<?php $this->import("head"); ?>
<script src="<?php echo $imgCdnUrl ?>/js/My97DatePicker/WdatePicker.js"></script>
<script>
    $(document).ready(function() {
        // $("#type_1").click(function() {
        //     $("#show_1").show();
        //     $("#show_2").hide();
        // });
        // $("#type_2").click(function() {
        //     $("#show_2").show();
        //     $("#show_1").hide();
        // });
        // $("#type_3").click(function() {
        //     $("#show_2").hide();
        //     $("#show_1").hide();
        // });
        $("#lotteryType").change(function() {
            var lotteries = <?php echo $json_typeLotterys; ?>;
            $("#lottery_id").html("");
            //var shtml ="<select name='lottery' id='lottery'>";
            var shtml = "<option value='0'>请选择</option>";
            if ($("#lotteryType").val() >= 0)
            {
                $.each(lotteries[$("#lotteryType").val()], function(i, v) {
                    shtml = shtml + "<option value='" + v.lottery_id + "'>" + v.cname + "</option>";
                });
            }
            //shtml += "</select>";
            $("#lottery_id").html(shtml);
        });

        // POST载入奖期列表
        $("#lottery_id").change(function() {
            $.ajax({
                type: "POST",
                url: "?c=draw&a=cancelProject",
                dataType: "json",
                data: "sa=getIssue&lottery_id=" + $(this).val(),
                success: function(json_data)
                {
                    var json = json_data;
                    var tmp = '<option value="-1">请选择奖期</option>';
                    $.each(json_data, function(i, v) {
                        tmp += "<option value='" + v.issue + "'>" + v.issue + " (" + v.start_sale_time + " 至 " + v.end_sale_time + ")(" + v.code + ")</option>";
                    });
                    $('#issue').html(tmp);
                }
            });
        });

        $("#form1").submit(function() {
            ondisabled();
            if ($("#lottery_id").val() == -1) {
                alert("彩种ID不正确！");
                offdisabled();
                return false;
            }
            if ($("#issue").val() == -1) {
                alert("奖期不正确！");
                offdisabled();
                return false;
            }
            var type = $(":radio:checked[name='type']").val();
            if (type == undefined) {
                alert("处理原因不正确,请选择处理类型");
                offdisabled();
                return false;
            }
            // if (type == 1 && $("#real_start_time").val() == '') {
            //     alert("请输入官方实际开奖时间！");
            //     offdisabled();
            //     return false;
            // }
            // if (type == 2 && $("#real_code").val() == '') {
            //     alert("请输入正确开奖号码！");
            //     offdisabled();
            //     return false;
            // }
            return true;
        });
    });

    function ondisabled() {
        $("#btsubmit").attr("disabled", true);
    }

    function offdisabled() {
        $("#btsubmit").attr("disabled", false);
    }
</script>
<div class="list-div " id="addDiv">
    <form name="form1" class="add-main form-top" id="form1" action="./?c=draw&a=<?php echo ACTION; ?>" method="post" onsubmit="return checkform(this)">
        <table class="table table-responsive table-bordered" cellpadding="0" cellspacing="0" style="width: 50%;">
            <tr>
                <td class="rowTitle tl" colspan="2">
                    <b>系统撤单</b>
                </td>
            </tr>
            <tr>
                <td class="narrow-label" width="20%"><strong>注意：</strong></td>
                <td width="80%"><span style="color:#FF0000;">异常处理时间限制在 <?php echo $issue_exception_limit; ?> 分钟内</span></td>
            </tr>
            <tr>
                <td class="narrow-label">游戏名称</td>
                <td>
                    <div class="form-inline">
                        <select class="input-md form-control" name="lotteryType" id="lotteryType">
                            <option value="0">请选择</option>
                            <?php foreach ($lotteryTypes as $k => $v): ?>
                            <option value="<?php echo $k; ?>"><?php echo $v; ?></option>
                            <?php endforeach; ?>
                        </select>
                        <select class="input-md form-control" name="lottery_id" id="lottery_id">
                            <option value="0">请选择</option>
                        </select>
                    </div>
                </td>
            </tr>

            <tr>
                <td class="narrow-label">游戏奖期</td>
                <td><span id="issuelist">
                        <select class="input-md form-control" name='issue' id="issue">
                            <option value="-1">请选择奖期</option>
                        </select></span>
                </td>
            </tr>

            <tr>
                <td class="narrow-label">处理原因</td>
                <td>
                    <label for="type_1"><input type="radio" value="1" name="type" id="type_1">提前开奖</label>&nbsp;&nbsp;&nbsp;&nbsp;
                    <label for="type_2"><input type="radio" value="2" name="type" id="type_2">开奖号码错误</label>&nbsp;&nbsp;&nbsp;&nbsp;
                    <label for="type_3"><input type="radio" value="3" name="type" id="type_3">官方未开奖</label>&nbsp;&nbsp;&nbsp;&nbsp;
                    <label for="type_4"><input type="radio" value="4" name="type" id="type_4">重新判奖</label>
                </td>
            </tr>
            <tr id="show_1" style="display:none;">
                <td class="narrow-label">官方实际开奖时间</td>
                <td><input class="input-md form-control" type='text' id="real_start_time" name="real_start_time" onfocus="WdatePicker({dateFmt: 'yyyy-MM-dd HH:mm:ss'})">
                </td>
            </tr>
            <tr id="show_2" style="display:none;">
                <td class="narrow-label">正确的开奖号码</td>
                <td><input class="input-md form-control" type="text" name="real_code" id="real_code" value="" style="">
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <div style="width: 50%;margin: 0 auto;text-align: center;">
                        <input class="btn btn-info submit" type="submit" style="width: 60px;"  name="submit" value="<?php if (substr(ACTION, 0, 4) == "edit"): ?>更新<?php else: ?>提交<?php endif; ?>" />
                        <input class="btn btn-info submit" style="width: 60px;" type="button"  onclick="javascript:history.go(-1);" value="返回"/>
                        <input type="hidden" name="sa" value="cancelProject">
                    </div>
                </td>

            </tr>
        </table>
    </form>
</div>
<div class="list-div" id="listDiv">
    <form class="form-top">
        <table class="table table-responsive table-bordered mainList " style="margin-top:20px;" >
            <thead>
                <tr>
                    <td>ie_id</td>
                    <td>彩种</td>
                    <td>奖期</td>
                    <td>错误类型</td>
                    <td>开奖时间</td>
                    <td>登记时间</td>
                    <td>登记人</td>
                    <td>错误号</td>
                    <td>旧状态</td>
                    <td>旧返点</td>
                    <td>旧中奖</td>
                    <td>旧派奖</td>
                    <td>正确号码</td>
                    <td>新状态</td>
                    <td>新返点</td>
                    <td>新中奖</td>
                    <td>新派奖</td>
                    <td>撤销派奖</td>
                    <td>撤单状态</td>
                    <td>操作</td>
                </tr>
            </thead>
            <?php foreach ($issueErrors as $key => $v): ?>
                <tr>
                    <td><?php echo $v['ie_id']; ?></td>
                    <td><?php echo $v['lottery_name']; ?></td>
                    <td><?php echo $v['issue']; ?></td>
                    <td>
                        <?php if ($v['type'] == '1'): ?>
                            官方提前开奖[撤销派奖+系统撤单]
                        <?php elseif ($v['type'] == '2'): ?>
                            录入号码错误[撤销派奖+重新判断中奖+重新派奖]
                        <?php elseif ($v['type'] == '3'): ?>
                            官方未开奖
                        <?php endif; ?>
                    </td>

                    <td><?php echo $v['open_time']; ?></td>
                    <td><?php echo $v['create_time']; ?></td>
                    <td><?php echo $v['admin_user']; ?></td>
                    <td><?php echo $v['old_code']; ?></td>
                    <td>
                        <?php if ($v['old_status_code'] == '0'): ?>
                            未写入
                        <?php elseif ($v['old_status_code'] == '1'): ?>
                            写入待验证
                        <?php elseif ($v['old_status_code'] == '2'): ?>
                            已验证
                        <?php endif; ?>
                    </td>
                    <td>
                    <?php if ($v['old_status_rebate'] == '0'): ?>
                        未开始
                    <?php elseif ($v['old_status_rebate'] == '1'): ?>
                        进行中
                    <?php elseif ($v['old_status_rebate'] == '2'): ?>
                        已完成
                    <?php endif; ?>
                    </td>
                    <td>
                        <?php if ($v['old_status_check_prize'] == '0'): ?>
                            未开始
                        <?php elseif ($v['old_status_check_prize'] == '1'): ?>
                            进行中
                        <?php elseif ($v['old_status_check_prize'] == '2'): ?>
                            已完成
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php if ($v['old_status_send_prize'] == '0'): ?>
                            未开始
                        <?php elseif ($v['old_status_send_prize'] == '1'): ?>
                            进行中
                        <?php elseif ($v['old_status_send_prize'] == '2'): ?>
                            已完成
                        <?php endif; ?>
                    </td>
                    <td><?php echo $v['code']; ?></td>
                    <td>
                        <?php if ($v['status_code'] == '0'): ?>
                            未写入
                        <?php elseif ($v['status_code'] == '1'): ?>
                            写入待验证
                        <?php elseif ($v['status_code'] == '2'): ?>
                            已验证
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php if ($v['status_rebate'] == '0'): ?>
                            未开始
                        <?php elseif ($v['status_rebate'] == '1'): ?>
                            进行中
                        <?php elseif ($v['status_rebate'] == '2'): ?>
                            已完成
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php if ($v['status_check_prize'] == '0'): ?>
                            未开始
                        <?php elseif ($v['status_check_prize'] == '1'): ?>
                            进行中
                        <?php elseif ($v['status_check_prize'] == '2'): ?>
                            已完成
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php if ($v['status_send_prize'] == '0'): ?>
                            未开始
                        <?php elseif ($v['status_send_prize'] == '1'): ?>
                            进行中
                        <?php elseif ($v['status_send_prize'] == '2'): ?>
                            已完成
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php if ($v['status_cancel_prize'] == '0'): ?>
                            未开始
                        <?php elseif ($v['status_cancel_prize'] == '1'): ?>
                            进行中
                        <?php elseif ($v['status_cancel_prize'] == '2'): ?>
                            已完成
                        <?php elseif ($v['status_cancel_prize'] == '9'): ?>
                            被忽略
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php if ($v['status_repeal'] == '0'): ?>
                            未开始
                        <?php elseif ($v['status_repeal'] == '1'): ?>
                            进行中
                        <?php elseif ($v['status_repeal'] == '2'): ?>
                            已完成
                        <?php elseif ($v['status_repeal'] == '9'): ?>
                            被忽略
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php if ($canDelete): ?>
                            <a class="btn btn-mini btn-info f14" href="./?c=draw&a=deleteIssueError&ie_id=<?php echo $v['ie_id']; ?>" onclick="return confirm('真的假的？');">删除</a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </form>
</div>
<div class="pageTal"><?php echo $pageList; ?></div>

<?php $this->import("foot"); ?>