<?php $this->import("head"); ?>
<script>
$(document).ready(function(){
   $("input[name=rank]").val("<?php echo $drawSource['rank']; ?>");
   $("input[name=ds_id]").val("<?php echo $drawSource['ds_id']; ?>");
});
function checkform(ob) {
    var msg = "";
    if (ob.rank.value <= 0) {
        msg = "请输入权重";
    }
//    else if (ob.usage[0].checked == false && ob.usage[1].checked == false) {
//        msg = "请选择用途";
//    }

    if (msg != "") {
        alert(msg);
        return false;
    }
    return true;
}
</script>
<div class="list-div mt20" id="addDiv">
<form name="form1" id="form1" action="./?c=draw&a=<?php echo ACTION; ?>" method="post" onsubmit="return checkform(this)">
<table class="table table-responsive table-bordered" cellpadding="0" cellspacing="0" style="width: 65%;">
    <tr>
    <td style="font-weight: bold;text-align: left;vertical-align: middle;" class="narrow-label">游戏名称</td>
    <td style="vertical-align: middle;"><?php echo $lotteries[$drawSource['lottery_id']]['name']; ?></td>
    </tr>
    <tr>
        <td style="font-weight: bold;text-align: left;vertical-align: middle;">号源网站名称</td>
        <td style="vertical-align: middle;"><?php echo $drawSource['name']; ?></td>
    </tr>
    <tr>
        <td style="font-weight: bold;text-align: left;vertical-align: middle;">详细网址</td>
        <td style="vertical-align: middle;"><?php echo $drawSource['url']; ?></td>
    </tr>
    <tr>
        <td style="font-weight: bold;text-align: left;vertical-align: middle;">权重</td>
        <td style="vertical-align: middle;"><input class="input-md form-control" name="rank"/></td>
    </tr>
    <tr>
        <td style="font-weight: bold;text-align: left;vertical-align: middle;">是否启用</td>
        <td style="vertical-align: middle;"><?php if ($drawSource['is_enabled'] == 1): ?>是<?php else: ?>否<?php endif; ?></td>
    </tr>
    <tr> 
        <td></td>
        <td colspan="2">
            <div style="width: 60%;margin: 0 auto;text-align: center;">
                <input class="btn btn-info submit" type="submit"  name="submit" value="<?php if (substr(ACTION, 0, 4) == "edit"): ?>更新<?php else: ?>提交<?php endif; ?>" />
                <input class="btn btn-info submit" type="button"  onclick="javascript:history.go(-1);" value="返回"/>
                <input type="hidden" name="ds_id" value="" />
            </div>
        </td>
    </tr>
</table>
    </form>
</div>

<?php $this->import("foot"); ?>