<?php $this->import("head"); ?>
<script src="<?php echo $imgCdnUrl ?>/js/jedate/jedate.js"></script>
<script src="<?php echo $imgCdnUrl ?>/js/jquery.tablesorter.js"></script>
<link href="<?php echo $imgCdnUrl ?>/css/tablesorter.css" rel="stylesheet" type="text/css" />
<style>
.tablesorter .tablesorter-header {
	background-image: url(data:image/gif;base64,R0lGODlhFQAJAIAAACMtMP///yH5BAEAAAEALAAAAAAVAAkAAAIXjI+AywnaYnhUMoqt3gZXPmVg94yJVQAAOw==);
	background-position: center right;
	background-repeat: no-repeat;
	cursor: pointer;
	white-space:nowrap;
	padding-right:16px;
}
.tablesorter thead .headerSortUp,
.tablesorter thead .tablesorter-headerSortUp,
.tablesorter thead .tablesorter-headerAsc {
	background-image: url(data:image/gif;base64,R0lGODlhFQAEAIAAACMtMP///yH5BAEAAAEALAAAAAAVAAQAAAINjI8Bya2wnINUMopZAQA7);
	border-bottom: #000 2px solid;
}
.tablesorter thead .headerSortDown,
.tablesorter thead .tablesorter-headerSortDown,
.tablesorter thead .tablesorter-headerDesc {
	background-image: url(data:image/gif;base64,R0lGODlhFQAEAIAAACMtMP///yH5BAEAAAEALAAAAAAVAAQAAAINjB+gC+jP2ptn0WskLQA7);
	border-bottom: #000 2px solid;
}
.tablesorter thead .sorter-false {
	background-image: none;
	cursor: default;
	padding: 4px;
}

.tablesorter td {
    white-space:nowrap;
    padding:5px;
    }
.jedatehms{display: none!important;}
</style>

<script>
    $(function() {

        //设置默认值
        // 巧妙的改变一下吧,这不是扯把子,你试了会明白的.
        //>>author snow,谁改的.胡些jquery版本用不了,涉及到状态值的最好用prop  .
//        $('#isGroupBy').attr('checked', <?php //echo $isGroupBy == '1' ? 'true' : 'false';?>//).on('change',function(){
//            $('input[name=isGroupBy]').val($(this).attr('checked') ? 1 : 0);
//        });

        /************* author snow ***********************************/
        $('#isGroupBy').prop({'checked' : <?php echo $isGroupBy == 1 ? 'true' : 'false'; ?>});
        $('#isGroupBy').click(function () {
            $('input[name=isGroupBy]').val($(this).prop('checked') ? 1 : -1)
        });
        /************* author snow ***********************************/
        $('#startDate').val('<?php echo $startDate; ?>');
        $('#endDate').val('<?php echo $endDate; ?>');
        $('select[name=top_id]').val('<?php echo $top_id; ?>');
        $('select[name=game_type]').val('<?php echo $gameType; ?>');
        $('select[name=pageSize]').val('<?php echo $pageSize; ?>');
        //$("#myTable").tablesorter({ sortList: [[0,1]] });
        $('.tablesorter').tablesorter({
        	sortList : [[3,1]],
            // set forced sort on the fourth column and i decending order.
             headers: {
            	0	: { sorter: false }	,	//user_id
            	1	: { sorter: true }	,	//总代用户名
            	2	: { sorter: true }	,	//日期
            	3	: { sorter: true }	,	//投注量
            	4	: { sorter: true }	,	//中奖量
            	5	: { sorter: true }	,	//返点量
            	6	: { sorter: true }	,	//游戏盈亏
            	7	: { sorter: true }	,	//开户人数
            	8	: { sorter: true }	,	//存款量
            	9	: { sorter: true }	,	//提款量
            	10	: { sorter: true }	,	//首存人数
            	11	: { sorter: true }	,	//首存量
            	12	: { sorter: false }	,	//前日余额
            	13	: { sorter: false }	,	//当日余额
            	14	: { sorter: false }	,	//pt前日余额
            	15	: { sorter: false }	,	//pt当日余额
//            	16	: { sorter: true }	,	//pt投注量
//            	17	: { sorter: true }	,	//pt盈亏
//            	18	: { sorter: true }	,	//实际盈亏
//            	19	: { sorter: true }	,	//优惠量
//            	20	: { sorter: true }	,	//差帐
//            	21	: { sorter: false }     //图表显示
             }
        });

        /******************** author snow 修改查询功能为 实时查询+历史查询************************************/

        $('.find-data').click(function () {
            //>>添加点击事件,进行分别请求
            var buttonName = $(this).attr('name');
            //>>开始日期
            var start = $('#startDate').val();
            //>>结束日期
            var end   = $('#endDate').val();
            switch (buttonName) {
                case 'history' :  //>>查询历史记录
                    historyClick(start, end);
                    break;
                case 'live' :     //>>查询实时记录
                    liveClick();
                    break;
            }

        })

        //>>实时数据查询
        function liveClick() {
            //>>修改参数值,使后台可以识别是进行实时查询
            $('#is-live').val('true');
            //>>不需要开始时间与结束时间,后台自动计算
            $('#form1').submit();

        }

        //>>历史查询方法
        function historyClick(start, end) {
            if (validateDateTime(start) && validateDateTime(end) && start <= end) {
                //>>验证通过.进行查询
                //>>修改参数的值,使后台识别是进行历史数据查询
                $('#is-live').val('false');
                $('#form1').submit();
            } else {
                //>>使用了iframe so你懂的
                try {
                    window.parent.layer.alert('日间格式或输入不正确,且开始时间必须小于结束时间');
                } catch (e) {
                    alert('日间格式或输入不正确,且开始时间必须小于结束时间')
                }
                return false;
            }
        }

        //>>验证日期格式是否正确.且开始日期是否小于结束日期
        function validateDateTime(testdate) {

            var date_regex = /^((19|20)[0-9]{2})-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])$/;
            var res = date_regex.test(testdate);
            if(res) {
                var ymd = testdate.match(/(\d{4})-(\d+)-(\d+).*/);
                var year = parseInt(ymd[1]);
                var month = parseInt(ymd[2]);
                var day = parseInt(ymd[3]);
                if(day > 28) {
                    //获取当月的最后一天
                    var lastDay = new Date(year, month, 0).getDate();
                    return (lastDay >= day);
                }
                return true;
            }
            return false;
        }
        //>>加载完成后进行判断..如果是实时查询,需要隐藏部分字段 如果是历史查询则显示相应字段

        var isLive = $('#is-live').val();
        var backWater = $('.back-water');
        if (isLive == 'false') {
            backWater.show();
        } else {
            backWater.hide();
        }
        /******************** author snow 修改查询功能为 实时查询+历史查询************************************/
    });
</script>

    <!------------------ author snow引入搜索相关文件--------------------------->

    <link rel="stylesheet" href="/js/jquery-select/bootstrop-select.css">
    <script src="/js/jquery-select/bootstrop.min.js"></script>
    <script src="/js/jquery-select/bootstrop-select.js"></script>
    <!------------------ author snow引入搜索相关文件--------------------------->
<form name="form1" class="form-top" id="form1" action="" method="GET">
    <div class="form-inline mt20">
        <div class="form-group has-default has-feedback">
            <label class="ml10">日期:</label>
            <input title="开始日期" class="input-md form-control Wdate" type="text" name="startDate" id="startDate"  onclick="jeDate({dateCell:'#startDate',isTime:true,format:'YYYY-MM-DD'})" />
            <span class="glyphicon glyphicon-calendar form-control-feedback"></span>
        </div>
        <div class="form-group has-default has-feedback">
            <label>到</label>
            <input title="结束日期" class="input-md form-control Wdate " type="text" name="endDate" id="endDate"  onclick="jeDate({dateCell:'#endDate',isTime:true,format:'YYYY-MM-DD'})"/>
            <span class="glyphicon glyphicon-calendar form-control-feedback"></span>
        </div>
        <label class="ml10">每页显示条数:</label>
        <select class="input-md form-control"  title="每页显示条数" name="pageSize">
            <option value="20">20条</option>
            <option value="50">50条</option>
            <option value="100">100条</option>
        </select>
        <label class="ml10">所属总代:</label>
        <select id="top-username" class="selectpicker snow-topUser-search" name="top_id" data-live-search="true" title="请选择 ...">
            <option value="-1">请选择…</option>
            <?php foreach ($json_topUsers as $k => $v): ?>
                <option value="<?=$v['user_id']?>"><?=$v['username']?></option>
            <?php endforeach; ?>
        </select>
        <?php if ($gameTypes != null): ?>
        <label class="ml10">游戏类型:</label>
        <select title="游戏类型" class="input-md form-control" name="game_type">
            <option value="-1">请选择</option>
            <?php foreach ($gameTypes as $key => $value): ?>
                <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
            <?php endforeach; ?>
        </select>
        <?php endif; ?>

        <input type="checkbox" id="isGroupBy" value="1" />
        <label for="isGroupBy">按用户统计</label>
        <input type="hidden" name="isGroupBy" value="<?=$isGroupBy?>"/>
        <input type="hidden" name="c" value="game"/>
        <input type="hidden" name="a" value="teamReport"/>
        <input type="hidden" id="showType" name="showType" value="table" />
        <input type="hidden" id="is-live" name="isLive" value="<?=$isLive?>" />
        <input class="btn btn-info submit ml10 submit find-data" style="width: 60px;" type="button" name="history" value="提交"/>
        <!------------------------ 暂时注释,功能还未开发完成 ,且不能提交---------------------------------->
<!--        <input class="btn btn-info submit ml10 submit find-data" style="width: 60px;" type="button" name="live" value="实时查询"/>-->
        <hr>
    </div>
</form>
<b>注一：按惯例，为负表示客户赢钱平台输钱，为正表示客户输钱平台赢钱；</b><br>
<!--<b>注二：现提供实时查询数据功能按钮，之前功能保持不变，查询今日之前历史数据。</b>-->
<div class="list-div mt15" id="listDiv" style="border:0px">
    <table class="table table-responsive table-bordered  mainList tablesorter" id='my   Table'>
        <thead>
            <tr>
                <td>user_id</td>
                <td>总代用户名</td>
                <td>日期</td>
                <td id="defaultOrder">投注量</td>
                <td>中奖量</td>
                <td>返点量</td>
                <!--------------------- snow 修改游戏盈亏为损益 修改公式 为 ----------------------------------->
                <!--------------------- snow 修改公式为:游戏盈亏 = 中奖量  - 投注量 --------------------------->
                <td title="损益 = 投注量  - 中奖量">损益</td>
                <td>开户人数</td>
                <td>存款量</td>
                <td>提款量</td>
                <td>存款人数</td>
                <td>首存量</td>
                <!--------------------- snow 损益 为盈亏         --------------------------->
                <td title="盈亏 = 存款量- 提款量">盈亏</td>
                <!------------------------------再次修改名称------------------------>
                <td>充值优惠</td>
                <td class="back-water">投注日返水</td>
                <!------------------------------再次修改名称------------------------>
            </tr>
        </thead>
        <?php foreach ($teamReport as $v): ?>
            <tr>
                <td><?php echo $v['user_id']; ?></td>
                <td title="<?php echo $v['user_id']; ?>"><?php echo $topUsers[$v['user_id']]['username']; ?><?php if ($v['type'] == 1): ?><b style="color:red">[推广]</b><?php endif; ?></td>
                <td><?php echo $v['belong_date']; ?></td>
                <td><?php echo number_format($v['buy_amount'], 2); ?></td>
                <td><?php echo number_format($v['prize_amount'], 2); ?></td>
                <td><?php echo number_format($v['rebate_amount'], 2); ?></td>
                <td>
                        <font color="<?=$v['game_win'] < 0 ? 'red' : ''?>"><?php echo number_format($v['game_win'], 2); ?></font>
                </td>
                <td><?php echo $v['reg_num'] > 0 ? $v['reg_num'] : 0 ; ?></td>
                <td><?php echo number_format($v['deposit_amount'], 2); ?></td>
                <td><?php echo number_format($v['withdraw_amount'], 2); ?></td>
                <td><?php echo $v['first_deposit_num'] > 0 ? $v['first_deposit_num'] : 0 ; ?></td>
                <td><?php echo number_format($v['first_deposit_amount'], 2); ?></td>
                <td>
                        <font color="<?=$v['real_win'] < 0 ? 'red' : ''?>"><?php echo number_format($v['real_win'], 2); ?></font>
                </td>
                <td>
                        <?php echo number_format($v['promos'], 2); ?>
                </td>
                <!--添加投注日返水 -->
                <td class="back-water">
                    <?php echo number_format($v['back_water'], 2); ?>

                </td>
            </tr>
        <?php endforeach; ?>
        <tfoot>
        <tr>
            <td colspan="3">本页小计</td>
            <td><?php echo number_format($totalInfo['buy_amount'], 2); ?></td>
            <td><?php echo number_format($totalInfo['prize_amount'], 2); ?></td>
            <td><?php echo number_format($totalInfo['rebate_amount'], 2); ?></td>
            <td>
                    <font color="<?=$totalInfo['game_win'] < 0 ? 'red' : ''?>"><?php echo number_format(($totalInfo['game_win']), 2); ?></font>
            </td>
            <td><?php echo $totalInfo['reg_num']; ?></td>
            <td><?php echo number_format($totalInfo['deposit_amount'], 2); ?></td>
            <td><?php echo number_format($totalInfo['withdraw_amount'], 2); ?></td>
            <td><?php echo $totalInfo['first_deposit_num']; ?></td>
            <td><?php echo number_format($totalInfo['first_deposit_amount'], 2); ?></td>
            <td style="text-align: center;vertical-align: middle;">
                <?php if ($totalInfo['real_win'] < 0): ?>
                    <font color="red"><?php echo number_format($totalInfo['real_win'], 2); ?></font>
                <?php else: ?>
                    <?php echo number_format($totalInfo['real_win'], 2); ?>
                <?php endif; ?>
            </td>
            <td style="text-align: center;vertical-align: middle;">
                    <?php echo number_format($totalInfo['promos'], 2); ?>
            </td>
            <td class="back-water">
             <?php echo number_format($totalInfo['back_water'], 2); ?>
            </td>
        </tr>
        </tfoot>
    </table>
</div>
<div class="pageTal"><?php echo $pageList; ?></div>

<?php $this->import("foot"); ?>