<?php $this->import("head"); ?>
<script src="<?php echo $imgCdnUrl ?>/js/My97DatePicker/WdatePicker.js"></script>
<div class="list-div" id="addDiv">
<form name="form1" id="form1" action="./?c=lottery&a=<?php echo ACTION; ?>&lottery_id=<?php echo $lottery['lottery_id']; ?>" method="post">
    <table class="table table-responsive table-bordered form-top" style="width: 60%">
        <tr>
            <td>所属彩种</td>
            <td><?php echo $lottery['cname']; ?></td>
        </tr>
        <tr>
            <td>休市日期</td>
            <td>
                <?php echo $lottery['yearly_start_closed']; ?> 至 <?php echo $lottery['yearly_end_closed']; ?>
            </td>
        </tr>
        <tr>
            <td>奖期生成日期</td>
            <td id = 'ir'>
                <!-- <div>Issue<input name="issue[]" value="" size="10"/>From<input name="startDate[]" id="startDate" my97mark="false" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss'})" class="Wdate">To<input name="endDate[]" id="endDate[]" my97mark="false" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss'})" class="Wdate"><br>
                </div> -->

                <div class="form-inline">
                    <div>Issue<input class="form-control input-md" name="issue[]" value="" size="10"/>
                    <div class="form-group has-default has-feedback">
                        From<input name="startDate[]" my97mark="false" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss'})" size="30">
                        <span class="glyphicon glyphicon-calendar form-control-feedback"></span>
                    </div>
                    <div class="form-group has-default has-feedback">
                        To<input name="endDate[]" my97mark="false" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss'})"  size="30">
                        <span class="glyphicon glyphicon-calendar form-control-feedback"></span>
                    </div>
                    
                    <br>
                </div>
                </div>




            </td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="button" class="submit" value="添加奖期" />
                <input type="submit" class="submit" name="submit" value="批量生成奖期" />
                <input type="button" class="submit" onclick="javascript:history.go(-1);" value="返回"/>
                <input type="hidden" name="sa" value="genIssue">
            </td>
        </tr>
</table>
</form>
</div>

<script>
$(document).ready(function(){
   $(":button").click(function(){
        var doc = $('#ir > div:first').html();
        $('#ir').append('<div class="form-inline">'+doc+'</div>');
   });
});
</script>

<?php $this->import("foot"); ?>