<?php $this->import("head"); ?>
<script>
    function checkform(ob) {
        var msg = "";

        if ($('input[name=username]').val() == '') {
            msg = '请输入用户名！';
        }
        if ($('input[name=promo_amount]').val() == '' || !/\d[\d\.]+/.test($('input[name=promo_amount]').val())) {
            msg = '请输入正确的金额！';
        }

        if (msg != "") {
            alert(msg);
            return false;
        }
        return true;
    }

</script>
<div class="list-div" id="addDiv">
    <form name="form1" id="form1" action="./?c=promo&a=<?php echo ACTION; ?>" method="post" onsubmit="return checkform(this)">
        <table cellpadding="0" cellspacing="0" width="40%" border="0">
            <tr>
                <td>优惠类型</td>
                <td>
                    <div id="notes">
                        	平台理赔：<input type="text" name="type" id="type_1" value="4" style="display:none" />
                    </div>
                </td>
            </tr>
            <tr>
                <td>用户名</td>
                <td><input name="username"/></td>
            </tr>
            <tr>
                <td>优惠金额</td>
                <td><input name="promo_amount" onkeyup="value=value.replace(/[^\d{1,}\.\d{1,}|\d{1,}]/g,'')"/></td>
            </tr>
            <tr>
                <td colspan="2"><input type="submit" class="submit" name="submit" value="提交" />
                    <input type="button" class="submit" onclick="javascript:history.go(-1);" value="返回"/>
            </tr>
        </table>
    </form>
</div>

<?php $this->import("foot"); ?>