<?php $this->import("default_top"); ?>
<?php $this->import("default_left"); ?>
<link rel="stylesheet" href="<?php echo $imgCdnUrl ?>/view/new/css/user-level.css" />

<script type="text/html" id="user_level_tool" >
  <div class="user-live-gird-button user-live-gird-button-lc1" lay-event="edit"><span>编辑</span></div>
  <div class="user-live-gird-button user-live-gird-button-lc2" lay-event="delete"><span>删除</span></div>
</script>

<div class="dc-right-body custom-defind-common dc-body-common-div">
  <div  class="dc-user-management-top" >
    <div class="dc-user-management_title"><span>层级管理</span></div>
    <div id="user_level_addnew" class="domain-management-button" onclick="addNewLevel()" ><span>新增</span></div>
    <div id="user_level_delete" class="domain-management-button"><span>删除</span></div>
  </div>
  
  <div id="user_level_form" >
    <div id="user_level_form_account" >
      <span>代理账号：</span>
      <input type="text" name="" class="user-condition-input" placeholder="请输入层级名称" />
    </div>
    <div id="user_level_form_select" class="domain-management-button">
      <span>查询</span>
    </div>
  </div>
  
  <div id="user_level_list_grid">
    <table id="user_level_list" lay-filter="user_level_list" class="layui-table"
    	lay-data="{width:1195, height: 710, url:'', page: true, limit: 10, limits:[10]}">
      <thead>
        <tr>
          <th lay-data="{checkbox: true, width: 40} " rowspan="2" ></th>
          <th lay-data="{field: 'levelName', title: '层级名称', width: 90, align:'center'} " rowspan="2" ></th>
          <th lay-data="{field: 'disscription', title: '描述', width: 178, align:'center'} " rowspan="2" ></th>
          
          <th lay-data="{align:'center', style: 'font-weight:700;'}" colspan="4">层级条件</th>
          <th lay-data="{align:'center', style: 'font-weight:700;'}" colspan="2">投注返水</th>
          <th lay-data="{field: 'userTotal', title: '用户人数', width: 90, align:'center'} " rowspan="2" ></th>
          <th lay-data="{field: 'operator', title: '操作', width: 115, align:'center', toolbar: '#user_level_tool'} " rowspan="2" ></th>
        </tr>
        <tr>
          <th lay-data="{field: 'depositCount', title: '存款次数', width: 90, align:'center'} " ></th>
          <th lay-data="{field: 'depositTotal', title: '存款总额', width: 90, align:'center'} " ></th>
          <th lay-data="{field: 'regDate', title: '注册时间', width: 145, align:'center'} " ></th>
          <th lay-data="{field: 'firstDepositDate', title: '首存时间', width: 145, align:'center'} " ></th>
          <th lay-data="{field: 'lottey', title: '彩票', width: 100, align:'center'} " ></th>
          <th lay-data="{field: 'electronic', title: '电子', width: 100, align:'center'} " ></th>
        </tr>
      </thead>
      <tbody>
      	<tr>
      	  <td></td>
      	  <td>层级名称</td>
      	  <td>描述</td>
      	  <td>用户人数</td>
      	  <td>
      	  </td>
      	  <td>存款次数</td>
      	  <td>存款总额</td>
      	  <td>注册时间</td>
      	  <td>首存时间</td>
      	  <td>彩票</td>
      	  <td>电子</td>
      	</tr>
      	<tr>
      	  <td></td>
      	  <td>层级名称</td>
      	  <td>描述</td>
      	  <td>用户人数</td>
      	  <td>
      	    
      	    
      	  </td>
      	  <td>存款次数</td>
      	  <td>存款总额</td>
      	  <td>注册时间</td>
      	  <td>首存时间</td>
      	  <td>彩票</td>
      	  <td>电子</td>
      	</tr>
      	<tr>
      	  <td></td>
      	  <td>层级名称</td>
      	  <td>描述</td>
      	  <td>用户人数</td>
      	  <td>
      	    
      	    
      	  </td>
      	  <td>存款次数</td>
      	  <td>存款总额</td>
      	  <td>注册时间</td>
      	  <td>首存时间</td>
      	  <td>彩票</td>
      	  <td>电子</td>
      	</tr>
      	<tr>
      	  <td></td>
      	  <td>层级名称</td>
      	  <td>描述</td>
      	  <td>用户人数</td>
      	  <td>
      	    
      	    
      	  </td>
      	  <td>存款次数</td>
      	  <td>存款总额</td>
      	  <td>注册时间</td>
      	  <td>首存时间</td>
      	  <td>彩票</td>
      	  <td>电子</td>
      	</tr>
      	<tr>
      	  <td></td>
      	  <td>层级名称</td>
      	  <td>描述</td>
      	  <td>用户人数</td>
      	  <td>
      	    
      	    
      	  </td>
      	  <td>存款次数</td>
      	  <td>存款总额</td>
      	  <td>注册时间</td>
      	  <td>首存时间</td>
      	  <td>彩票</td>
      	  <td>电子</td>
      	</tr>
      	<tr>
      	  <td></td>
      	  <td>层级名称</td>
      	  <td>描述</td>
      	  <td>用户人数</td>
      	  <td>
      	    
      	    
      	  </td>
      	  <td>存款次数</td>
      	  <td>存款总额</td>
      	  <td>注册时间</td>
      	  <td>首存时间</td>
      	  <td>彩票</td>
      	  <td>电子</td>
      	</tr>
      	<tr>
      	  <td></td>
      	  <td>层级名称</td>
      	  <td>描述</td>
      	  <td>用户人数</td>
      	  <td>
      	    
      	    
      	  </td>
      	  <td>存款次数</td>
      	  <td>存款总额</td>
      	  <td>注册时间</td>
      	  <td>首存时间</td>
      	  <td>彩票</td>
      	  <td>电子</td>
      	</tr>
      	<tr>
      	  <td></td>
      	  <td>层级名称</td>
      	  <td>描述</td>
      	  <td>用户人数</td>
      	  <td>
      	    
      	    
      	  </td>
      	  <td>存款次数</td>
      	  <td>存款总额</td>
      	  <td>注册时间</td>
      	  <td>首存时间</td>
      	  <td>彩票</td>
      	  <td>电子</td>
      	</tr>
      	<tr>
      	  <td></td>
      	  <td>层级名称</td>
      	  <td>描述</td>
      	  <td>用户人数</td>
      	  <td>
      	    
      	    
      	  </td>
      	  <td>存款次数</td>
      	  <td>存款总额</td>
      	  <td>注册时间</td>
      	  <td>首存时间</td>
      	  <td>彩票</td>
      	  <td>电子</td>
      	</tr>
      	<tr>
      	  <td></td>
      	  <td>层级名称</td>
      	  <td>描述</td>
      	  <td>用户人数</td>
      	  <td>
      	    
      	    
      	  </td>
      	  <td>存款次数</td>
      	  <td>存款总额</td>
      	  <td>注册时间</td>
      	  <td>首存时间</td>
      	  <td>彩票</td>
      	  <td>电子</td>
      	</tr>
      	<tr>
      	  <td></td>
      	  <td>层级名称</td>
      	  <td>描述</td>
      	  <td>用户人数</td>
      	  <td>
      	    
      	    
      	  </td>
      	  <td>存款次数</td>
      	  <td>存款总额</td>
      	  <td>注册时间</td>
      	  <td>首存时间</td>
      	  <td>彩票</td>
      	  <td>电子</td>
      	</tr>
      	<tr>
      	  <td></td>
      	  <td>层级名称</td>
      	  <td>描述</td>
      	  <td>用户人数</td>
      	  <td>
      	    
      	    
      	  </td>
      	  <td>存款次数</td>
      	  <td>存款总额</td>
      	  <td>注册时间</td>
      	  <td>首存时间</td>
      	  <td>彩票</td>
      	  <td>电子</td>
      	</tr>
      	<tr>
      	  <td></td>
      	  <td>层级名称</td>
      	  <td>描述</td>
      	  <td>用户人数</td>
      	  <td>
      	    
      	    
      	  </td>
      	  <td>存款次数</td>
      	  <td>存款总额</td>
      	  <td>注册时间</td>
      	  <td>首存时间</td>
      	  <td>彩票</td>
      	  <td>电子</td>
      	</tr>
      </tbody>
      
      
    </table>
  </div>
    
</div>
<script type="text/javascript">
	layui.use('table', function(){
	   var table = layui.table;
	   table.on('tool(user_level_list)', function(obj) {
			var rowData = obj.data;
			var layEvent = obj.event;
			var tr = obj.tr;
			debugger
			if('edit' == layEvent){
				
			}else if('delete' == layEvent){
				
			}
	   });
	});
</script>










































