<?php $this->import("default_top"); ?>
<?php $this->import("default_left"); ?>
<link rel="stylesheet" href="<?php echo $imgCdnUrl ?>/view/new/css/user-loglist.css" />

<div class="dc-right-body custom-defind-common dc-body-common-div">
  <div  class="dc-user-management-top" >
    <div class="dc-user-management_title"><span>登录日志</span></div>
  </div>
  
  <form id="user_loglist_form" >
  
    <div id="user_condition_login_start">
      <p><span>注册时间：</span></p>
      <input type="text" id="user_login_start" name="" class="user-condition-input" >
      <img alt="" src="<?php echo $imgCdnUrl ?>/view/new/img/date.png">
    </div>
    <div id="user_condition_login_end">
	  <p><span>至：</span></p>
      <input type="text" id="user_login_end" name="" class="user-condition-input" > 
      <img alt="" src="<?php echo $imgCdnUrl ?>/view/new/img/date.png"> 	    
    </div>
    <div id="user_login_username" >
  	  <p><span>用户名：</span></p>
  	  <input type="text" id="login_user_name" name="" class="user-condition-input" />
  	</div>
  	<div id="user_login_ip" >
  	  <p><span>IP：</span></p>
  	  <input type="text" id="login_user_ip" name="" class="user-condition-input" />
  	</div>
  
    <div id="user_login_button"><span>搜索</span></div>
  
  </form>
  
  <div id="user_login_gird"><table id="loadLoginData" lay-filter="loadLoginData"></table></div>
</div>
<script type="text/javascript">
	layui.use('laydate', function(){
		var laydate = layui.laydate;
		laydate.render({
			elem:'#user_login_start'
		});
		laydate.render({
			elem:'#user_login_end'
		});
	});

	layui.use('table', function(){
		var table = layui.table;
		table.render({
		    elem: '#loadLoginData',
		    width: 1190,
		    height: 720,
		    url: '', //数据接口
		    page: true, //开启分页
		    limit: 15,
		    limits: [15,30,45,60,75,90],
		    cols: [[ //表头
		      {field: 'userName', title: '用户名称', width:175, align:'center', unresize:true},
		      {field: 'loginTyle', title: '登录方式', width: 175, align:'center', unresize:true},
		      {field: 'loginAddress', title: '登录IP', width: 280, align:'center', unresize:true},
		      {field: 'lastLoginTime', title: '最后登录时间', width: 420, align:'center', unresize:true},
		      {field: 'onlineStatus', title: '在线状态', width: 134, align:'center', unresize:true}
		    ]]
		  });
	});
</script>





