<?php $this->import("head"); ?>
<script>
//预设编辑值
$(document).ready(function(){
    $('#form1').submit(function(){
        if ($.trim($('input[name=name]').val()) == '') {
            alert('请输入名字');
            return false;
        }

        return true;
    })

    <?php if (ACTION == 'editCategory'): ?>
        $("input[name=category_id]").val("<?php echo $category['category_id']; ?>");
        $("input[name=name]").val("<?php echo $category['name']; ?>");
    <?php endif; ?>
});
</script>
<div class="list-div add-main form-top" id="addDiv">
<form name="form1" id="form1" action="?c=article&a=<?php echo ACTION; ?>" method="post">
<table class="table table-responsive table-bordered" cellpadding="0" cellspacing="0" style="width: 50%;">
    <tr>
        <td colspan="2" class="rowTitle">
            <b>分类</b>
        </td>
    </tr>
    <tr>
        <td>分类名</td>
        <td><input class="input-md form-control
        " name="name" size="20"/></td>
    </tr>
    <tr>
        <td colspan="2">
            <div style="width: 50%;margin: 0 auto;text-align: center;">
                <input class="btn btn-info submit" type="submit" style="width: 60px" name="submitBtn" value="<?php if (ACTION == "addCategory"): ?>提交<?php else: ?>更新<?php endif; ?>" />
                <input class="btn btn-info submit" type="button" style="width: 60px"  onclick="javascript:history.go(-1);" value="返回"/>
                <input type="hidden" name="category_id" value="" />
            </div>
        </td>

    </tr>
</table>
    </form>
</div>

<?php $this->import("foot"); ?>