<?php $this->import("head"); ?>

<script>
$(document).ready(function(){
   var action="<?php echo ACTION; ?>";
   if (action == 'editGroup') {
       $("input[name=cg_id]").val("<?php echo $group['cg_id']; ?>");
       $("input[name=ref_group_id]").val("<?php echo $group['ref_group_id']; ?>");
       $("input[name=name]").val("<?php echo $group['name']; ?>");
       $("input[name=level_amount]").val("<?php echo $group['level_amount']; ?>");
       $("input[name=deposit_count]").val("<?php echo $group['deposit_count']; ?>");
       $("input[name=commission_percentage]").val("<?php echo $group['commission_percentage']; ?>");
       $("input[name=egame_commission_percentage]").val("<?php echo $group['egame_commission_percentage']; ?>");
       $("input[name=sort]").val("<?php echo $group['sort']; ?>");
       $("input[name=status]").attr("<?php $status = $group['status']; if ($status == 1) { echo 'checked'; } else { echo ''; } ?>", "");
       $("input[name=is_fixed]").attr("<?php $is_fixed = $group['is_fixed']; if ($is_fixed == 1) { echo 'checked'; } else { echo ''; } ?>", "");
   }
});
function checkform(ob) {
    var msg = "";
    if (ob.name.value == "") {
        msg = "请输入名称";
    }
//    else if (ob.usage[0].checked == false && ob.usage[1].checked == false) {
//        msg = "请选择用途";
//    }

    if (msg != "") {
        alert(msg);
        return false;
    }
    return true;
}
</script>
<div class="list-div add-main mt20" id="addDiv">
  <form name="form1" id="form1" class="form-top" action="./?c=card&a=<?php echo ACTION; ?>" method="post" onsubmit="return checkform(this)">
    <table class="table table-responsive table-bordered" cellpadding="0" cellspacing="0" style="width:60%;">
        <tr>
            <td class="fb" width="20%">卡组 ID</td>
            <td>
                <input class="input-md form-control" name="ref_group_id" maxlength="19"/>
            </td>
        </tr>
        <tr>
            <td class="fb">卡组名称</td>
            <td><input class="input-md form-control" name="name" maxlength="19"/></td>
        </tr>
        <tr>
            <td class="fb">金额</td>
            <td><input class="input-md form-control" name="level_amount"/></input></td>
        </tr>
        <tr>
            <td class="fb">存款次数</td>
            <td><input class="input-md form-control" name="deposit_count"/></input></td>
        </tr>
        <tr>
            <td class="fb">返水</td>
            <td><input class="input-md form-control" name="commission_percentage"/></input></td>
        </tr>
        <tr>
            <td class="fb">电子返水</td>
            <td><input class="input-md form-control" name="egame_commission_percentage"/></input></td>
        </tr>
           <tr>
            <td class="fb">启用</td>
            <td><input type="checkbox" name="status"></td>
        </tr>
        </tr>
           <tr>
            <td class="fb">是否固定</td>
            <td><input type="checkbox" name="is_fixed"></td>
        </tr>
        <tr>
            <td class="fb">排序（越小越靠前）</td>
            <td><input class="input-md form-control" name="sort" value="100"/></td>
        </tr>
        <tr>
            <td colspan="2">
              <div style="width:40%;margin:0 auto;text-align:center;">
                <input class="btn btn-info submit" style="width: 60px;" type="submit"  name="submit" value="<?php if (ACTION == "addGroup"): ?>提交<?php else: ?>更新<?php endif; ?>" />
                <input class="btn btn-info submit" style="width: 60px;" type="button"  onclick="javascript:history.go(-1);" value="返回"/>
                <input type="hidden" name="cg_id" value="" />
              </div>
            </td>
        </tr>
    </table>
  </form>
</div>

<?php $this->import("foot"); ?>
