<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
    <title><?php echo ADMIN_BACKEND_NAME;?></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/bootstrap/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/public.css">
    <script language="javascript" type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/jquery.js"></script>
    <script language="javascript" type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/jquery.md5.js"></script>
    <style>
    .inputText {
            width:150px;
    }
table {
	border:0px solid #000;
	padding: 0px;
	border-spacing: 0px;
	border-collapse: collapse;
	margin:20px 0px 0px 0px;
}
td {
	border:0px solid #000;
	padding: 1px;
    font: 12px "sans-serif","Arial","Verdana";
}
.login_bg{
    width:100%
    margin:0 auto;
    height:900px;
    background: url(images/user_bg.jpg) no-repeat center center;
    position: relative;

}
.form_list{
    margin:0;
    width:370px;
    height: 300px;
    border:1px solid rgba(0,0,0,0);
    position: absolute;
    top:33%;
    left:59%;

}
    </style>
<script>
function chksubmit(f) {
    if (f.username.value == '') {
        alert('請輸入用戶名');
        return false;
    }
    if (f.password.value == '') {
        alert('請輸入密碼');
        return false;
    }
    if (f.verifyCode.value == '') {
        alert('請輸入驗証字');
        return false;
    }
    var pwd = $('input[name=password]').val();
    $('input[name=password]').val($.md5(pwd));
    return true;
}
</script>
</head>
<body>
    <div class="login_bg" >
    <form class="form_list  form-inline" role="form" action="?a=login" method="post" onsubmit="return chksubmit(this);">
            <div class="form-group has-success has-feedback" >
                 <label>用户名：</label>
                 <input class="form-control inputText mb20" type="text" value="" name="username"/>
                 <span class="glyphicon glyphicon-user form-control-feedback">
            </div>

            <div class="form-group has-success has-feedback">
                <label>密　碼：</label>
                <input class="form-control inputText mb20" type="password" name="password"/>
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="form-group has-success has-feedback">
                <label>验证码：</label>
                <input class="form-control " type="text" size="4" maxlength="4" id="verifyCode" name="verifyCode"/>
                <img align="absmiddle" src="?c=default&a=verifyCode" width="70" height="20" border="1" title="点击更换验证码" style="cursor: pointer; border-color: rgb(255, 255, 255);"
                             onclick="this.src='?a=verifyCode&'+Math.random()">
            </div>
            <br>
            <div class="form-group has-success has-feedback mt20 ml90">
                <input type="hidden" name="verify" value="login">
                <input class="btn btn-info button" type="submit"  value="用户登入" />
            </div>
    <!--<table>
        <tbody><tr>
                <td>用戶名</td>
                <td><input class="inputText" type="text" value="" name="username"></td>
            </tr>
            <tr>
                <td>密　碼</td>
                <td><input class="inputText" type="password" name="password" style="margin-right: 4px;"></td>
            </tr>
            <tr>
                <td>验证码</td>
                <td height="auto" style="text-valign:bottom"><input type="text" size="4" maxlength="4" id="verifyCode" name="verifyCode">
                    <img align="absmiddle" src="?c=default&a=verifyCode" width="70" height="20" border="1" title="点击更换验证码" style="cursor: pointer; border-color: rgb(255, 255, 255);"
                         onclick="this.src='?a=verifyCode&'+Math.random()">
                </td>
            </tr>
            <tr><td align="center" colspan="2"><input type="hidden" name="verify" value="login">
                    <input type="submit" class="button" value="用戶登入"></td></tr>
        </tbody></table>
        -->
    </form>
</div>
</body>
</html>