
<?php $this->import("head"); ?>
 
<div class="list-div container" id="addDiv">
		<table class="table table-responsive table-striped"> 
			<tr>
    	       <td align="center" height="25"><strong>欢迎使用管理系统！</strong></td>
            </tr>
            <tr>
    	       <td style="height: 45px;line-height: 45px;">祝您使用愉快。</td>
            </tr>
		</table>
<!--<table cellpadding="0" cellspacing="0" width="100%" border="0" bordercolordark="#FFFFFF" bordercolorlight="#FF0000" align="center">
    <tr>
    	<td align="center" height="25"><strong>欢迎使用管理系统！</strong></td>
    </tr>
    <tr>
    	<td align="left" height="40">
            祝您使用愉快。
        </td>
    </tr>
</table>-->
</div>
<br/><br/><br/><br/><br/><br/><br/><br/>
<?php $this->import("foot"); ?>