<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?php echo ADMIN_BACKEND_NAME; ?></title>
        <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/bootstrap/css/bootstrap.css">
        <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/public.css">
        <style>
            body {
                padding:0px;
                margin:0px;
                color:#fff;
                background:#383838;
                font-size:12px;
                font-family:"Courier New";
                border:0px solid #f00;
                overflow:hidden;
            }
            .search_btn{
                height:22px;
                line-height:11px;

            }
            table {
                border-collapse: collapse;
            }

            a:link,a:visited {
                text-decoration:underline;
                color:#fff;
            }
            #title{ letter-spacing:0px; height:70px; line-height: 50px;}
            #title a { text-decoration:none;font-size:20px; font-family:"";color:000; font-weight:700; letter-spacing:0px;}
        </style>
        <script src="js/jquery.js" type="text/javascript"></script>
        <script src="js/common.js"></script>
        <script src="js/jqueryUI/dialog/js/jquery.dialog.js" type="text/javascript"></script>
        <script type="text/javascript">
            function openSearch(v) {
                // window.open('/?c=user&a=viewUser&user_id=' + this.value, '_blank', 'height=1200, width=800,scrollbars=0,location=0,menubar=0,resizable=0,status=0');
                var msg = ('<iframe width="820px" scrolling="yes"  style="overflow: scroll;" height="500px" frameborder="0" src="/?c=user&a=viewUser&user_id=' + v + '"> </iframe>');

                   $('<div title="提示">' + msg + '</div>').dialog({
                    bgiframe: true,
                    width: 830,
                    height: 520,
                    top:1,
                    buttons: {
                        "确定": function() {
                            $(this).dialog("close", window.parent);       //关闭这个对话框
                        }
                    }
                }, window.parent);
            }

            $(function() {
                $('#userInput').keyup(function(evt) {
                    if (evt.keyCode == 13) {
                        openSearch($(this).val());
                    }
                });

                $('#userSearch').click(function(evt) {
                        openSearch($('#userInput').val());
                });

            });
        </script>
    </head>
    <body>
        <table class="table table-responsive" style="padding:0px!important;border-bottom: 0px;">
            <tr>
                <td style="width:30%;line-height: 66px;"><span id="title"><a href="./?c=default" target="_top"><?php echo ADMIN_BACKEND_NAME; ?></a> </span> &nbsp;
                    <?php if (RUN_ENV == 1): ?><font style="font-size:20px; font-family:''; font-weight:normal;">[本地环境]</font>
                    <?php elseif (RUN_ENV == 2): ?><font style="font-size:20px; font-family:''; font-weight:normal;">[测试环境]</font>
                    <?php endif; ?>
                </td>

                <td width="250" style="text-align:right">
                    欢迎 <?php echo $admin_name; ?>，<a href="./?a=logout">退出系统</a>
                    <br/><span>上次登录：<?php echo $admin_last_time; ?></span>
                    <br/><span><?php echo ip::loc($admin_last_ip); ?></span>
                </td>
            </tr>
        </table>
    </body>
</html>
