<?php $this->import("head"); ?>
<script src="<?php echo $imgCdnUrl ?>/js/jedate/jedate.js"></script>
<script>
$(function(){
//    //准备数据
//    var json_topUsers = '<?php //echo json_encode($orders['topUsers']); ?>//';
//        json_topUsers = JSON.parse(json_topUsers);
//    var tmp = '';
//
//    //总代选择框
//    $.each(json_topUsers, function(i,v){
//        tmp = '<option value=' + v.top_id + '>' + v.userName + '</option>';
//        $('select[name=top_id]').append(tmp);
//    });


////>>所属总代与用户二选一点击事件
//    $('input[name=name_style]').click(function(){
//        if ($(this).val() == 1) {
//            $('select[name=top_id]').attr('disabled', false);
//            $('input[name=username]').attr('disabled', true);
//        }
//        else {
//            $('select[name=top_id]').attr('disabled', true);
//            $('input[name=username]').attr('disabled', false).focus();
//        }
//    });
//


    //设置默认值
    //$('select[name=type]').val('<?=$type?>').change();
    $('input[name=transfer_id]').val('<?php echo !empty($options['transfer_id']) ? $options['transfer_id'] : ''; ?>');
    $('#start_time').val('<?=$options['startDate']?>');
    $('#end_time').val('<?=$options['endDate']?>');
    $('select[name=top_id]').val('<?=$top_id?>');
    $('select[name=action]').val('<?=$options['action']?>');
    $('select[name=status]').val('<?=$options['status']?>');
    $('select[name=platform]').val('<?=$options['platform']?>');
    $('input[name=status]').val('<?=$options['endDate']?>');
    $('input[name=include_childs]').attr('checked', <?php if ($options['include_childs'] == 1): ?>true<?php else: ?>false<?php endif; ?>);
    $('input[name=start_amount]').val('<?php echo ($options['amount_start'] > 0) ?  $options['amount_start'] : 0; ?>');
    $('input[name=end_amount]').val('<?php echo ($options['amount_end'] > 0) ?  $options['amount_end'] : 0; ?>');
//    if ($('input[name=username]').val() == '') {
//        $('input[name=name_style][value=1]').attr('checked', true).click();
//    }
//    else {
//        $('input[name=name_style][value=2]').attr('checked', true).click();
//    }
    $('#form1').find('input[name=submit]').click(function(){
        //>>提交之前进行数据有效性验证
        var transfer_id = $('input[name=transfer_id]').val();
        //>>只能是数字
        if(transfer_id != ''){
            var reg = /^\d{1,12}$/;
           if( !reg.test(transfer_id)){
               alert('订单编号格式不正确');
               return false;
           }
        }

        //>>验证时间格式


        var reg = /^((((1[6-9]|[2-9]\d)\d{2})-(0?[13578]|1[02])-(0?[1-9]|[12]\d|3[01]))|(((1[6-9]|[2-9]\d)\d{2})-(0?[13456789]|1[012])-(0?[1-9]|[12]\d|30))|(((1[6-9]|[2-9]\d)\d{2})-0?2-(0?[1-9]|1\d|2[0-8]))|(((1[6-9]|[2-9]\d)(0[48]|[2468][048]|[13579][26])|((16|[2468][048]|[3579][26])00))-0?2-29-)) (20|21|22|23|[0-1]?\d):[0-5]?\d:[0-5]?\d$/;
        var start_time = $('#start_time').val();
        var end_time   = $('#end_time').val();
        if(!reg.test(start_time) || !reg.test(end_time)){
            //>>时间格式不正确
            alert('时间格式不正确');
            return false;
        }

        //>>如果输入了用户名

    });


    //>>做数据验证
    $('input[name=transfer_id]').keyup(function(){
        //>>获取数据
        var transfer_id = $('input[name=transfer_id]').val();

        if(transfer_id.length >12){
            $('input[name=transfer_id]').val(parseInt(transfer_id.substring(0,12)));
            alert('最多只能输入12位数字');
        }else{
            if(transfer_id != ''){
                var reg = /^\d{1,12}$/;
                if( !reg.test(transfer_id)){
                    alert('只能输入数字');
                    $('input[name=transfer_id]').val(parseInt(0));
                    return false;
                }
            }
        }



    });

    $('input[name=username]').live('focusout',function(){
        var reg = /^[u4E00-u9FA5]+$/;
        var user_name = $('input[name=username]').val();
        if(user_name.length > 50){
            alert('用户名长度超过了最大限制');
            $('input[name=username]').val('');
            return false;
        }

    });
});
</script>
<!------------------ author snow引入搜索相关文件--------------------------->

<link rel="stylesheet" href="/js/jquery-select/bootstrop-select.css">
<script src="/js/jquery-select/bootstrop.min.js"></script>
<script src="/js/jquery-select/bootstrop-select.js"></script>
<!------------------ author snow引入搜索相关文件--------------------------->
<form name="form1" class="form-top" id="form1" action="" method="GET">
    <div class="form-inline mt15">
        <div class="form-group has-default has-feedback">
            <input type="hidden" name="c" value="egame"/>
            <input type="hidden" name="a" value="<?php echo ACTION; ?>"/>
            <label>订单编号</label>
            <input class="input-md form-control tl" style="width: 104px;" name="transfer_id" size="20"/>
            <label>游戏时间</label>
            <input class="input-md form-control" type="text" name="start_time" id="start_time"  onclick="jeDate({dateCell:'#start_time',isTime:true,format:'YYYY-MM-DD hh:mm:ss'})"  />
            <span class="glyphicon glyphicon-calendar form-control-feedback"></span>
        </div>
        <div class="form-group has-default has-feedback">
            <label>到</label>
            <input class="input-md form-control Wdate" type="text" name="end_time" id="end_time"  onclick="jeDate({dateCell:'#end_time',isTime:true,format:'YYYY-MM-DD hh:mm:ss'})" />
            <span class="glyphicon glyphicon-calendar form-control-feedback"></span>
        </div>
        <label>帐变类型: </label>
        <select class="input-md form-control" name="action">
            <option value="0">请选择</option>
            <?php foreach ($orders['egameAction'] as $k => $v): ?>
                <option value="<?=$v?>"><?=$actionName[$v]?></option>
            <?php endforeach; ?>
        </select>
        <label>状态:</label>
        <select class="input-md form-control" name="status">
            <option value="0">请选择</option>

            <?php foreach ($orders['status'] as $k => $v): ?>
                <option value="<?=$k?>"><?=$v?></option>
            <?php endforeach; ?>
        </select>

    </div>
<div id='tradeTypesTable' style='border:0px;margin:5px 0px 10px 0px;display:none;'>
	<?php foreach ($orderTypes as $k => $v): ?>
    <div style='border:0px;float:left;width:120px;text-align:left;'>
    	<input class='tradeTypes' id='tradeTypes_<?=$k?>' type='checkbox' name='type[<?=$k?>]' value='<?=$k?>' <?php if (isset($types[$k])): ?>checked<?php endif; ?> />
    	<label for='tradeTypes_<?=$k?>'><?=$v?></label>
    </div>
    <?php endforeach; ?>
    <div style="clear:both;"></div>
</div>
    <div class="form-inline mt15 mb15">
        <label>平台：</label>
        <select class="input-md form-control" name="platform">
            <option value="">请选择</option>
            <?php foreach ($orders['platform'] as $k => $v): ?>
                <option value="<?=$k?>"><?=$v?></option>
            <?php endforeach; ?>
        </select>
        <input type="radio" name="name_style" id="radio1" value="1"/>
        <label for="radio1">所属总代:</label>
        <select id="top_id" class="selectpicker snow-topUser-search" name="top_id" data-live-search="true" title="请选择 ...">
            <option value="">请选择…</option>
            <?php foreach ($orders['topUsers'] as $k => $v): ?>
                <option value="<?=$v['top_id']?>"><?=$v['userName']?></option>
            <?php endforeach; ?>
        </select>

<!--        <input type="radio" name="name_style" id="radio1" value="1"/>-->
<!--        <label  for="radio1">所属总代</label>-->
<!--        <select class="input-md form-control" name="top_id">-->
<!--            <option value="">请选择</option>-->
<!--        </select>-->
        <label>或</label>
        <input type="radio" name="name_style" value="2" id="radio2"/>
        <label style="font-weight: normal;" for="radio2">用户名</label>
        <input class="input-md form-control" name="username" size="10"/>
        <input type="checkbox" name="include_childs" id="include_childs" value="1" /><label for="include_childs">包含下级</label> &nbsp;
        <label>帐变金额</label>
        <input class="input-md form-control"  name="start_amount" size="10"/>
        <label>到</label>
        <input class="input-md form-control"  name="end_amount" size="10"/>
        <input class="btn btn-info submit" style="width: 60px;" type="submit" name="submit"  value="查询"/>
</form>
    </div>

<h4>
<!--    <input class="btn btn-info excel"  type="button" table=".mainList" excelFile="用户日投注"  value="导出Excel"/>-->
</h4>

    <div class="list-div mt20" id="listDiv">
        <table class="table table-responsive  table-bordered mainList" width="80%">
            <thead>
                <tr>
                    <td>订单 ID</td>
                    <td>用户 ID</td>
                    <td>用户名</td>
                    <td>总代</td>
                    <td>转帐金额</td>
                    <td>本地订单号</td>
                    <td>账变类型</td>
                    <td>平台</td>
                    <td>平台订单号</td>
                    <td>转帐前余额</td>
                    <td>转帐后余额</td>
                    <td>状态</td>
                    <td>备注</td>
                    <td>转帐时间</td>
                </tr>
            </thead>
            <?php if ($isCanSearch): ?>
            <?php foreach ($orders['pageResult'] as $v): ?>
                <tr>
    	           <td><?=$v['transfer_id']?></td>
    	           <td><?=$v['user_id']?></td>
                    <td>
                        <a href="?c=egame&a=translateList&user_id=<?=$v['user_id']?>&username=<?=$v['username']?>"><?=$v['username']?></a>
                    <td><?=$v['top_id']?></td>
                    <td class="snow-amount"><?=$v['amount']?></td>
                    <td><?=$v['element_id']?></td>
                    <td><?=$actionName[$v['action']]?></td>
                    <td><?=$orders['platform'][$v['platform']]?></td>
                    <td><?=$v['paymentid']?></td>
                    <td><?=$v['pre_balance']?></td>
                    <td><?=$v['balance']?></td>
                    <td><?=$orders['status'][$v['status']]?></td>
                    <td><?=$v['remark']?></td>
                    <td><?=$v['create_time']?></td>
    </tr>
    <?php endforeach; ?>
    <?php else: ?>
    <tr>
        <td colspan="13" class="no-records">至少指定帐变类型或用户名后才能查询！</td>
    </tr>
    <?php endif; ?>
</table>
</div>
<div class="pageTal"><?=$pageList?><div class="smallTal">本页小计:<b></b>元，总计:<b><?=$orders['totalAmount']?></b>元 &nbsp; </div></div>

<?php $this->import("foot"); ?>
<script >
    $(function(){
        //>>计算本页小计
        var snow_amouts = $('.snow-amount');
        var smallTal = 0;
        snow_amouts.each(function(key,val){
            smallTal += parseFloat($(val).text())
        });

        $('.smallTal').find('b').text(smallTal);
    })
</script>
