<?php $this->import("head"); ?>
<style type="text/css">
    .liveInt tr{height: 30px;line-height:30px;}
    .jedatehms{display: none!important;}
</style>
<script src="js/jedate/jedate.js"></script>
<script>
    $(function(){
        $('input[name=username]').val('<?php echo $username; ?>');
        $('input[name=amount]').val('<?php echo $amount; ?>');
        $('input[name=startDate]').val('<?php echo $startDate; ?>');
        $('input[name=endDate]').val('<?php echo $endDate; ?>');
    });
</script>
<div class="list-div" id="addDiv">
<form name="form1" id="form1" class="form-top" action="./?c=liveInt&a=<?php echo ACTION; ?>" method="POST">
    <h3>波音接口管理</h3>
    <hr>
<p class="boyin_port">当前会话信息：<?php echo $config['cfg_value']; ?><br/> 更新时间：<?php echo $config['ts']; ?> </p>
<div class="form-inline mb15 mt15">
    <input class="btn btn-mini btn-info" type="button" class="submit" name="btn1" value="保存新会话" onclick="this.form.sa.value='saveSessInfo';this.form.submit();"/> &nbsp;
    <input class="btn btn-mini btn-info" type="button" class="submit" name="btn1" value="显示额度" onclick="this.form.sa.value='showCBalance';this.form.submit();"/> &nbsp;
        <div class="form-group has-default has-feedback">
        <label>时间:</label>
        <input class="form-control" type="text" size="21" name="startDate" id="startDate" onclick="jeDate({dateCell:'#startDate',isTime:true,format:'YYYY-MM-DD'})" />
        <span class="glyphicon glyphicon-calendar form-control-feedback"></span>
    </div>
    <div class="form-group has-default has-feedback">
        <label>到</label>
        <input class="form-control " type="text" size="21" name="endDate" id="endDate" onclick="jeDate({dateCell:'#endDate',isTime:true,format:'YYYY-MM-DD'})" />
        <span class="glyphicon glyphicon-calendar form-control-feedback"></span>
    </div>
    <input class="btn btn-mini btn-info" type="button" class="submit" name="btn1" value="显示各代理输赢" onclick="this.form.sa.value='getAgentGainLoss';this.form.submit();"/> &nbsp;
<input type="hidden" name="sa" value=""/>

</div>
<!--<input type="button" class="submit" name="btn1" value="保存新会话" onclick="this.form.sa.value='saveSessInfo';this.form.submit();"/> &nbsp;
<input type="button" class="submit" name="btn1" value="显示额度" onclick="this.form.sa.value='showCBalance';this.form.submit();"/> &nbsp;
<input size="15" name="startDate" id="startDate" my97mark="false" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd'})" class="Wdate"/>
<input size="15" name="endDate" id="endDate" my97mark="false" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd'})" class="Wdate"/>
<input type="button" class="submit" name="btn1" value="显示各代理输赢" onclick="this.form.sa.value='getAgentGainLoss';this.form.submit();"/> &nbsp;
<input type="hidden" name="sa" value=""/>-->
</form>


<h3>测试结果</h3>
<hr>
<pre><?php print_r($result); ?></pre>

<h3>附：错误对照表</h3>
<hr>
<div class="mainList_table">
    <table class="table-responsive table-hover mainList liveInt">
        <tr><td class="di ml10">代码</td><td>信息参考</td></tr>
        <tr><td class="di ml10">-101</td><td>代理自己额度不够转给用户</td></tr>
        <tr><td class="di ml10">-102</td><td>用户自己额度不够转出</td></tr>
        <tr><td class="di ml10">-127</td><td>可能内容改版</td></tr>
        <tr><td class="di ml10">-128</td><td>可能内容改版</td></tr>
        <tr><td class="di ml10">-399</td><td>波音帐户尚未激活</td></tr>
        <tr><td class="di ml10">-400</td><td>后台未设置好代理帐户</td></tr>
        <tr><td class="di ml10">-401</td><td>后台未设置好代理会话</td></tr>
        <tr><td class="di ml10">-404</td><td>会话已到期，需要重新登录</td></tr>
    </table>
</div>
</div>

<?php $this->import("foot"); ?>