<?php $this->import("head"); ?>
<style type="text/css">
    .jedatehms{display:none !important;}
</style>
<script src="<?php echo $imgCdnUrl ?>/js/jedate/jedate.js"></script>
<script>
$(document).ready(function(){
    $("input[name=startDate]").val("<?php echo $startDate; ?>");
    $("input[name=endDate]").val("<?php echo $endDate; ?>");
    $("input[name=show1]").attr('checked', <?php if ($show1 == 1): ?>true<?php else: ?>false<?php endif; ?>);
    $("input[name=show2]").attr('checked', <?php if ($show2 == 1): ?>true<?php else: ?>false<?php endif; ?>);

});
</script>
<div class="list-div mt20" id="addDiv">
    <form name="form1" class="form-top" id="form1" action="" method="get" onsubmit="return checkform(this)">
        <div class="form-inline">
            <input type="hidden" name="c" value="market"/>
            <input type="hidden" name="a" value="saleChart"/>
            <div class="form-group has-default has-feedback">
                <label>开始时间:</label>
                <input class="input-md form-control Wdate" type="text" name="startDate" id="startDate" onclick="jeDate({dateCell:'#startDate',isTime:true,format:'YYYY-MM-DD'})" />
                <span class="glyphicon glyphicon-calendar form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback has-default">
                <label class="ml10">结束时间:</label>
                <input class="input-md form-control  Wdate" type="text" name="endDate" id="endDate" onclick="jeDate({dateCell:'#endDate',isTime:true,format:'YYYY-MM-DD'})" />
                <span class="glyphicon glyphicon-calendar form-control-feedback"></span>
            </div>
            <label  for='show1' style='color:#00FF00;font-weight: normal;'><input class="ml10" type="checkbox" id="show1" name="show1" value="1"/>投注量</label>&nbsp;&nbsp;
            <label for='show2' style='color:#00FFCC;font-weight: normal;'><input class="ml10" type="checkbox" id="show2" name="show2" value="1"/>人均销量</label>&nbsp;&nbsp;
            <input class="btn btn-info button ml10" type="submit" value="查看"  style="width:60px" />
        </div>
    </form>
<div class="mt15 mb15">
   <b> 系统销量图表</b>
</div>
<table class="table table-responsive table-bordered" cellpadding="0" cellspacing="0">
    <tr>
        <td>
            <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" width="100%" height="280" id="chart" >
                <param name="movie" value="js/chart.swf?" />
                <param name="FlashVars" value='&dataURL=?c=market%26a=saleChart%26op=getXML%26startDate=<?php echo $startDate; ?>%26endDate=<?php echo $endDate; ?>%26show1=<?php echo $show1; ?>%26show2=<?php echo $show2; ?>'>
                <param name="quality" value="high" />
                <embed src="js/chart.swf?" flashVars='&dataURL=?c=market%26a=saleChart%26op=getXML%26startDate=<?php echo $startDate; ?>%26endDate=<?php echo $endDate; ?>%26show1=<?php echo $show1; ?>%26show2=<?php echo $show2; ?>' quality="high" width="100%" height="280" name="chart" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />
            </object>
        </td>
    </tr>
</table>
    </form>
</div>

<?php $this->import("foot"); ?>