<?php $this->import("head"); ?>
<script src="<?php echo $imgCdnUrl ?>/js/jedate/jedate.js"></script>
<script>
    $(function() {
        $('input[name=from_time]').val('<?php echo $from_time; ?>');
        $('input[name=to_time]').val('<?php echo $to_time; ?>');
        $('select[name=title]').val('<?php echo $title; ?>');
        $('select[name=status]').val('<?php echo $status; ?>');
        $('select[name=type]').val('<?php echo $type; ?>');
        $('input[name=username]').val('<?php echo $username; ?>');
    });
</script>
<div id="query">
    <form name="form1" class="form-top" id="form1" action="./" method="get">
        <div class="form-inline mt15">
            <div class="form-group has-default has-feedback">
                <label>起始时间</label>
                <input class="input-md form-control tl" type="text" name="from_time" id="from_time"  value="<?php echo date('Y-m-d H:i:s'); ?>" onclick="jeDate({dateCell:'#from_time',isTime:true,format:'YYYY-MM-DD hh:mm:ss'})"/>
                <span class="glyphicon glyphicon-calendar form-control-feedback"></span>
            </div>  
            <div class="form-group has-default has-feedback">
                <label>结束时间</label>
                <input class="input-md form-control tl" type="text" name="to_time" id="to_time" value="" onclick="jeDate({dateCell:'#to_time',isTime:true,format:'YYYY-MM-DD hh:mm:ss'})"/>
                <span class="glyphicon glyphicon-calendar form-control-feedback"></span>
            </div>
            <label>名称</label>
            <select class="input-md  form-control" name="title">
                <option value="">请选择</option>
                <?php foreach ($titles as $v): ?>
                <option value="<?php echo $v['title']; ?>"><?php echo $v['title']; ?></option>
                <?php endforeach; ?>
            </select>
            <label>用户名</label>
            <input class="input-md  form-control" name="username" size="10"/>
            <label>状态</label>
            <select class="input-md  form-control"  name="status">
                <option value="">请选择</option>
                <option value="0">未开始</option>
                <option value="1">正在进行</option>
                <option value="2">未完成任务</option>
                <option value="5">已领取已获礼金</option>
                <option value="3">已完成任务</option>
                <option value="4">已领取成功礼金</option>
                <option value="6">资格审核</option>
                <option value="7">申请成功奖金</option>
                <option value="8">申请已获奖金</option>
                <option value="9">拒绝发放成功奖金</option>
                <option value="10">拒绝发放已获奖金</option>
            </select>
            <label>类型</label>
            <select class="input-md  form-control" name="type">
                <option value="">请选择</option>
                <option value="0">完成任务发放</option>
                <option value="1">限制提款</option>
            </select>
            <input class="btn btn-info " style="width: 60px;" type="submit" name="submit" value="查 询"/>
            <input type="hidden" name="c" value="market"/>
            <input type="hidden" name="a" value="userGifts"/>
        </div>
    </form>
    <div class="mt10 mb10"><input class="btn btn-info excel" type="button" table=".mainList" excelFile="礼品卷报表"  value="导出Excel"/></div>  
</div>
<div class="list-div mt10" id="listDiv">
    <table class="table table-responsive   table-bordered mainList">
        <thead>
            <tr>
                <td>ug_id</td>
                <td>类型</td>
                <td>名称</td>
                <td>用户名</td>
                <td>父用户</td>
                <td>起始时间</td>
                <td>结束时间</td>
                <td>最大礼金</td>
                <td>已获实际礼金</td>
                <td>每日流水要求</td>
                <td>总流水要求</td>
                <td>团队流水</td>
                <td>状态</td>
                <td>申请IP</td>
                <td>备注</td>
                <td>操作</td>
            </tr>
        </thead>
        <?php foreach ($userGifts as $v): ?>
            <tr data-ug_id="<?php echo $v['ug_id']; ?>">
                <td><?php echo $v['ug_id']; ?></td>
                <td>
                    <?php if ($v['type'] == 0): ?>完成任务发放
                    <?php elseif ($v['type'] == 1): ?>限制提款
                    <?php endif; ?>
                </td>
                <td><?php echo $v['title']; ?></td>
                <td><?php echo $v['username']; ?></td>
                <td><?php echo $v['parentusername']; ?></td>
                <td><?php echo $v['from_time']; ?></td>
                <td><?php echo $v['to_time']; ?></td>
                <td id="gift_<?php echo $v['ug_id']; ?>"><?php echo $v['gift']; ?></td>
                <td><?php echo $v['failed_gift']; ?></td>
                <td><?php echo ($v['min_day_water'] == 0 ? '无' : $v['min_day_water']); ?></td>
                <td><?php echo ($v['min_total_water'] == 0 ? '无' : $v['min_total_water']); ?></td>
                <td><?php echo ($v['is_include_child'] == 0 ? '否' : '是'); ?></td>
                <td id="status_<?php echo $v['ug_id']; ?>">
                    <?php if ($v['status'] == 0 || strtotime($v['from_time']) > time()): ?><b><font color="red">未开始</font></b>
                    <?php elseif ($v['status'] == 1): ?><b><font color="red">正在进行</font></b>
                    <?php elseif ($v['status'] == 2): ?><b><font color="red">未完成任务</font></b>
                    <?php elseif ($v['status'] == 3): ?>已完成任务
                    <?php elseif ($v['status'] == 4): ?>已领取成功礼金
                    <?php elseif ($v['status'] == 5): ?>已领取已获礼金
                    <?php elseif ($v['status'] == 6): ?>资格审核
                    <?php elseif ($v['status'] == 7): ?>申请成功奖金
                    <?php elseif ($v['status'] == 8): ?>申请已获奖金
                    <?php elseif ($v['status'] == 9): ?>拒绝发放成功奖金
                    <?php elseif ($v['status'] == 10): ?>拒绝发放已获奖金
                    <?php endif; ?>
                </td>
                <td><?php echo ip::loc($v['apply_ip']); ?></td>
                <td><?php echo $v['remark']; ?></td>
                <!--<td><?php echo ($v['verify_admin_id'] == 0 ? '无' : $v['remark'] . ' <br/>由：' . $v['verify_admin_id']); ?></td>-->
                <td id="action_<?php echo $v['ug_id']; ?>">
                    <?php if($v['type'] == 600 && $v['status'] == 3): ?>
                        <a class="btn btn-mini btn-info btn-lol" href="javascript:void(0)">发放</a>&nbsp;
                    <?php endif; ?>
                    <?php if (($v['status'] == 7 || $v['status'] == 8) && $canVerify): ?>
                        <a class="btn btn-mini btn-info" target="_blank" href="?c=market&a=sendUserGifts&ug_id=<?php echo $v['ug_id']; ?>" onclick="return confirm('真的要发放礼金券吗？');">发放</a>&nbsp;
                        <a class="btn btn-mini btn-info" target="_blank" href="?c=market&a=sendUserGifts&op=not&ug_id=<?php echo $v['ug_id']; ?>" onclick="return confirm('真的要拒绝吗？');">拒绝</a>&nbsp;
                    <?php endif; ?>
                    <?php if ($v['status'] == 6 && $canVerify): ?>
                        <a class="btn btn-mini btn-info" target="_blank" href="?c=market&a=sendUserGifts&op=verify&ug_id=<?php echo $v['ug_id']; ?>" onclick="return confirm('通过资格审核？通过资格审核将会设置状态为进行中');">通过</a>&nbsp;
                    <?php endif; ?>
                    <?php if ($v['status'] != 4 && $v['status'] != 5 && $canDelete): ?><a class="btn btn-mini btn-info" target="_blank" href="?c=market&a=deleteUserGifts&ug_id=<?php echo $v['ug_id']; ?>" onclick="return confirm('真的要删除吗？该操作不可恢复！');">删除</a>&nbsp;<?php endif; ?>
                </td>
            <?php endforeach; ?>
    </table>
</div>
<div class="pageTal"><?php echo $pageList; ?></div>

<?php $this->import("foot"); ?>
<style>
    .layui-layer-content{color: #333;}
    .layui-layer-title{background: #333;}
    .layui-layer-btn0{background: #333!important;border-color: #333!important;}
</style>
<script src="<?php echo $imgCdnUrl ?>/js/layer-v2.4/layer.js"></script>
<script>
    $(function(){
        $('.btn-lol').click(function(){
            let $this = $(this);
            let $tr = $this.parents('tr')[0];
            $tr = $($tr);
            let $ug_id = $tr.attr('data-ug_id');

            layer.prompt({title: '输入皮肤价值：', formType: 3}, function($cost, index){
                layer.close(index);
                if($cost >= 0){
                    $cost = parseInt($cost);
                    $.post('?c=market&a=sendLolSkin',{'ug_id':$ug_id,'gift':$cost},function($data){
                        if($data.errCode > 0){
                            alert($data.errMsg);
                            return false;
                        }

                        $('#gift_'+$ug_id).text($cost);
                        $('#status_'+$ug_id).text('已领取成功礼金');
                        $('#action_'+$ug_id).html('');

                    },'JSON');
                }else{
                    layer.msg('请输入正确的数据!');
                }

            });
        });
    });
</script>
