<?php $this->import("head"); ?>
<style type="text/css">
.jedatehms{display:none !important;}
</style>
<script src="<?php echo $imgCdnUrl ?>/js/jedate/jedate.js"></script>
<script>
$(document).ready(function(){

    $("input[name=startDate]").val("<?php echo $startDate; ?>");
    $("input[name=endDate]").val("<?php echo $endDate; ?>");
    $("input[name=show1]").attr('checked', <?php if ($show1 == 1): ?>true<?php else: ?>false<?php endif; ?>);
    $("input[name=show2]").attr('checked', <?php if ($show2 == 1): ?>true<?php else: ?>false<?php endif; ?>);
//    $("input[name=show3]").attr('checked', <?php if ($show3 == 1): ?>true<?php else: ?>false<?php endif; ?>);
//    $("input[name=show4]").attr('checked', <?php if ($show4 == 1): ?>true<?php else: ?>false<?php endif; ?>);
    $('select[name=top_id]').val('<?php echo $top_id; ?>');
});
</script>
    <!------------------ author snow引入搜索相关文件--------------------------->

    <link rel="stylesheet" href="/js/jquery-select/bootstrop-select.css">

    <script src="/js/jquery-select/bootstrop.min.js"></script>
    <script src="/js/jquery-select/bootstrop-select.js"></script>
    <!------------------ author snow引入搜索相关文件--------------------------->
<div class="list-div mt20" id="addDiv">
    <form name="form1" class="form-top" id="form1" action="" method="get">
        <div class="form-inline">
            <div class="form-group has-default has-feedback">
                <label class="ml10">开始时间:</label>
                <input class="input-md form-control tl" type="text" name="startDate" id="startDate"  onclick="jeDate({dateCell:'#startDate',isTime:true,format:'YYYY-MM-DD'})" />
                <span class="glyphicon glyphicon-calendar form-control-feedback"></span>
            </div>
            <div class="form-group has-default has-feedback">
                <label>到</label>
                <input class="input-md form-control tl" type="text" name="endDate" id="endDate"  onclick="jeDate({dateCell:'#endDate',isTime:true,format:'YYYY-MM-DD'})"/>
                <span class="glyphicon glyphicon-calendar form-control-feedback"></span>
            </div>
            <label>所属总代:</label>
            <select id="top-username" class="selectpicker snow-topUser-search" name="top_id" data-live-search="true" title="请选择 ...">
                <option value="-1">请选择…</option>
                <?php foreach ($json_topUsers as $k => $v): ?>
                    <option value="<?=$v['user_id']?>"><?=$v['username']?></option>
                <?php endforeach; ?>
            </select>
            <input type="hidden" name="c" value="market"/>
            <input type="hidden" name="a" value="amountChart"/>
            <label class="ml10"  for='show1' style='color:#0033CC;'><input type="checkbox" id="show1" name="show1" value="1"/>存款量</label>&nbsp;&nbsp;
            <label class="ml10"  for='show2' style='color:#FF0000;'><input type="checkbox" id="show2" name="show2" value="1"/>提款量</label>&nbsp;&nbsp;
            <input class="btn btn-info button ml10" type="submit" value="查看"  style="width:60px" />
        </div>
    </form>
<div class="mt15">
    <?php if($user['username']) :?>总代<?php echo $user['username'];?>团队数据
    <?php else: ?>
    <b>系统财务图表</b>
    <?php endif;?>
</div>
<table class="table table-responsive table-bordered " cellpadding="0" cellspacing="0">
    <tr>
        <td>
            <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" width="100%" height="280" id="chart" >
                <param name="movie" value="js/chart.swf?" />
                <param name="FlashVars" value='&dataURL=?c=market%26a=amountChart%26op=getXML%26startDate=<?php echo $startDate; ?>%26endDate=<?php echo $endDate; ?>%26show1=<?php echo $show1; ?>%26show2=<?php echo $show2; ?>%26top_id=<?php echo $top_id; ?>'>
                <param name="quality" value="high" />
                <embed src="js/chart.swf?" flashVars='&dataURL=?c=market%26a=amountChart%26op=getXML%26startDate=<?php echo $startDate; ?>%26endDate=<?php echo $endDate; ?>%26show1=<?php echo $show1; ?>%26show2=<?php echo $show2; ?>%26top_id=<?php echo $top_id; ?>' quality="high" width="100%" height="280" name="chart" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />
            </object>
        </td>
    </tr>
</table>
    </form>
</div>

<?php $this->import("foot"); ?>