<?php $this->import("head"); ?>
<style>
#betArea {
    border:1px solid #ededed;
    width:400px;
    height:100px;
    overflow-x:hidden;
    overflow-y:scroll;
    border-radius: 8px;
    -webkit-border-radius:8px;
}
#betArea ul {
    padding:0px;
}
#betArea ul li {
    list-style-type:none;
    margin:0px;
    padding:0px;
}
#betArea span {
    margin:1px 5px 1px 5px;
    text-align:center;
}
</style>
<script src="js/My97DatePicker/WdatePicker.js"></script>
<script>
$(function(){
    //准备数据
    var json_users = <?php echo $json_users; ?>;
    var json_lotterys = <?php echo $json_lotterys; ?>;
    var json_methods = <?php echo $json_methods; ?>;
    var tmp = '';
//        $('select').click(function(){
//            alert(this.innerHTML);
//        });

    //所有用户选择框
    $.each(json_users, function(i,v){
        tmp = '<option value=' + v.user_id + '>' + v.username + '</option>';
        $('select[name=user_id]').append(tmp);
    });
    //彩种选择框
    $.each(json_lotterys, function(i,v){
        tmp = '<option value=' + v.lottery_id + '>' + v.name + '</option>';
        $('select[name=lottery_id]').append(tmp);
    });
    $('select[name=lottery_id]').change(function(){
        $('select[name=method_id]').empty().append('<option value="0">请选择</option>');
        if ($('select[name=lottery_id]').val() == 0) {
            return;
        }
        //以下也可改成动态读取，都差不多
        $.each(json_methods[$('select[name=lottery_id]').val()], function(i,v){
            tmp = '<option value="' + v.mg_name + '" style="color:#00f;">' + v.mg_name + '</option>';//玩法组没有method_id
            $('select[name=method_id]').append(tmp);
            $.each(v.childs, function(ii,vv){
                tmp = '<option value="' + vv.method_id + '">&nbsp;&nbsp;' + vv.cname + '</option>';
                $('select[name=method_id]').append(tmp);
            });
        });

        getIssue();
        getUserRebate();
    });

    $('select[name=user_id]').change(getUserRebate);

    //动态读取彩种奖期
    function getIssue() {
        $.post(
            '?c=game&a=getIssue',
            {'lottery_id':$('select[name=lottery_id]').val(), 'start_time':$('#start_time').val()},
            function(json_data) {
                $('select[name=issue]').empty().append('<option value="">请选择</option>');
                $.each(json_data, function(i,v){
                    tmp = '<option value="' + v.issue + '">' + v.issue + '（' + v.code + '）' +' (' + v.start_sale_time + '~' + v.end_sale_time + ')</option>';
                    $('select[name=issue]').append(tmp);
                });
                //预选中奖期
                $('select[name=issue]').val('<?php echo $issue; ?>');
        }, 'json');
    }

    //动态读取用户奖金组
    function getUserRebate() {
        if ($('select[name=user_id]').val() == 0 || $('select[name=lottery_id]').val() == 0) {
            return false;
        }
        $.post(
            '?c=test&a=testBuy',
            {'user_id':$('select[name=user_id]').val(), 'lottery_id':$('select[name=lottery_id]').val(), 'op':'getUserRebate'},
            function(data) {
                $('#user_rebate').html('可调返点范围0 - ' + data + '</span> 请输入：<input name="curRebate" size="5"/>');
            }, 'text'); //返回内容格式，xml, html, script, json, text, _default。
    }

    //显示追号框
    $('input[name=traceNum]').change(function(){
        var str = '';
        for (var i=0; i<$('input[name=traceNum]').val(); i++) {
            str = str + '倍数<input name="traceDetails[]" class="traceDetails" size="3" value="1" />';
        }
        str = str + '<input type="checkbox" name="stopOnWin" value="1" checked/>中奖后停止';
        $('#traceDetails').html(str);
    });

    //计算单倍注数
    $('input[name=code]').blur(function(){
        $.post(
                '?c=test&a=testBuy',
                {
                    'op':'getSingleNum',
                    'method_id':$('select[name=method_id]').val(),
                    'code':$('input[name=code]').val()
                },
                function(response){
                    if (response.errno == 0) {
                        $('input[name=single_num]').val(response.single_num);
                    }
                    else {
                        $('input[name=single_num]').val('');
                        alert('所输号码无效');
                    }
            }, 'json');
    });

    //设置默认值
    $('select[name=user_id]').val('<?php echo $user_id; ?>');
    $('select[name=lottery_id]').val('<?php echo $lottery_id; ?>').change();
    $('select[name=method_id]').val('<?php echo $method_id; ?>');
    $('select[name=modes]').val('<?php echo $modes; ?>');
    $('input[name=code]').val('<?php echo $code; ?>');
    $('input[name=rebate]').val('<?php echo $rebate; ?>');
});
</script>

<script>
$(function(){
    $('.hand').live('click',function(){
        $(this).parent().remove();
    });
    var count = 0;
    $('input[name=addBtn]').click(function(){
        if ($('select[name=method_id]').val() == 0) {
            alert('请选择玩法');
            return false;
        }
        if ($('input[name=code]').val() == '' || $('input[name=single_num]').val() == '') {
            alert('请完整填写号码和单倍注数');
            return false;
        }
        var single_amount = $('input[name=single_num]').val() * 2 * $('select[name=modes]').val();
        if (single_amount == 0) {
            alert("金额为0，请注意是否选择了投注模式（元角分），还要填写单倍注数");
            return false;
        }
        //<li><span mid="1">1.三星直选</span><span>123</span><span>12 注</span><span>100倍</span><span>￥2400.00</span>
        var str = '<li><span mid="' + $('select[name=method_id]').val() + '">' + (++count) + '.' + $('select[name=method_id] :selected').text().trim() +'</span>' + '<span>' + $('input[name=code]').val() + '</span><span>' + $('input[name=single_num]').val() + '注</span>' + '<span>￥'+ number_format(single_amount, 2, '.', '') + '</span>' + '<span title="删除" class="hand">X</span></li>';
        $('#betArea>ul').append(str);
    });

    $('input[name=submit]').click(function(){
        $('#result').text('');
        var flag = true;
        // 这种做法return false;只是退出匿名函数，对submit()段不起作用:)
        $('select').each(function(i){
            if ($(this).val() == 0) {
                flag = false;
            }
        });
        if (flag == false) {
            alert('所有下拉框均须有值');
            return false;
        }

        //因为数据需要预处理，用$.post提交，代替form提交
        var spans, codes = [], traceDetails = [];
        $('#betArea>ul').children('li').each(function(i){
            spans = $(this).children();
            codes.push({
                'method_id':spans.eq(0).attr('mid'),
                'code':spans.eq(1).text(),
                'single_num':parseInt(spans.eq(2).text()),
                //'multiple':parseInt(spans.eq(3).text()),
                'single_amount':parseFloat(spans.eq(3).text().substr(1))
            });
        });
        $('input.traceDetails').each(function(i){
            traceDetails.push($(this).val());
        });

        $.post(
                '?c=test&a=testBuy',
                {
                    'op':'buy',
                    'lottery_id':$('select[name=lottery_id]').val(),
                    'issue':$('select[name=issue]').val(),
                    'curRebate':$('input[name=curRebate]').val(),
                    'modes':$('select[name=modes]').val(),
                    'user_id':$('select[name=user_id]').val(),
                    'codes':codes,
                    'multiple':$('input[name=multiple]').val(),
                    //'traceNum':$('input[name=traceNum]').val(),
                    'traceDetails':traceDetails,
                    'stopOnWin':$('input[name=stopOnWin]').val()
                },
                function(response){
                    if (response.errno == 0) {
                        $('#result').text('购买成功:)');
                    }
                    else {
                        $('#result').text('购买失败:'+ response.errstr + "(errno=" + response.errno +")").css('color', 'red');
                    }
            }, 'json');
    });
});
</script>
<div class="mt10">
    <b>约束：不同方案的元角分模式必须相同，倍数相同;所选号码的单倍注数须填写正确;追号必须从当前期开始;</b>
</div>
<form name="form1" class="form-top" id="form1" action="?c=test&a=<?php echo ACTION; ?>" method="POST">
    <table class="table table-responsive table-bordered mt10" style="width: 60%;">
        <tr>
            <td>
               <div class="form-inline mt10" >
                    <label>游戏名称</label>
                    <select class="input-md form-control " name="lottery_id"><option value="0">请选择</option></select>
                    <label class="ml10">游戏奖期</label>
                    <select class="input-md form-control " name="issue"><option value="">请选择</option></select>
                    <label class="ml10">投注模式</label>
                    <select class="input-md form-control " name="modes"><option value="0">请选择<option value="1">元</option><option value="0.1">角</option><option value="0.01">分</option></select>
                </div> 
            </td>
        </tr>
        <tr>
            <td>
                <div class="form-inline">
                    <label>所属用户</label>
                    <select class="input-md form-control " name="user_id"><option value="0">请选择</option></select><span id="user_rebate"></span>
                </div>
            </td>
        </tr>
    </table>
    <div class="mt10">
        <b>选择玩法投注，注意相应号码表示格式，以直选为例，"1,2,3"或"12,34,56780"均是正确格式</b>
    </div>
        <table class="table table-responsive table-bordered mt10 " style="width: 60%;">
            <tr>
                <td>
                   <div class="form-inline">
                        <label>游戏玩法</label>
                        <select class="input-md form-control " name="method_id"><option value="0">请选择</option></select>
                        <label class="ml10">号码</label>
                        <input class="input-md form-control " name="code" size="30"/>
                        <label class="ml10">单倍注数</label>
                        <input class="input-md form-control " name="single_num" size="3"/>
                        <input class="btn btn-info submit ml10" type="button" name="addBtn" class="submit" value="添加"/>
                    </div> 
                </td>
            </tr>
            <tr>
                <td>
                    <div id="betArea">
                        <ul>
                        </ul>
                    </div>                   
                </td> 
            </tr>
            <tr>
                <td>
                    <div class="form-inline">
                        <label>追号期数：</label>
                        <input class="input-md form-control " style="width: 30%;" name="traceNum" size="3" value="0" /><span id="traceDetails"></span>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="form-inline">
                        <label>倍数:</label>
                        <input class="input-md form-control submit" style="width: 30%;" name="multiple" size="3" value="1"/>
                        <input class="btn btn-info ml10" type="button" name="submit" value="$.post投注"/>
                    </div>
                </td>
            </tr>
            <tr>
               <td><h4>结果：<span id="result"></span></h4></td> 
            </tr>
        </table>
</form>



<?php $this->import("foot"); ?>