<?php $this->import("head"); ?>
<style>
#betArea {
    border:1px solid #000;
    width:400px;
    height:100px;
    overflow-x:hidden;
    overflow-y:scroll;
}
#betArea ul {
    padding:0px;
}
#betArea ul li {
    list-style-type:none;
    margin:0px;
    padding:0px;
}
#betArea span {
    margin:1px 5px 1px 5px;
    text-align:center;
}
</style>
<script src="js/My97DatePicker/WdatePicker.js"></script>
<script>
$(function(){
    //准备数据
    var json_lotterys = <?php echo $json_lotterys; ?>;
    var tmp = '';
//        $('select').click(function(){
//            alert(this.innerHTML);
//        });
    $('#form1').submit(function(){
        var flag = true;
        // 这种做法return false;只是退出匿名函数，对submit()段不起作用:)
        $('select').each(function(i){
            if ($(this).val() == 0) {
                flag = false;
            }
        });
        if (flag == false) {
            alert('所有下拉框均须有值');
        }
        return flag;
    });

    //彩种选择框
    $.each(json_lotterys, function(i,v){
        tmp = '<option value=' + v.lottery_id + '>' + v.name + '</option>';
        $('select[name=lottery_id]').append(tmp);
    });
    $('select[name=lottery_id]').change(function(){
        if ($('select[name=lottery_id]').val() == 0) {
            $('select[name=issue]').empty().append('<option value="">请选择</option>');
            return;
        }
        getIssue();
    });
    $('select[name=dates]').change(function(){
        if ($('select[name=dates]').val() == '') {
            return;
        }
        getIssue();
    });

    //动态读取彩种奖期
    function getIssue()
    {
        if ($('select[name=lottery_id]').val() == 0) {
            return;
        }
        $.post(
            '?c=game&a=getIssue',
            {'lottery_id':$('select[name=lottery_id]').val(), 'start_time':$('select[name=dates]').val()},
            function(json_data) {
                $('select[name=issue]').empty().append('<option value="">请选择</option>');
                $.each(json_data, function(i,v){
                    tmp = '<option value="' + v.issue + '">' + v.issue + '（' + v.code + '）' +' (' + v.start_sale_time + '~' + v.end_sale_time + ')</option>';
                    $('select[name=issue]').append(tmp);
                });
                //预选中奖期
                $('select[name=issue]').val('<?php echo $issue; ?>');
        }, 'json');
    }


    $('select[name=issue]').change(function(){
        if ($('select[name=issue]').val() == 0) {
            return;
        }
        getPackage();
    });
    //动态读取某奖期的所有订单
    function getPackage()
    {
        $.post(
            '?c=test&a=testRebate',
            {'op':'getPackage','lottery_id':$('select[name=lottery_id]').val(), 'issue':$('select[name=issue]').val()},
            function(json_data) {
                $('select[name=package_id]').empty().append('<option value="">请选择</option>');
                $.each(json_data, function(i,v){
                    tmp = '<option value="' + v.package_id + '">id:' + v.package_id + ' 金额:' + v.amount +' (' + v.create_time  + ')</option>';
                    $('select[name=package_id]').append(tmp);
                });
        }, 'json');
    }

    //设置默认值
    $('select[name=lottery_id]').val('<?php echo $lottery_id; ?>').change();

    $('.submit').click(function(){
        //因为数据需要预处理，用$.post提交，代替form提交
        $.post(
                '?c=test&a=testRebate',
                {
                    'op':$(this).attr('name'),
                    'lottery_id':$('select[name=lottery_id]').val(),
                    'issue':$('select[name=issue]').val(),
                    'package_id':$('select[name=package_id]').val()
                },
                function(response){
                    if (response.errno == 0) {
                        $('#result').text('执行成功:)');
                        alert('执行成功:)');
                    }
                    else {
                        $('#result').text('执行失败:'+ response.errstr + "(errno=" + response.errno +")").css('color', 'red');
                    }
            }, 'json');
    });
});
</script>

<form name="form1" id="form1" class="form-top" action="?c=test&a=<?php echo ACTION; ?>" method="POST">
    <table class="table table-responsive table-bordered mt20" style="width:60%;">
        <tr>
            <td>
                <div class="form-inline">
                    <label>游戏名称:</label>
                <select class="input-md form-control" name="lottery_id"><option value="0">请选择</option></select>
                <label class="ml10">日期:</label>
                <select class="input-md form-control" name="dates">
                    <option value="">请选择</option>
                    <?php foreach ($dates as $v): ?>
                    <option value="<?php echo $v;?>"><?php echo $v;?></option>
                    <?php endforeach; ?>
                </select>
                <label class="ml10">游戏奖期：</label>
                <select class="input-md form-control" name="issue"><option value="">请选择</option></select>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="form-inline">
                    <label>该期订单:</label>
                    <select class="input-md form-control" name="package_id"><option value="0">请选择</option></select>
                    <span> 如果不选择，将针对所有订单！</span>
                </div>
            </td>
        </tr>
    </table>
<p>以下全部为ajax调用</p>
<table class="table table-responsive  table-bordered" style="width:60%;">
    <tr>
        <td>
            <div class="form-inline">
                <input class="btn btn-info submit" type="button" name="doRebate"  value="上级返点"/>
                <input class="btn btn-info submit" type="button" name="doCancelRebate"  value="(因撤单)取消该单所有返点"/><span>(由于自身返点也被取消，一般不独立执行，作为撤单的一个子步骤执行)</span>
            </div>
        </td>
    </tr>
    <tr>
        <td>
            <div class="form-inline">
                <input class="btn btn-info submit" type="button" name="doJudgePrize"  value="中奖"/>
                <input class="btn btn-info submit" type="button" name="doSendPrize"  value="派奖"/>
                <input class="btn btn-info submit" type="button" name="doCancelPrize"  value="取消派奖"/>(可重复执行) 
            </div>
        </td>
    </tr>
    <tr>
        <td>
            <input class="btn btn-info submit" type="button" name="doCancelPackage" value="系统撤单"/>(如果已派奖先撤消派奖，如果上级已返点则撤消返点，自身撤单返款)
        </td>
    </tr>
</table>
</form>
<br/>
<h4>结果：<span id="result"></span></h4>

<?php $this->import("foot"); ?>