<?php $this->import("head"); ?>
<script>
function checkform(ob) {
    var msg = "";
    if (ob.real_name.value == "" && ob.real_name.value == "") {
        msg = "请输入真实姓名";
    }
	if (ob.remark.value == "" && ob.remark.value == "") {
        msg = "请输入修改原因";
    }

    if (msg != "") {
        alert(msg);
        return false;
    }
    return true;
}
</script>
<div class="list-div" id="addDiv">
<form name="form1" id="form1" action="?c=user&a=editRealName" method="post" onsubmit="return checkform(this)">
<table>
    <tr>
        <td width="40%">用户名</td>
        <td width="60%"><?php echo $user['username']; ?></td>
    </tr>
	<tr>
        <td width="40%">昵称</td>
        <td width="60%"><?php echo $user['nick_name']; ?></td>
    </tr>
    <tr>
        <td>真实姓名</td>
        <td><input name="real_name" value="<?php echo $user['real_name']; ?>"/></td>
    </tr>
    <tr>
        <td>修改原因</td>
        <td><textarea name="remark"></textarea></td>
    </tr>
	<tr>
		<td></td>
		<td>
			<input type="hidden" name="user_id" value="<?php echo $user['user_id']; ?>" />
			<input type="hidden" name="op" value="doEditRealName" />
			<input type="submit" class="submit" name="submitBtn" value="更新" />
			<input type="button" class="submit" onclick="javascript:history.go(-1);" value="返回"/>
		</td>
	</tr>
</table> 
</form>
</div>
<?php $this->import("foot"); ?>