<?php $this->import("head"); ?>
<span style="display:inline-block;height:35px;line-height:35px;font-size:14px;">说明：权限管理的实现基于控制器和行为来限定。</span>
<br/>
<div id="listDiv">
        <form name="form1" class="form-top" id="form1" action="./?c=userMenu&a=<?php echo ACTION; ?>" method="post" onsubmit="return checkform(this)">
            <table class="table table-responsive  table-bordered mainList" width="100%">
                <thead>
                <tr>
                    <td>menu id</td>
                    <td>名称</td>
                    <td>说明</td>
                    <td>控制器</td>
                    <td>行为</td>
                    <td>是否启用</td>
                    <td>是否记录日志</td>
                    <td>排序</td>
                    <td>下级菜单</td>
                    <td>更新时间</td>
                    <td>操作</td>
                </tr>
                </thead>
                <?php foreach ($menus as $v): ?>
                <tr>
                    <td><?php echo $v['menu_id']; ?></td>
                    <td><?php echo $v['title']; ?></td>
                    <td><?php echo $v['description']; ?></td>
                    <td><?php echo $v['control']; ?></td>
                    <td><?php echo $v['action']; ?></td>
                    <td><?php if ($v['is_enabled']): ?>启用<?php else: ?>禁用<?php endif; ?></td>
                    <td><?php if ($v['is_log']): ?>记录<?php else: ?>不记录<?php endif; ?></td>
                    <td><input class="input-sm form-control" type="text" name="sort_ids[<?php echo $v['menu_id']; ?>]" value="<?php echo $v['sort']; ?>" size="3"/></td>
                    <td>
                        <?php if ($v['is_menu'] == 1): ?>
                            <a class="btn btn-mini btn-info" href="./?c=userMenu&a=menuList&parent_id=<?php echo $v['menu_id']; ?>&prev_id=<?php echo $parent_id; ?>">下级菜单</a>
                        <?php else: ?>
                            无
                        <?php endif; ?>
                    </td>
                    <td><?php echo $v['ts']; ?></td>
                    <td>
                        <?php if ($v['is_menu'] == 1): ?>
                            <a class="btn btn-mini btn-info" href="./?c=userMenu&a=addMenu&parent_id=<?php echo $v['menu_id']; ?>">增加</a>
                        <?php else: ?>
                            &nbsp;
                        <?php endif; ?>
                        <a class="btn btn-mini btn-info" href="./?c=userMenu&a=editMenu&menu_id=<?php echo $v['menu_id']; ?>&prev_id=<?php echo $v['parent_id']; ?>">编辑</a>
                        <a class="btn btn-mini btn-info" href="./?c=userMenu&a=deleteMenu&menu_id=<?php echo $v['menu_id']; ?>" onclick="return confirm('真的删除？该操作不可恢复！');">删除</a>
                    </td>
                </tr>
                <?php endforeach; ?>
                <td colspan="7">&nbsp;</td>
                <td>
                    <input class="btn btn-default" type="submit" name="submit" class="submit" value="保存"/>
                </td>
                <td>
                    <?php if ($parent_id > 0): ?>
                        <input class="btn btn-default" type="button" name="button" class="submit" value="上级" onclick="window.location.href='./?c=userMenu&a=menuList&parent_id=<?php echo $prev_id; ?>';">
                    <?php endif; ?>
                </td>
                <td colspan="2"></td>
            </table>
                <input type="hidden" name="prev_id" value="<?php echo $prev_id; ?>"/>
                <input type="hidden" name="sa" value="saveSort"/>
        </form>
</div>

<?php $this->import("foot"); ?>