<?php $this->import("head"); ?>
<script src="<?php echo $imgCdnUrl ?>/js/My97DatePicker/WdatePicker.js"></script>
<script src="<?php echo $imgCdnUrl ?>/js/jqueryUI/dialog/js/jquery.dialog.js?_=1" type="text/javascript"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $imgCdnUrl ?>/js/jqueryUI/dialog/css/jquery.dialog.blue.css" />
<script>
//预设查询值
    $(function() {
        $('input[name=username]').val('<?php echo $username; ?>');
        $('input[name=bank_username]').val('<?php echo $bank_username; ?>');
        $('select[name=bank_id]').val('<?php echo $bank_id; ?>');
        $('input[name=card_num]').val('<?php echo $card_num; ?>');
        $('select[name=status]').val('<?php echo $status; ?>');
    });
</script>
    <!------------------author snow 引入搜索相关文件--------------------------->
    <link rel="stylesheet" href="/js/jquery-select/bootstrop-select.css">
    <script src="/js/jquery-select/bootstrop.min.js"></script>
    <script src="/js/jquery-select/bootstrop-select.js"></script>
    <!------------------author snow 引入搜索相关文件--------------------------->
<div id="query">
    <form name="form1" action="./" method="get">
        <div class="form-inline mt15">
            <label>用户名：</label>
            <input class="input-md form-control" name="username" size="12"/>
            <label>银行：</label>
            <select class="selectpicker bank_id" name="bank_id" id="bank_id" data-live-search="true" title="请选择 ...">
                <option value="">请选择…</option>
                <?php foreach ($withdrawBankList as $k => $v): ?>
                    <option value="<?php echo $k; ?>"><?php echo $v['name'] . '-' . $v['firstCharter'] ; ?></option>
                <?php endforeach; ?>
            </select>

            <label>卡号：</label>
            <input class="input-md form-control" name="card_num" size="12"/>
            <label>状态：</label>
            <select class="input-md form-control" name="status">
                <option value="-1">请选择</option>
                <option value="1">正常</option>
                <option value="0">已删除</option>
                <option value="2">已冻结</option>
            </select>
            <input type="hidden" name="c" value="user"/>
            <input type="hidden" name="a" value="bindCardList"/>
         　　 <input class="btn btn-info  " type="submit" name="submit" value=">> 查 询 <<"/>
            <input class="btn btn-info ml15" type="submit" name="wrongCard" value="查询不规则的银行卡"/>
            <input style="margin-left: 10px" class="btn btn-info excel"  type="button" table=".mainList" excelFile="用户卡列表"  value="导出Excel"/>
        </div>
        <!--用户名
        开户名<input name="bank_username" size="12"/>
        银行<select name="bank_id">
            <option value="0">请选择</option>
            <?php foreach ($withdrawBankList as $k => $v): ?>
                <option value="<?php echo $k; ?>"><?php echo $v; ?></option>
            <?php endforeach; ?>
        </select>
        卡号<input name="card_num" size="12"/>
        状态<select name="status">
            <option value="-1">请选择</option>
            <option value="1">正常</option>
            <option value="0">已删除</option>
            <option value="2">已冻结</option>
        </select>
        <input type="hidden" name="c" value="user"/><input type="hidden" name="a" value="bindCardList"/>
         　　<input type="submit" name="submit" value=">> 查 询 <<"/><input type="submit" name="wrongCard" value="查询不规则的银行卡"/>-->
    </form>
    <h4></h4>
</div>

<div class="list-div form-top" id="listDiv">
    <table class="table table-responsive table-bordered mainList">
        <thead>
            <tr>
                <td>bind_card_id</td>
                <td>用户id</td>
                <td>用户名</td>
                <td>开户名</td>
                <td>卡号</td>
                <td>所属银行</td>
                <td>省份</td>
                <td>城市</td>
                <td>添加时间</td>
                <td>状态</td>
                <td>操作</td>
            </tr>
        </thead>
        <?php foreach ($cards as $v): ?>
            <tr>
                <td><?php echo $v['bind_card_id']; ?></td>
                <td><?php echo $v['user_id']; ?></td>
                <td><?php echo $v['username']; ?><?php if ($v['type'] == 1): ?><b style="color:red">[推广]</b><?php endif; ?></td>
                <td><?php echo mb_substr($v['bank_username'],0,mb_strlen($v['bank_username'],'utf-8')-1,'utf-8') . '*'; ?></td>
                <td><?php echo $v['card_num']; ?></td>
                <!-------author snow 更改取值方式------->
                <td><?php echo $withdrawBankList[$v['bank_id']]['name']; ?></td>
                <!-------author snow 更改取值方式------->
                <td><?php echo $v['province']; ?></td>
                <td><?php echo $v['city']; ?></td>
                <td><?php echo $v['create_time']; ?></td>
                <td>
                    <?php if ($v['status'] == 1): ?>正常
                    <?php elseif ($v['status'] == 0): ?><del>已删除</del>
                    <?php elseif ($v['status'] == 2): ?><del>已冻结</del>
                    <?php endif; ?>
                </td>
                <td>
                    <a class="btn btn-mini btn-info " href="/?c=user&a=editBindCard&bind_card_id=<?php echo $v['bind_card_id']; ?>">编辑</a>
                    <?php if ($canDelete): ?>
                        <?php if ($v['status'] == 1): ?>
                            <a class="btn btn-mini btn-info" data-id="<?=$v['bind_card_id']?>" href="#"  id ="del" >删除</a>
                        <?php endif; ?>
                        <?php if ($v['status'] != 2): ?>
                            <a class="btn btn-mini btn-info" data-id="<?=$v['bind_card_id']?>" href="#" id ="frozen" >冻结</a>
                        <?php endif; ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
<input type="hidden" name="hide">

<script>
    var func = function (par,frozen){

        $("[name='hide']").val($(par).data('id'));

        var url = " ./?c=user&a=deleteCard&frozen=1&bind_card_id="+$("[name='hide']").val();
        //冻结时提示语
        title = 'title="注意：对于确认为套利客或者恶意用户的银行卡，冻结之后，永远不可再次绑定!"';
        if(frozen === 0){
            url = " ./?c=user&a=deleteCard&bind_card_id="+$("[name='hide']").val();
            //删除时提示语
            var title = 'title="注意：删除之后，可再次绑定!"';
        }

        var formStr = '<form class="remark_form" method="post">输入理由：<textarea class="input-md form-control remark_text" name="remark"></textarea></form>';
        $('<div ' + title + '>' + formStr + '</div>').dialog({
                bgiframe: true,
                width: 300,
                buttons: {
                    "确定": function() {
                            if($(".remark_text").val()===''){
                                alert("理由不能为空");
                            }else{
                                $(".remark_form").attr("action",url);
                                $(".remark_form").submit();
                            }
                    },
                    "取消": function() {
                        $(par).dialog("close", window.self);       //关闭这个对话框
                    }
                }
            }, window.self);
    };
    $('#frozen ').click(function(){
        func(this,1);
    });
    $('#del ').click(function(){
        func(this,0);
    });
</script>
<div class="pageTal">
    
<?php echo $pageList; ?>

</div>
<div class="tip">
</div>

<?php $this->import("foot"); ?>