<?php $this->import("head"); ?>

<div class="list-div add-main form-top mt20" id="addDiv">
<form name="form1" id="form1" action="./?c=domains&a=domainsUpdata" method="post">
	<table class="table table-responsive table-bordered" cellpadding="0" cellspacing="0" style="width: 50%;">
	
		<tr>
			<td width="20%">代理帐号</td>
			<td><input class="input-md form-control" name="username" maxlength="19" readonly="readonly" value="<?php echo $userDomains['0']['username']?>"/></td>
		</tr>
		<tr>
			<td>代理昵称</td>
			<td><input class="input-md form-control"  name="nick_name" value="<?php echo $userDomains['0']['nick_name']?>" /></td>
            <input type="hidden" name="ud_id" value="<?php echo $userDomains['0']['ud_id'];?>"/>
		</tr>
<!--		<tr>-->
<!--			<td>推广码</td>-->
<!--			<td><input class="input-md form-control"  name="ext_code" value="--><?php //echo $userDomains['0']['ext_code']?><!--"/><b style="color:red">备注:推广码长度6~8位，格式:字母，数字或字母数字组合!</b>-->
<!--			<input type="hidden" name="ud_id" value="--><?php //echo $userDomains['0']['ud_id']?><!--"/></td>-->
<!--		</tr>-->
		<!--<tr>
			<td>域名</td>
			<td><input class="input-md form-control"  name="domain" value="<?php echo $userDomains['0']['name']?>"/>
			</td>
		</tr>-->

		<tr>
			<td colspan="2">
				<div style="width: 60%;margin: 0 auto;text-align: center;"> 
					<input class="btn btn-info submit" type="submit" style="width: 60px;" name="submit" value="提交" />
					<input class="btn btn-info submit" type="button" style="width: 60px" onclick="window.location.href='?c=domains&a=domainsList';" value="返回"/>
					<input type="hidden" name="user_id" value="" />
				</div>
			</td>
		</tr>
	</table>
</form>
</div>
<!--<script>
    $(function() {
        var action = "<?php echo ACTION; ?>";
        if (action == 'editUser') {
            $("input[name=user_id]").val("<?php echo $user['admin_id']; ?>");
            $("input[name=username]").val("<?php echo $user['username']; ?>");
            $("input[name=pwd]").val("");
            $("input[name=pwd2]").val("");
            $("select[name=group_id]").val("<?php echo $user['group_id']; ?>");
            let enableStatus = <?php if ($user['is_enabled'] == 1): ?>true<?php else: ?>false<?php endif; ?>;
            if(!enableStatus){$('#switch').removeClass("on").addClass("off");}else{$('#switch').removeClass("off").addClass("on");}
            //状态值已与数据库同步但是切换状态没变
        }
        else if (action == 'editPwd') {
            $("input[name=user_id]").val("<?php echo $user['admin_id']; ?>");
            $("input[name=username]").val("<?php echo $user['username']; ?>").attr('disabled', true);
            $("input[name=pwd]").val("");
            $("input[name=pwd2]").val("");
            $("select[name=group_id]").val("<?php echo $user['group_id']; ?>").attr('disabled', true);

        }










    });

    function toogle(th) {
        let ele = $(th).children(".move");
        if ($(th).hasClass('on')) {
            ele.animate({left: "1px"}, 300, function () {
            });
            $(th).removeClass("on").addClass("off");
            $("input[name=is_enabled]").val(0);
        } else {
            ele.animate({left: '35px'}, 300, function () {
            });
            $(th).removeClass("off").addClass("on");
            $("input[name=is_enabled]").val(1);
        }


    }



</script>-->
<?php $this->import("foot"); ?>

