<?php $this->import("head"); ?>
<script src="js/My97DatePicker/WdatePicker.js"></script>
<script src="js/area/area.js"></script>
<script>
function checkform(ob) {
    var msg = "";
/*********************************** snow 修改提示内容 为叠加 并加入 单笔100万金额限制***********************************************************/
    if (ob.username.value == "") {
        msg = "请选择用户名:";
    }
     if (ob.bank_id.value == "0") {
        msg += "请选择银行:";
    }
     if (ob.card_name.value == "") {
        msg += "请输入卡户名:";
    }
     if (ob.card_num.value == "") {
        msg += "请输入卡号:";
    }
     if (ob.city.value == "") {
        msg += "请选择城市:";
    }
     if (ob.branch.value == "") {
        msg += "请输入开户网点地址:";
    }

//    else if (ob.player_pay_time.value == "" || (!/\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}/.test(ob.player_pay_time.value) && !/\d{4}年\d{2}月\d{2}日 \d{2}:\d{2}:\d{2}/.test(ob.player_pay_time.value))) {
//        msg = "请输入正确的付款时间";
//    }
//    else if (ob.order_num.value == "") {
//        msg = "请输入订单号，24位";
//    }
     if (ob.amount.value == "") {
        msg += "请输入正确的金额，2位小数:";
    }

     if (ob.amount.value > 1000000) {
        msg += "单笔金额不能超过100万:";
    }
//    else if (ob.trade_type.value == "5" && ob.fee2.value == "") {
//        msg = "ATM现存必须填写手续费0";
//    }
//    else if (ob.trade_type.value == "7" && ob.trade_place.value == "") {
//        msg = "跨行没有交易地点，请仔细核对数据";
//    }

    if (msg != "") {

        try{
            window.parent.layer.alert(msg + "！");
        }catch(e){
            alert(msg + "！");
        }
        return false;
    }
    /***************************** snow 修改提示内容 为叠加 并加入 单笔100万金额限制***********************************************************/

    return true;
}

$(document).ready(function(){
    //预设查询值
//    $('#bank_id').val('<?php echo $bank_id; ?>').change();
});
</script>

    <!------------------author snow 引入搜索相关文件--------------------------->
    <link rel="stylesheet" href="/js/jquery-select/bootstrop-select.css">

    <script src="/js/jquery-select/bootstrop.min.js"></script>
    <script src="/js/jquery-select/bootstrop-select.js"></script>
    <!------------------author snow 引入搜索相关文件--------------------------->
<div class="list-div add-main mt20" id="addDiv">
<form name="form1" id="form1" class="form-top" action="?c=withdraw&a=<?php echo ACTION; ?>" method="post" onsubmit="return checkform(this)">
<table class="table table-responsive table-bordered" cellpadding="0" cellspacing="0" style="width:50%;">
    <tr>
        <td colspan="2" class="rowTitle">
            <b>手工添加提款提案</b>
        </td>
    </tr>
    <tr>
        <td>用户帐号</td>
        <td><input class="input-sm form-control" type="text" name="username" value=""/>
        </td>
    </tr>
</table>
<br/>
<table class="table table-responsive table-bordered" cellpadding="0" cellspacing="0" style="width:50%;">
    <tr>
        <td class="rowTitle" colspan="2">
            <b>提款信息</b>
        </td>
    </tr>
    <tr>
        <td>所属银行:</td>
        <td>
            <!------------------ author snow 修改成可搜索------------------------------>
            <select class="selectpicker bank_id" name="bank_id" id="bank_id" data-live-search="true" title="请选择 ...">
                <option value="0">请选择…</option>
                <?php foreach ($bankList as $k => $v): ?>
                    <option value="<?php echo $k; ?>"><?php echo $v['name'] . '-' . $v['firstCharter'] ; ?></option>
                <?php endforeach; ?>
            </select>
            <!------------------ author snow 修改成可搜索------------------------------>
        </td>
    </tr>
    <tr>
        <td>户名:</td>
        <td><input class="input-md form-control" name="card_name"/></td>
    </tr>
    <tr>
        <td>卡号:</td>
<!--        /******* snoww 修复 form-control 后面缺少一个 " 引号   *******/-->
        <td><input class="input-md form-control" name="card_num" maxlength="19" /></td>
    </tr>
    <tr>
        <td>所在地区:</td>
        <td>
            <div class="form-inline">
                <select class="input-md form-control input_bk_D2D2D2 mb10" style="width:200px;" name="province"  id="province" onChange="SelChgCity('city' , document.getElementById('province').options[document.getElementById('province').selectedIndex].value , arrProvince , arrCity , 'country');">
                </select>省
            </div>
            <div class="form-inline">
                <select class="input-md form-control input_bk_D2D2D2" style="width:200px;" name="city"  id="city">
            </select>市
            </div>
            
        </td>
    </tr>
    <tr>
        <td>开户网点地址:</td>
        <td><input class="input-md form-control" name="branch" /></td>
    </tr>
    <tr>
        <td>提款金额:</td>
        <td><input class="input-md form-control" name="amount"/></td>
    </tr>
    <tr>
        <td>备注:</td>
        <td>
            <textarea class="input-md form-control" style="height: 50px;" name="remark">手工添加</textarea>
        </td>
    </tr>
    <tr>
        <td colspan="2">
            <div style="width:100%;margin:0 auto;text-align:center;">
                <input class="btn btn-info submit" type="submit" style="width: 60px;"  name="submit" value="提 交" />
            </div>
        </td>
    </tr>
</table>

</form>
</div>
<script language="javascript">
	InitArea("province" , "city" , "country" , arrProvince , arrCity , arrCountry , "" , "" , "");
</script>
<?php $this->import("foot"); ?>