<!DOCTYPE HTML>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="webkit" name="renderer">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title><?php echo config::getConfig('site_title'); ?></title>
        <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/all_LightBlue.css?v=<?php echo $html_version_num; ?>" />
    </head>

    <body>
        <!-- 内页公用板块 -->
        <div class="GameBoxall SubGamePlatePadding">
          <div class="Gamepart">
            <div class="subTopBar">
              <div class="SubTit">
                <h3>客户端下载</h3>
              </div>
            </div>
            <div class="clear"></div>
            <div class="sub_public">
              <ul class="Khd_ContBox">
                 <li class="t-l">
                    <div class="content-text">
                        <h5>Windows 客户端</h5>
                            <dl>
                                <dd>大小：684K</dd>
                                <dd>适用系统：Windows</dd>
                                <dd>更新时间：2015-11-24</dd>
                            </dl>
                        <a class="download" href="/upload/jyzsetup.rar"></a>
                    </div>
                 </li>
                 <li class="t-r "></li>
                 <li class="b-l">
                     <div class="content-text">
                        <h5>Android 手机APP</h5>
                        <img src="<?php echo $imgCdnUrl ?>/images/light_blue/download/android_QR.png" alt="扫描二维码下载" width="100" height="100">
                        <a class="download" href="/upload/jyz_160309_1_1_1.apk"></a>
                    </div>
                 </li>
                 <li class="b-r"></li>
              </ul>
            </div>
          </div>
        </div>
    </body>
</html>
