<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="webkit" name="renderer">
        <meta charset="UTF-8">
        <title><?php echo config::getConfig('site_title'); ?></title>
        <link rel="shortcut icon" href="<?php echo $imgCdnUrl ?>/images/favicon.ico" type="images/x-icon">
        <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/global_reset.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/ZClijin.css"/>
    </head>
    <body>
        <div class="content">
            <div class="Top">
                <img class="TopImgone" src="<?php echo $imgCdnUrl ?>/images/ZClijin/title.png"/>
                <img class="TopImgtwo" src="<?php echo $imgCdnUrl ?>/images/ZClijin/backdrop.png"/>
            </div>
            <div class="CZmain">
                <div class="ContentText">
                    <div class="mainBg fix">
                        <div class="headline">
                            <span>01</span>
                            <h3></h3>
                        </div>
                        <div class="headlineOne">
                            <span>报名方式</span>
                            <p>注册充值后联系客服报名登记，领取礼金前投注将无法申请礼金。</p>
                        </div>
                    </div>
                </div>
                <div class="ContentTextOne">
                    <div class="mainBg fix">
                        <div class="headline">
                            <span>02</span>
                            <h3></h3>
                        </div>
                        <div class="headlineOne">
                            <span>活动内容</span>
                            <p>试营业期间，凡单笔充值金额3000元及以上，联系客服报名、风控部门审核后将直接赠送20%充值礼金。</p>
                        </div>
                    </div>
                </div>
                <div class="ContentTextTwo">
                    <div class="mainBg fix">
                        <div class="headline">
                            <span>03</span>
                            <h3></h3>
                        </div>
                        <div class="headlineOne">
                            <span>活动规则</span>
                            <p>（1）活动期间一个用户每天最多可领取一次，每天100个名额；</p>
                            <p>（2）活动期间内，参加活动的用户流水必须满足本金的20倍则可提现，未达标流水继续充值将累加充值金额的30%流水；</p>
                            <p>（3）活动期间每期玩法下注注数不得高于全包玩法的70%；</p>
                            <p>（4）但凡活动结束，用户获得前置礼金而未满足投注流水，扣除前置礼金后方可出款；</p>
                            <p>（5）若风控部门发现利用多个账户对冲或其他一切方式进行套利，将直接扣除违规所得情节严重者直接冻结账户；</p>
                            <p>（6）游戏拥有对该活动的一切解释权且有权进行变更或修改。</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
