<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="yes" name="apple-mobile-web-app-capable">
    <meta content="yes" name="apple-touch-fullscreen">
    <meta content="telephone=no,email=no" name="format-detection">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title><?php echo config::getConfig('site_title'); ?></title>
</head>
<body>
<h1>尊敬的新老客户：我们正遭受大流量攻击，请您点击<a href="javascript:;" id="cl">（这里）</a>加速访问</h1>
</body>
<script src="<?php echo $imgCdnUrl ?>/js/jquery-1.8.3.min.js" type="text/javascript"></script>
<script type="text/javascript">
$('#cl').click(function(){
	console.log(12);
		$.ajax({
            type : 'post',
            url : '?a=verify',
            data : {verify:1},
            success : function(response){
            	console.log(response);
            	return false;
                if (response == '1') {
                    location.href = '?a=login';
                }
            }
        });
	});
</script>
</html>