<!DOCTYPE HTML>  <!-- 银行资料管理之解锁页面 -->
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="webkit" name="renderer">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title><?php echo config::getConfig('site_title'); ?></title>
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/all_LightBlue.css?v=<?php echo $html_version ?>" />
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/global_reset.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/common_operate.css" />
    <?php $this->import('public_cssjs') ?>
</head>

<body>
<?php $this->import('public_header') ?>
<div class="operate_middle_page">
    <?php $this->import("public_usermenu"); ?>

    <div class="common_pages default_operate_pageheight">
        <table class="defoperate_record_tablist">
            <thead>
            <tr class="defoperate_record_tabtitle">
                <th width="23%">绑定银行类型</th>
                <th width="18%">开户人姓名</th>
                <th width="25%">银行卡账号</th>
                <th width="19%">最后操作时间</th>
                <th width="16%">状态</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td><?php echo $withdrawBankList[$userBindCard['bank_id']]; ?></td>
                <td><span class="yellow"><?php echo $userBindCard['bank_username']; ?></span></td>
                <td><?php echo $userBindCard['card_num']; ?></td>
                <td><?php echo $userBindCard['ts']; ?></td>
                <td><?php
                    if($userBindCard['status'] == 1) {
                        $statusDesc =  '已锁定';
                    }elseif($userBindCard['status'] == 3 && time() > $userBindCard['frozen_ts'] + 3*24*3600){
                        $statusDesc = '已解锁';
                    }elseif($userBindCard['status'] == 3){
                        $statusDesc = '解锁中';
                    }else{
                        $statusDesc = '';
                    }
                    echo $statusDesc;
                    ?>
                </td>
                <td></td>
            </tr>
            </tbody>
        </table>

        <div class="middle_modify_layer unbindcard_modify_layer">
            <form name="form1" id="form1" action="index.jsp?c=fin&a=<?php echo ACTION; ?>" method="post">
                <input type="hidden" name="bind_card_id" value="<?php echo $userBindCard['bind_card_id'];?>">
                <div class="form_group">
                    <label for="safe_pwd" class="control_label">安全码：</label>
                    <div class="col_sm_10">
                        <input type="password" class="form_control" name="safe_pwd" id="safe_pwd">
                    </div>
                </div>
                <div class="form_group">
                    <label for="verifyCode" class="control_label">验证码：</label>
                    <div class="col_sm_10">
                        <input type="text" size="4" maxlength="4" id="verifyCode" name="verifyCode" class="form_control input_verifycode">
                        <img align="absmiddle" id="code" src="?c=default&a=verifyCode" width="70" height="20" border="1" title="點擊更換驗証串" style="cursor: pointer; border-color: rgb(255, 255, 255);float: left;">
                    </div>
                </div>
                <div class="form_group msgsend_btn_layer">
                    <input type="submit" class="default_navyblue_btn personal_infor_subbtn" value="提交" name="submit">
                    <input type="button" onclick="javascript:history.go(-1);" class="default_common_btn defaultbig_gray_btn hundred_twenty_width" value="返回" name="返回">
                </div>
            </form>
        </div>
    </div>
</div>
<?php $this->import('public_foot') ?>
<script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/jquery.plugin.js"></script><!--jquery小插件-->

<script>
    $(document).ready(function() {
        $('#verifyCode').focus(function(){
                getCode('#code');
            })
            $('#code').click(function(){
                getCode('#code');
                $('#verifyCode').focus();
            })
            function getCode(ele){
                $(ele).attr('src','?a=verifyCode&'+Math.random())
            }
        <?php if (ACTION == 'editPwd'): ?>
        $("input[name=user_id]").val("<?php echo $user['user_id']; ?>");
        $("input[name=oldpassword]").val("");
        $("input[name=password]").val("");
        $("input[name=password2]").val("");
        $("input[name=oldsecpassword]").val("");
        $("input[name=secpassword]").val("");
        $("input[name=secpassword2]").val("");
        <?php endif; ?>
        $('#form1').submit(function() {
            if ($('input[name=oldpassword]').val().length < 6) {
                alert('请输入旧密码');
                return false;
            }
            if ($('input[name=password]').val().length < 6 || $('input[name=password]').val() != $('input[name=password2]').val()) {
                alert('请正确输入新密码，6位字符以上，字母和数字混合，且两次输入的要一致');
                return false;
            }
        });
        $('#form2').submit(function() {
            if ($('input[name=oldsecpassword]').val().length < 6) {
                alert('请输入旧密码');
                return false;
            }
            if ($('input[name=secpassword]').val().length < 6 || $('input[name=secpassword]').val() != $('input[name=secpassword2]').val()) {
                alert('请正确输入新密码，6位字符以上，字母和数字混合，且两次输入的要一致');
                return false;
            }
        });
    });
</script>

</body>
</html>