<!DOCTYPE HTML>  <!-- 个人账变 -->
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="webkit" name="renderer">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title><?php echo config::getConfig('site_title'); ?></title>
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/common_operate.css"/>
    <?php $this->import('public_cssjs') ?>
</head>
<body>
<!-- 顶部导航信息部分 -->
<?php $this->import('public_header') ?>
<!-- End 顶部导航条 -->
<div class="operate_middle_page">
    <?php $this->import("public_usermenu"); ?>

    <div class="common_pages default_big_pageheight">
        <div class="default_record_search">
            <form method="get" action="" id="form1" name="form1">
                <ul>
                    <li>
                        <label class="search_record_gamelab">充值或提款：</label>
                        <select  class="default_common_input" onchange="choiceType(this)">
                            <option value="recharge"<?php if($key === 'recharge'):?>selected="selected"<?php endif;?>>充值</option>
                            <option value="withdraw" <?php if($key === 'withdraw'):?>selected="selected"<?php endif;?>>提款</option>
                        </select>
                        <input type="hidden" name="key" value="recharge">
                    </li>
                    <li>
                        <label class="search_record_datelab">时间：</label>
                        <div class="record_date_range">
                            <input size="15" name="startDate" id="startDate" my97mark="false"
                                   onfocus="WdatePicker({dateFmt: 'yyyy-MM-dd'})"
                                   class="default_common_input datepicker85"/>
                            <em>到</em>
                            <input size="15" name="endDate" id="endDate" my97mark="false"
                                   onfocus="WdatePicker({dateFmt: 'yyyy-MM-dd'})"
                                   class="default_common_input datepicker85"/>
                        </div>
                    </li>
                    <li>
                        <input type="hidden" name="c" value="fin"/>
                        <input type="hidden" name="a" value="<?php echo ACTION; ?>"/>
                        <input type="submit" value="搜索" class="default_record_searchbtn" name="submit">
                    </li>
                    <li class="float_right">
                        <div class="user-page-boxs">
                            <?php echo $pageList; ?>
                        </div>
                    </li>
                </ul>
            </form>
        </div>

        <table class="defoperate_record_tablist">
            <thead>
            <tr class="defoperate_record_tabtitle">
                <th>订单号</th>
                <th>订单状态</th>
                <th>备注</th>
                <th>提交时间</th>

            </tr>
            </thead>
            <tbody>
            <?php $arrStatus=['未处理','已受理','已审核','机器正在受理','需要人工干预','--','--','--','已成功','因故取消']; if ($list): ?>
                <?php foreach ($list as $v): ?>
                    <tr class="recordsContent">
                        <?php if($key === 'withdraw'):?>
                            <td>--</td>
                        <?php else:?>
                        <td><?php echo $v['local_order_num']; ?></td>
                        <?php endif;?>
                        <td><?php echo $arrStatus[$v['status']];?></td>
                        <td><?php if(empty($v['remark'])){echo '--';}else{echo $v['remark'];}?></td>
                        <td><?php echo $v['create_time']; ?></td>
                    </tr>
                <?php endforeach; ?>
                <tr>
                    <th colspan="8">
                        <div class="bottom_info">注：只能查询2个月以内的数据</div>
                    </th>
                </tr>
            <?php else: ?>
                <tr>
                    <th colspan="8" class="text_center">暂无数据显示</th>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
    </div>

</div>
<?php $this->import('public_foot') ?>
<script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/jquery.plugin.js"></script><!--jquery小插件-->
<script src="js/My97DatePicker/WdatePicker.js"></script>
<script>
    $(function () {
        //设置默认值
        $('select[name=orderType]').val('<?php echo $orderType; ?>');
        $('#startDate').val('<?php echo $startDate; ?>');
        $('#endDate').val('<?php echo $endDate; ?>');
    });

    function showPackageDetail(wrapId) {
        var str_award = '普通玩法';
        layer.open({
            type: 2,
            shadeClose: true,
            title: str_award + '&nbsp;&nbsp;订单编号：' + wrapId,
            closeBtn: false,
            shade: [0.3, '#000'],
            border: [0],
            area: ['824px', '550px'],
            content: ['index.jsp?c=game&a=packageDetail&wrap_id=' + wrapId]
        });
        $('div.xubox_title', document).addClass('layui-layer-title');
    }

    function choiceType(obj) {
        var vo = $(obj).find('option:selected').val();
        $("input[name='key']").val(vo);
    }
</script>
</body>
</html>