<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="webkit" name="renderer">
    <title><?php echo config::getConfig('site_title'); ?></title>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
    <meta content="no-cache" http-equiv="Pragma">
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/global_reset.css"/>
    <link href="css/chart.css" rel="stylesheet" type="text/css">
    <script src="<?php echo $imgCdnUrl ?>/js/jquery.js" type="text/javascript"></script>
    <link href="css/chart.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<div id="rightcon">
    <div style="display:none;" class="win_bot" id="msgbox">
        <h5 id="msgtitle"></h5>
        <div class="clear"></div>
        <div class="wb_con">
            <p id="msgcontent"></p>
        </div>
        <div class="clear"></div>
        <a id="msgpre" onclick="javascript:prenotice();" href="#" class="wb_p">上一条</a><a
                onclick="javascript:nextnotice();" href="#" class="wb_n">下一条</a></div>
    <script language="javascript">
    </script>
    <style>
        esun\: * {
            behavior: url(#default#VML)
        }
    </style>
    <div class="rc_con history">
        <div class="rc_con_lt"></div>
        <div class="rc_con_rt"></div>
        <div class="rc_con_lb"></div>
        <div class="rc_con_rb"></div>
        <div class="rc_con_to">
            <div class="rc_con_ti">
                <div class="history_code">
                    <table width="100%" border="0" cellspacing="0" cellpadding="0" id="tm">
                        <tbody>
                        <tr>
                            <td width="300" align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong>
                                    <font><?php echo $lottery['cname']; ?>：</font>
                                    基本走势 </strong></td>
                            <td align="right">
                                <div class="Tabfixed">
                                    <form method="POST">
                                            <span>
                                            <label for="has_miss">
                                                <input type="checkbox" id="has_miss" name="checkbox" value="checkbox"
                                                       checked="checked">
                                                显示遗漏分层
                                            </label>
                                            <label for="has_line">
                                                <input type="checkbox" id="has_line" value="checkbox" name="checkbox2">
                                                显示折线 </label>
                                            </span>&nbsp; <span>
                                            <label for="no_miss">
                                                <input type="checkbox" id="no_miss" value="checkbox" name="checkbox">
                                                不带遗漏</label>&nbsp;&nbsp;&nbsp;&nbsp;
                                            <!-- <label for="no_miss"> 显示期数：
                                                <select name="issueNum" id="issueNum">
                                                <option value="50" selected="">50 &nbsp;&nbsp;期</option>
                                                <option value="100">100 期</option>
                                                <option value="200">200 期</option>
                                                </select>
                                            </label> -->
                                            </span>
                                    </form>
                                </div>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="hrc_list">
                    <div class="hrl_list">
                        <table border="0" cellspacing="1" cellpadding="0" id="chartsTable">
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>
<div class="layer"></div>
</body>
<script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/template-web.js"></script>
<script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/game_chart.js"></script>
<script src="<?php echo $imgCdnUrl ?>/js/line.js" type="text/javascript" language="javascript"></script>

<!--时时彩-->
<script type="text/html" id="content_ssc">
    {{each list value i}}
    <tr>
        <td class="issue">
            <!-- 输出期号 -->
            <div>{{value.issue}}</div>
        </td>

        <!-- 输出开奖号 -->
        {{each value.code codeItem}}
        <td align="center">
            <div class="ballnumb">
                <div class="wth">{{codeItem}}</div>
            </div>
        </td>
        {{/each}}
        <!-- 循环万千百十个位 -->
        <% for(var j = 0; j < value.code.length; ++j){ %>
        <!-- 循环每一位上的10个号 -->
        <% for(var i = 0; i < 10; ++i){ %>
        <!-- 判断第几列,单数列还是双数列 -->
        {{set rem = j%2}}
        <!-- 判断是否是开奖的号,是则输出圈的样式 -->
        <% if(value.code[j] == i){ %>
        <td align="center" class="charball">
            <div class="tenthousand">
                <!-- 根据单双数列判断是红色还是蓝色 -->
                <div class="ball0{{rem>0?2:1}}">{{value.code[j]}}</div>
            </div>
        </td>
        <% }else{ %>
        <td align="center" class="wdh">
            <div class="tenthousand">
                <div class="ball0{{rem>0?4:3}}"></div>
            </div>
        </td>
        <% } %>
        <% } %>
        <% } %>
    </tr>
    {{/each}}
</script>
<script type="text/html" id="head_ssc">
    <tr class="th">
        <td rowspan="2" width="6.5%">
            <div style="width:auto;">期号</div>
        </td>
        <td colspan="5" rowspan="2">开奖号码</td>
        <td colspan="10">万位</td>
        <td colspan="10">千位</td>
        <td colspan="10">百位</td>
        <td colspan="10">十位</td>
        <td colspan="10">个位</td>
    </tr>
    <tr class="th">
        <td class="wdh">0</td>
        <td class="wdh">1</td>
        <td class="wdh">2</td>
        <td class="wdh">3</td>
        <td class="wdh">4</td>
        <td class="wdh">5</td>
        <td class="wdh">6</td>
        <td class="wdh">7</td>
        <td class="wdh">8</td>
        <td class="wdh">9</td>
        <td class="wdh">0</td>
        <td class="wdh">1</td>
        <td class="wdh">2</td>
        <td class="wdh">3</td>
        <td class="wdh">4</td>
        <td class="wdh">5</td>
        <td class="wdh">6</td>
        <td class="wdh">7</td>
        <td class="wdh">8</td>
        <td class="wdh">9</td>
        <td class="wdh">0</td>
        <td class="wdh">1</td>
        <td class="wdh">2</td>
        <td class="wdh">3</td>
        <td class="wdh">4</td>
        <td class="wdh">5</td>
        <td class="wdh">6</td>
        <td class="wdh">7</td>
        <td class="wdh">8</td>
        <td class="wdh">9</td>
        <td class="wdh">0</td>
        <td class="wdh">1</td>
        <td class="wdh">2</td>
        <td class="wdh">3</td>
        <td class="wdh">4</td>
        <td class="wdh">5</td>
        <td class="wdh">6</td>
        <td class="wdh">7</td>
        <td class="wdh">8</td>
        <td class="wdh">9</td>
        <td class="wdh">0</td>
        <td class="wdh">1</td>
        <td class="wdh">2</td>
        <td class="wdh">3</td>
        <td class="wdh">4</td>
        <td class="wdh">5</td>
        <td class="wdh">6</td>
        <td class="wdh">7</td>
        <td class="wdh">8</td>
        <td class="wdh">9</td>
</script>
<script type="text/html" id="foot_ssc">
    <tr class="th">
        <td rowspan="2">
            <div>期号</div>
        </td>
        <td colspan="5" rowspan="2">开奖号码</td>
        <td class="wdh">0</td>
        <td class="wdh">1</td>
        <td class="wdh">2</td>
        <td class="wdh">3</td>
        <td class="wdh">4</td>
        <td class="wdh">5</td>
        <td class="wdh">6</td>
        <td class="wdh">7</td>
        <td class="wdh">8</td>
        <td class="wdh">9</td>
        <td class="wdh">0</td>
        <td class="wdh">1</td>
        <td class="wdh">2</td>
        <td class="wdh">3</td>
        <td class="wdh">4</td>
        <td class="wdh">5</td>
        <td class="wdh">6</td>
        <td class="wdh">7</td>
        <td class="wdh">8</td>
        <td class="wdh">9</td>
        <td class="wdh">0</td>
        <td class="wdh">1</td>
        <td class="wdh">2</td>
        <td class="wdh">3</td>
        <td class="wdh">4</td>
        <td class="wdh">5</td>
        <td class="wdh">6</td>
        <td class="wdh">7</td>
        <td class="wdh">8</td>
        <td class="wdh">9</td>
        <td class="wdh">0</td>
        <td class="wdh">1</td>
        <td class="wdh">2</td>
        <td class="wdh">3</td>
        <td class="wdh">4</td>
        <td class="wdh">5</td>
        <td class="wdh">6</td>
        <td class="wdh">7</td>
        <td class="wdh">8</td>
        <td class="wdh">9</td>
        <td class="wdh">0</td>
        <td class="wdh">1</td>
        <td class="wdh">2</td>
        <td class="wdh">3</td>
        <td class="wdh">4</td>
        <td class="wdh">5</td>
        <td class="wdh">6</td>
        <td class="wdh">7</td>
        <td class="wdh">8</td>
        <td class="wdh">9</td>
    </tr>
    <tr class="th">
        <td colspan="10">万位</td>
        <td colspan="10">千位</td>
        <td colspan="10">百位</td>
        <td colspan="10">十位</td>
        <td colspan="10">个位</td>
    </tr>
</script>
<!--3D模板-->
<script type="text/html" id="head_3D">
    <tr class="th">
        <td rowspan="2" width="6.5%">
            <div style="width:auto;">期号</div>
        </td>
        <td colspan="3" rowspan="2">开奖号码</td>
        <td colspan="10">百位</td>
        <td colspan="10">十位</td>
        <td colspan="10">个位</td>
    </tr>
    <tr class="th">
        <td class="wdh1">0</td>
        <td class="wdh">1</td>
        <td class="wdh">2</td>
        <td class="wdh">3</td>
        <td class="wdh">4</td>
        <td class="wdh">5</td>
        <td class="wdh">6</td>
        <td class="wdh">7</td>
        <td class="wdh">8</td>
        <td class="wdh">9</td>
        <td class="wdh">0</td>
        <td class="wdh">1</td>
        <td class="wdh">2</td>
        <td class="wdh">3</td>
        <td class="wdh">4</td>
        <td class="wdh">5</td>
        <td class="wdh">6</td>
        <td class="wdh">7</td>
        <td class="wdh">8</td>
        <td class="wdh">9</td>
        <td class="wdh">0</td>
        <td class="wdh">1</td>
        <td class="wdh">2</td>
        <td class="wdh">3</td>
        <td class="wdh">4</td>
        <td class="wdh">5</td>
        <td class="wdh">6</td>
        <td class="wdh">7</td>
        <td class="wdh">8</td>
        <td class="wdh">9</td>
    </tr>
</script>
<script type="text/html" id="foot_3D">
    <tr class="th">
        <td rowspan="2">
            <div>期号</div>
        </td>
        <td colspan="3" rowspan="2">开奖号码</td>
        <td class="wdh">0</td>
        <td class="wdh">1</td>
        <td class="wdh">2</td>
        <td class="wdh">3</td>
        <td class="wdh">4</td>
        <td class="wdh">5</td>
        <td class="wdh">6</td>
        <td class="wdh">7</td>
        <td class="wdh">8</td>
        <td class="wdh">9</td>
        <td class="wdh">0</td>
        <td class="wdh">1</td>
        <td class="wdh">2</td>
        <td class="wdh">3</td>
        <td class="wdh">4</td>
        <td class="wdh">5</td>
        <td class="wdh">6</td>
        <td class="wdh">7</td>
        <td class="wdh">8</td>
        <td class="wdh">9</td>
        <td class="wdh">0</td>
        <td class="wdh">1</td>
        <td class="wdh">2</td>
        <td class="wdh">3</td>
        <td class="wdh">4</td>
        <td class="wdh">5</td>
        <td class="wdh">6</td>
        <td class="wdh">7</td>
        <td class="wdh">8</td>
        <td class="wdh">9</td>
    </tr>
    <tr class="th">
        <td colspan="10">百位</td>
        <td colspan="10">十位</td>
        <td colspan="10">个位</td>
    </tr>
</script>
<!--北京Pk拾-->
<script type="text/html" id="head_pks">
    <tr class="th">
        <td rowspan="2" width="6.5%">
            <div style="width:auto;">期号</div>
        </td>
        <td colspan="10" rowspan="2">开奖号码</td>
        <td colspan="10">冠军</td>
        <td colspan="10">亚军</td>
        <td colspan="10">三名</td>
        <td colspan="10">四名</td>
        <td colspan="10">五名</td>
        <td colspan="10">六名</td>
        <td colspan="10">七名</td>
        <td colspan="10">八名</td>
        <td colspan="10">九名</td>
        <td colspan="10">十名</td>
    </tr>
    <tr class="th">
        <td class="wdh">01</td>
        <td class="wdh">02</td>
        <td class="wdh">03</td>
        <td class="wdh">04</td>
        <td class="wdh">05</td>
        <td class="wdh">06</td>
        <td class="wdh">07</td>
        <td class="wdh">08</td>
        <td class="wdh">09</td>
        <td class="wdh">10</td>
        <td class="wdh">01</td>
        <td class="wdh">02</td>
        <td class="wdh">03</td>
        <td class="wdh">04</td>
        <td class="wdh">05</td>
        <td class="wdh">06</td>
        <td class="wdh">07</td>
        <td class="wdh">08</td>
        <td class="wdh">09</td>
        <td class="wdh">10</td>
        <td class="wdh">01</td>
        <td class="wdh">02</td>
        <td class="wdh">03</td>
        <td class="wdh">04</td>
        <td class="wdh">05</td>
        <td class="wdh">06</td>
        <td class="wdh">07</td>
        <td class="wdh">08</td>
        <td class="wdh">09</td>
        <td class="wdh">10</td>
        <td class="wdh">01</td>
        <td class="wdh">02</td>
        <td class="wdh">03</td>
        <td class="wdh">04</td>
        <td class="wdh">05</td>
        <td class="wdh">06</td>
        <td class="wdh">07</td>
        <td class="wdh">08</td>
        <td class="wdh">09</td>
        <td class="wdh">10</td>
        <td class="wdh">01</td>
        <td class="wdh">02</td>
        <td class="wdh">03</td>
        <td class="wdh">04</td>
        <td class="wdh">05</td>
        <td class="wdh">06</td>
        <td class="wdh">07</td>
        <td class="wdh">08</td>
        <td class="wdh">09</td>
        <td class="wdh">10</td>
        <td class="wdh">01</td>
        <td class="wdh">02</td>
        <td class="wdh">03</td>
        <td class="wdh">04</td>
        <td class="wdh">05</td>
        <td class="wdh">06</td>
        <td class="wdh">07</td>
        <td class="wdh">08</td>
        <td class="wdh">09</td>
        <td class="wdh">10</td>
        <td class="wdh">01</td>
        <td class="wdh">02</td>
        <td class="wdh">03</td>
        <td class="wdh">04</td>
        <td class="wdh">05</td>
        <td class="wdh">06</td>
        <td class="wdh">07</td>
        <td class="wdh">08</td>
        <td class="wdh">09</td>
        <td class="wdh">10</td>
        <td class="wdh">01</td>
        <td class="wdh">02</td>
        <td class="wdh">03</td>
        <td class="wdh">04</td>
        <td class="wdh">05</td>
        <td class="wdh">06</td>
        <td class="wdh">07</td>
        <td class="wdh">08</td>
        <td class="wdh">09</td>
        <td class="wdh">10</td>
        <td class="wdh">01</td>
        <td class="wdh">02</td>
        <td class="wdh">03</td>
        <td class="wdh">04</td>
        <td class="wdh">05</td>
        <td class="wdh">06</td>
        <td class="wdh">07</td>
        <td class="wdh">08</td>
        <td class="wdh">09</td>
        <td class="wdh">10</td>
        <td class="wdh">01</td>
        <td class="wdh">02</td>
        <td class="wdh">03</td>
        <td class="wdh">04</td>
        <td class="wdh">05</td>
        <td class="wdh">06</td>
        <td class="wdh">07</td>
        <td class="wdh">08</td>
        <td class="wdh">09</td>
        <td class="wdh">10</td>
    </tr>
</script>
<script type="text/html" id="content_pks">
    {{each list value i}}
    <tr>
        <td class="issue">
            <!--输出奖期-->
            <div>{{value.issue}}</div>
        </td>
        <!--循环奖号-->
        {{each value.code codeItem}}
        <td align="center">
            <div class="ballnumb">
                <div class="wth">{{codeItem}}</div>
            </div>
        </td>
        {{/each}}

        <!--循环冠军亚军三四五六名-->
        <% for(var j=0; j< 10; ++j) { %>
        <!--循环每一名上的10个号码-->
        <% for(var i = 1; i< 11; ++i ) { %>
        <!--判断第几列，是单数列还是双数列-->
        {{set rem =j%2 }}
        <!--判断是否为开奖号码，如果是则输出的带有样式的开奖号-->
        <% if(value.code[j] == i) { %>
        <td align="center" class="charball">
            <div class="tenthousand">
                <div class="ball0{{rem>0?2:1}}">{{value.code[j]}}</div>
            </div>
        </td>
        <% } else{ %>
        <td align="center" class="wdh">
            <div class="tenthousand">
                <div class="ball0{{rem>0?4:3}}"></div>
            </div>
        </td>
        <% } %>
        <% } %>
        <% } %>
    </tr>
    {{/each}}
</script>
<script type="text/html" id="foot_pks">
    <tr class="th">
        <td rowspan="2">
            <div>期号</div>
        </td>
        <td colspan="10" rowspan="2">开奖号码</td>
        <td class="wdh">01</td>
        <td class="wdh">02</td>
        <td class="wdh">03</td>
        <td class="wdh">04</td>
        <td class="wdh">05</td>
        <td class="wdh">06</td>
        <td class="wdh">07</td>
        <td class="wdh">08</td>
        <td class="wdh">09</td>
        <td class="wdh">10</td>
        <td class="wdh">01</td>
        <td class="wdh">02</td>
        <td class="wdh">03</td>
        <td class="wdh">04</td>
        <td class="wdh">05</td>
        <td class="wdh">06</td>
        <td class="wdh">07</td>
        <td class="wdh">08</td>
        <td class="wdh">09</td>
        <td class="wdh">10</td>
        <td class="wdh">01</td>
        <td class="wdh">02</td>
        <td class="wdh">03</td>
        <td class="wdh">04</td>
        <td class="wdh">05</td>
        <td class="wdh">06</td>
        <td class="wdh">07</td>
        <td class="wdh">08</td>
        <td class="wdh">09</td>
        <td class="wdh">10</td>
        <td class="wdh">01</td>
        <td class="wdh">02</td>
        <td class="wdh">03</td>
        <td class="wdh">04</td>
        <td class="wdh">05</td>
        <td class="wdh">06</td>
        <td class="wdh">07</td>
        <td class="wdh">08</td>
        <td class="wdh">09</td>
        <td class="wdh">10</td>
        <td class="wdh">01</td>
        <td class="wdh">02</td>
        <td class="wdh">03</td>
        <td class="wdh">04</td>
        <td class="wdh">05</td>
        <td class="wdh">06</td>
        <td class="wdh">07</td>
        <td class="wdh">08</td>
        <td class="wdh">09</td>
        <td class="wdh">10</td>
        <td class="wdh">01</td>
        <td class="wdh">02</td>
        <td class="wdh">03</td>
        <td class="wdh">04</td>
        <td class="wdh">05</td>
        <td class="wdh">06</td>
        <td class="wdh">07</td>
        <td class="wdh">08</td>
        <td class="wdh">09</td>
        <td class="wdh">10</td>
        <td class="wdh">01</td>
        <td class="wdh">02</td>
        <td class="wdh">03</td>
        <td class="wdh">04</td>
        <td class="wdh">05</td>
        <td class="wdh">06</td>
        <td class="wdh">07</td>
        <td class="wdh">08</td>
        <td class="wdh">09</td>
        <td class="wdh">10</td>
        <td class="wdh">01</td>
        <td class="wdh">02</td>
        <td class="wdh">03</td>
        <td class="wdh">04</td>
        <td class="wdh">05</td>
        <td class="wdh">06</td>
        <td class="wdh">07</td>
        <td class="wdh">08</td>
        <td class="wdh">09</td>
        <td class="wdh">10</td>
        <td class="wdh">01</td>
        <td class="wdh">02</td>
        <td class="wdh">03</td>
        <td class="wdh">04</td>
        <td class="wdh">05</td>
        <td class="wdh">06</td>
        <td class="wdh">07</td>
        <td class="wdh">08</td>
        <td class="wdh">09</td>
        <td class="wdh">10</td>
        <td class="wdh">01</td>
        <td class="wdh">02</td>
        <td class="wdh">03</td>
        <td class="wdh">04</td>
        <td class="wdh">05</td>
        <td class="wdh">06</td>
        <td class="wdh">07</td>
        <td class="wdh">08</td>
        <td class="wdh">09</td>
        <td class="wdh">10</td>
    </tr>
    <tr class="th">
        <td colspan="10">冠军</td>
        <td colspan="10">亚军</td>
        <td colspan="10">三名</td>
        <td colspan="10">四名</td>
        <td colspan="10">五名</td>
        <td colspan="10">六名</td>
        <td colspan="10">七名</td>
        <td colspan="10">八名</td>
        <td colspan="10">九名</td>
        <td colspan="10">十名</td>
    </tr>
</script>
<!--11选5-->
<script type="text/html" id="head_115">
    <tr class="th">
        <td rowspan="2" width="6.5%">
            <div style="width:auto;">期号</div>
        </td>
        <td colspan="5" rowspan="2">开奖号码</td>
        <td colspan="11">万位</td>
        <td colspan="11">千位</td>
        <td colspan="11">百位</td>
        <td colspan="11">十位</td>
        <td colspan="11">个位</td>
    </tr>
    <tr class="th">
        <% for(var i= 0; i< 5; ++i) { %>
        <td class="wdh">01</td>
        <td class="wdh">02</td>
        <td class="wdh">03</td>
        <td class="wdh">04</td>
        <td class="wdh">05</td>
        <td class="wdh">06</td>
        <td class="wdh">07</td>
        <td class="wdh">08</td>
        <td class="wdh">09</td>
        <td class="wdh">10</td>
        <td class="wdh">11</td>
        <% } %>

    </tr>
</script>
<script type="text/html" id="foot_115">
    <tr class="th">
        <td rowspan="2">
            <div>期号</div>
        </td>
        <td colspan="5" rowspan="2">开奖号码</td>
        <% for(var i= 0; i< 5; ++i) { %>
        <td class="wdh">01</td>
        <td class="wdh">02</td>
        <td class="wdh">03</td>
        <td class="wdh">04</td>
        <td class="wdh">05</td>
        <td class="wdh">06</td>
        <td class="wdh">07</td>
        <td class="wdh">08</td>
        <td class="wdh">09</td>
        <td class="wdh">10</td>
        <td class="wdh">11</td>
        <% } %>

    </tr>
    <tr class="th">
        <td colspan="11">万位</td>
        <td colspan="11">千位</td>
        <td colspan="11">百位</td>
        <td colspan="11">十位</td>
        <td colspan="11">个位</td>
    </tr>
</script>
<script type="text/html" id="content_115">
    {{each list value i}}
    <tr>
        <td class="issue">
            <!-- 输出期号 -->
            <div>{{value.issue}}</div>
        </td>
        <!-- 输出开奖号 -->
        {{each value.code codeItem}}
        <td align="center">
            <div class="ballnumb">
                <div class="wth">{{codeItem}}</div>
            </div>
        </td>
        {{/each}}
        <!--循环个十百千万位数-->
        <% for(var j=0; j< 5; ++j) { %>
        <!--循环1-11的数字-->
        <% for (var i=1; i<= 11; ++i) { %>
        <!--判断是第几列，是奇数列还是偶数列-->
        {{set rem = j%2}}
        <!--判断开奖号是否在1-11的数字上，如果是则输出带样式的球号-->
        <% if(value.code[j] == i) { %>
        <td align="center" class="charball">
            <div class="tenthousand">
                <!-- 根据单双数列判断是红色还是蓝色 -->
                <div class="ball0{{rem>0?2:1}}">{{value.code[j]}}</div>
            </div>
        </td>
        <% } else { %>
        <td align="center" class="wdh">
            <div class="tenthousand">
                <div class="ball0{{rem>0?4:3}}"></div>
            </div>
        </td>
        <% } %>
        <% } %>
        <% } %>
    </tr>
    {{/each}}
</script>
</html>