<!DOCTYPE HTML> <!-- 追号详情页面 -->
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="webkit" name="renderer">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title><?php echo config::getConfig('site_title'); ?></title>
        <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/all_LightBlue.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/global_reset.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/common_operate.css" />
    </head>

    <body>
      <div id="orderDetailsLayer" class="order_details_layer">
       <table class="order_summary_cont">
           <caption>追号单摘要</caption>
           <colgroup>
              <col width="60px">
              <col width="412px">
              <col>
           </colgroup>
           <tbody>
               <tr class="five_height">
                    <td colspan="3">&nbsp;</td>
               </tr>
               <tr>
                   <td>&nbsp;</td>
                   <td>游戏：<?php echo $lottery['cname']; ?></td>
                   <td>模式：<?php echo $GLOBALS['cfg']['modes'][strval(floatval($trace['modes']))];?></td>
               </tr>
               <tr>
                   <td>&nbsp;</td>
                   <td>单倍注数：<?php echo $trace['single_num']; ?></td>
                   <td>总追号倍数：<?php echo $trace['total_multiple']; ?></td>
               </tr>
               <tr>
                   <td>&nbsp;</td>
                   <td>计划追号期数：<?php echo $trace['trace_times']; ?></td>
                   <td>计划总金额：<span class="orange_font"><?php echo $trace['total_amount']; ?></span></td>
               </tr>
               <tr>
                   <td>&nbsp;</td>
                   <td>奖金系列：<?php echo $prizeMode; ?>系列</td>
                   <td>中奖即停止：<?php if ($trace['stop_on_win']) echo '是'; else echo '否'; ?></td>
               </tr>
               <tr>
                   <td>&nbsp;</td>
                   <td>追号状态：
                       <?php if ($trace['status'] == 0): ?>未开始
                       <?php else: ?>
                           <?php if ($trace['status'] == 1): ?>正在进行
                           <?php elseif ($trace['status'] == 2): ?>已完成
                           <?php elseif ($trace['status'] == 3): ?>已取消
                           <?php endif; ?>
                       <?php endif; ?>
                   </td>
                   <td>投注时间：<?php echo $trace['create_time']; ?></td>
               </tr>
                <tr class="five_height">
                    <td colspan="3">&nbsp;</td>
                </tr>
           </tbody>
       </table>
       <table class="order_details_cont">
               <caption>订单明细</caption>
                <thead>
                    <tr>
                        <th width="16%">玩法名称</th>
                        <th width="26%">投注内容</th>
                        <th width="19%">投注注数</th>
                        <th width="20%">单倍金额</th>
                        <th width="21%">单倍奖金</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($projects as $v): ?>
                    <tr>
                        <td><?php echo $methods[$v['method_id']]['cname']; ?></td>
                        <td><label class="textarea"><?php echo $v['code']; ?></label></td>
                        <td><?php echo $v['single_num']; ?></td>
                        <td><span class="orange_font"><?php echo number_format($v['amount']/$v['multiple'], 3); ?></span></td>
                        <td><?php echo $v['will_prize']; ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
       </table>
          <table class="order_details_cont orderDetailsCont">
               <caption>各期追号详情</caption>
                <thead>
                    <tr>
                        <th width="8%">操作</th>
                        <th width="16%">追号期号</th>
                        <th>开奖号码</th>
                        <th width="13%">当期倍数</th>
                        <th width="10%">投注金额</th>
                        <th width="15%">中奖金额</th>
                        <th width="13%">订单状态</th>
                    </tr>
                </thead>
                <tbody>
                      <?php foreach ($packages as $v): ?>
                          <tr>
                              <td>
                                  <?php if ($isSelf): ?>
                                      <?php if ($issueInfos[$v['issue']]['end_sale_time'] > $nowTime && $v['cancel_status'] == 0): ?>
                                          <input type="checkbox" name="pkids[]" value="<?php echo $v['package_id']; ?>"/>
                                      <?php endif; ?>
                                  <?php endif; ?>
                              </td>
                              <td><?php echo $v['issue']; ?></td>
                              <td>
                                  <?php if (isset($openCodes[$v['issue']])): ?>
                                      <?php if ($lottery['lottery_id'] == 14): ?>
                                          <?php foreach ($openCodes[$v['issue']] as $code): ?>
                                              <span class="poker_kj_num <?php echo $code['suit']; ?>"><em><?php echo $code['num']; ?></em></span>
                                          <?php endforeach; ?>
                                      <?php else: ?>
                                          <?php echo $openCodes[$v['issue']]; ?>
                                      <?php endif; ?>
                                  <?php else: ?> &nbsp; <?php endif; ?>
                              </td>
                              <td><?php echo $v['multiple']; ?></td>
                              <td><?php echo $v['amount']; ?></td>
                              <td><?php echo $v['prize']; ?></td>
                              <td>
                                    <span class="orange_font">
                                    <?php if ($v['cancel_status'] > 0): ?>
                                        <?php if ($v['cancel_status'] == 1): ?>个人撤单
                                        <?php elseif ($v['cancel_status'] == 2): ?>追中撤单
                                        <?php elseif ($v['cancel_status'] == 3): ?>出号撤单
                                        <?php elseif ($v['cancel_status'] == 4): ?>未开撤单
                                        <?php elseif ($v['cancel_status'] == 9): ?>公司撤单
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <?php if ($v['check_prize_status'] == 0): ?>未开奖
                                        <?php elseif ($v['check_prize_status'] == 1): ?>已中奖
                                        <?php else: ?><font style=" color:#f00;">未中奖</font>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    </span>
                              </td>
                          </tr>
                      <?php endforeach; ?>

                </tbody>
          </table>
          <div class="close_order_layer">
              <input type="button" id="buttonCanle" class="cancellation_btn" name="cancel" style="display:none" value="撤单"/>
              <a href="javascript:void(0);" class="default_blue_btn closeDialogBtn">返回</a>
          </div>


</div>

   <script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/jquery-1.8.3.min.js"></script>
    <script>
    $(function() {
      if($('.textarea').text().length >= 30){
        $('.textarea').addClass('are');
      }else{
        $('.textarea').removeClass('are');
      }
      $('a.closeDialogBtn').on('click', function(){
            var index = parent.layer.getFrameIndex(window.name);      //获取当前窗口索引
            parent.layer.close(index);
        });

        $('input:checkbox').click(function(){
            var pt = this;
            $.each($(this).parent().parent().nextAll(), function(k,v){
                $(this).find(':checkbox').attr('checked', $(pt).attr('checked'));
            });
        });

        if ($('input:checkbox').length > 0) {
            $('input[name=cancel]').css('display', '');
        }
        else {
            //$('input[name=cancel]').remove();
        }

        $('#buttonCanle').click(function(){
          var pkids = [],
              that = this;
          $("table.orderDetailsCont input:checkbox:checked").each(function(i,item){
              pkids.push($(this).val());
          });
          if(pkids.length < 1){
            parent.layer.alert('请选择您要撤单的期数',{icon:7});
            return false;
          }

          parent.layer.confirm('您真的要撤单吗？',{icon:7},function(i) {
            $.post(
                'index.jsp?c=game&a=cancelTrace',
                {
                    'wrap_id': '<?php echo $trace['wrap_id']; ?>',
                    'pkids': pkids,
                },
                function(response){
                    if(response.errno　== 0){
                      //投注记录页
                      if(pkids.length == $('input:checkbox').length){
                          var wrap_id = '<?php echo $trace['wrap_id']; ?>';
                          $(window.top.document).find(".MainIframe").contents().find("input[name="+wrap_id+"]").hide();
                          $(window.top.document).find(".MainIframe").contents().find("#status_"+wrap_id).html('已取消');
                      }
                      parent.layer.alert(response.errstr,{icon:1});
                      window.location.reload();
                    } else {
                      parent.layer.alert(response.errstr,{icon:3});
                    }
                }, 'json');
            });
        });
    });
</script>
    </body>
</html>