<!DOCTYPE HTML> <!-- 追号记录 -->
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="webkit" name="renderer">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title><?php echo config::getConfig('site_title'); ?></title>
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/all_LightBlue.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/global_reset.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/common_operate.css" />
    <?php $this->import('public_cssjs') ?>

</head>

<body>
<!-- 顶部导航信息部分 -->
<?php $this->import('public_header') ?>
<!-- End 顶部导航条 -->
<div class="operate_middle_page">
    <?php $this->import("public_usermenu"); ?>

    <div class="common_pages default_operate_pageheight">
        <div class="default_record_search">
            <form method="get" action="" id="form1" name="form1">
                <ul>
                    <li>
                        <label class="search_record_gamelab">游戏：</label>
                        <select class="default_common_input" name="lottery_id">
                            <option value="0">请选择</option>
                            <?php foreach ($lotterys as $v): ?>
                                <option value="<?php echo $v['lottery_id']; ?>"><?php echo $v['cname']; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </li>
                    <li>
                        <label class="search_record_datelab">时间：</label>
                        <div class="record_date_range">
                            <input class="default_common_input datepicker85" onfocus="WdatePicker({dateFmt: 'yyyy-MM-dd'})" my97mark="false" id="start_time" name="startDate" size="16" value="<?php echo $startDate; ?>">
                            <em>到</em>
                            <input class="default_common_input datepicker85" onfocus="WdatePicker({dateFmt: 'yyyy-MM-dd'})" my97mark="false" id="end_time" name="endDate" size="16" value="<?php echo $endDate; ?>">
                        </div>
                    </li>
                    <li>
                        <label class="search_record_statuslab">状态：</label>
                        <select class="default_common_input" name="status">
                            <option value="-1">请选择</option>
                            <option value="0">未开始</option>
                            <option value="1">正在进行</option>
                            <option value="2">已完成</option>
                            <option value="3">已取消</option>
                        </select>
                    </li>
                    <li>
                        <input type="submit" value="搜索" class="default_record_searchbtn" name="submit">
                    </li>
                    <li class="float_right">
                        <!-- 分页 -->
                        <div class="user-page-boxs">
                            <?php echo $pageList; ?>
                        </div>
                        <!-- 分页end -->
                    </li>
                </ul>
                <input type="hidden" name="c" value="game"/>
                <input type="hidden" name="a" value="<?php echo ACTION; ?>"/>
            </form>
        </div>
        <!-- 列表数据 -->
        <form name="form2" id="form2" action="" method="GET">
            <table class="defoperate_record_tablist">
                <thead>
                <tr class="defoperate_record_tabtitle">
                    <th width="16%">追号编号</th>
                    <th>投注时间</th>
                    <th>游戏类别</th>
                    <th>开始期号</th>
                    <th>追号期数</th>
                    <th>总金额</th>
                    <th>完成期数</th>
                    <th>追号即停</th>
                    <th>追号状态</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                <?php if ($traces): ?>
                    <?php foreach ($traces as $v): ?>
                        <tr>
                            <td><a class="orderNumberBtn blue_font_href" href="javascript:;"><?php echo $v['wrap_id']; ?></a></td>
                            <td><?php echo date("m/d H:i:s", strtotime($v['create_time'])); ?></td>
                            <td><?php echo $lotterys[$v['lottery_id']]['cname']; ?></td>
                            <td><?php echo $v['start_issue']; ?></td>
                            <td><?php echo $v['trace_times']; ?></td>
                            <td><?php echo $v['total_amount']; ?>元</td>
                            <td><?php echo $v['finish_times']; ?></td>
                            <td><?php if ($v['stop_on_win'] == 0): ?><font color="red">否</font><?php elseif ($v['stop_on_win'] == 1): ?>是<?php endif; ?></td>
                            <td id="status_<?php echo $v['wrap_id']; ?>"><?php if ($v['status'] == 0): ?>未开始<?php elseif ($v['status'] == 1): ?>正在进行<?php elseif ($v['status'] == 2): ?>已完成<?php elseif ($v['status'] == 3): ?>已取消<?php endif; ?></td>
                            <td>
                                <?php if ($v['show_cancel']): ?>
                                    <input type="button" class="blue_font_href buttonCanle" name="<?php echo $v['wrap_id']; ?>" value="撤单" />
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <th colspan="10" class="text_center">暂无数据显示</th>
                    </tr>
                <?php endif; ?>
                </tbody>
            </table>
            <input type="hidden" name="c" value="game"/>
            <input type="hidden" name="a" value="traceDetail"/>
            <input type="hidden" name="wrap_id" value=""/>
        </form>
    </div>

    <!-- 页面统计 -->
    <?php $this->import("common_operate_count"); ?>
</div>
<?php $this->import('public_foot') ?>
<script src="<?php echo $imgCdnUrl ?>/js/common.js" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/jquery.plugin.js"></script><!--jquery小插件-->
<script src="js/My97DatePicker/WdatePicker.js"></script>
<script>
    $(function() {
        //准备数据
        //设置默认值
        $('select[name=lottery_id]').val('<?php echo $lottery_id; ?>').change();
        $('select[name=status]').val('<?php echo $status; ?>').change();
        $('select[name=modes]').val('<?php echo $modes; ?>');
        $('input[name=wrap_id]').val('<?php echo $wrap_id; ?>');
        $('.recordsContent a').click(function() {
            $('input[name=wrap_id]').val($(this).text());
            $('#form2').attr('target', '_blank').submit();
        });

        $('a.orderNumberBtn').on('click', function(){
          parent.layer.open({
                type: 2,
                shadeClose: true,
                title: '追号编号：'+$(this).text(),
                closeBtn: false,
                shade: [0.3, '#000'],
                border: [0],
                area: ['824px','590px'],
                content: ['index.jsp?c=game&a=traceDetail&wrap_id='+$(this).text()]
            });
            $('div.xubox_title').addClass('layui-layer-title');
        });

        $('.buttonCanle').click(function(){
          var obj = $(this),
              name = obj.attr('name');
          parent.layer.confirm('您真的要撤单吗？',{icon:7},function(i) {
            $.post(
                'index.jsp?c=game&a=cancelAllTrace',
                {
                    'wrap_id': name
                },
                function(response){
                    if(response.errno　== 0){
                        obj.hide();
                        obj.parent().prev().html('已取消');
                    }
                    parent.layer.alert(response.errstr,{icon:1});
                }, 'json').error(function(msg) { console.log(msg); });
          });
        });
    });
</script>
</body>
</html>