<!DOCTYPE html>
<html>
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="webkit" name="renderer">
<title><?php echo config::getConfig('site_title'); ?></title>
<meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
<meta content="no-cache" http-equiv="Pragma">
<link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/global_reset.css" />
<script src="<?php echo $imgCdnUrl ?>/js/jquery.js" type="text/javascript"></script>
<link href="css/chart.css" rel="stylesheet" type="text/css" />
</head>
    <body>
        <div id="rightcon">
	<div style="display:none;" class="win_bot" id="msgbox">
		<h5 id="msgtitle"></h5>
 		<div class="clear"></div>
		<div class="wb_con">
			<p id="msgcontent"></p>
		</div>
		<div class="clear"></div>
		<a id="msgpre" onClick="javascript:prenotice();" href="#" class="wb_p">上一条</a><a onClick="javascript:nextnotice();" href="#" class="wb_n">下一条</a> </div>
	<script language="javascript">
</script>
	<style>
    esun\:*{behavior:url(#default#VML)}
</style>
	<div class="rc_con history">
		<div class="rc_con_lt"></div>
		<div class="rc_con_rt"></div>
		<div class="rc_con_lb"></div>
		<div class="rc_con_rb"></div>
		<div class="rc_con_to">
			<div class="rc_con_ti">
				<div class="history_code" >
					<table width="100%" border="0" cellspacing="0" cellpadding="0" id="tm">
						<tbody>
							<tr>
								<td width="300" align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong> <font><?php  echo $lottery['cname'];?>：</font> 基本走势 </strong></td>
								<td align="right">
									<div class="Tabfixed">
										<form method="POST">
											<span>
											<label for="has_miss">
												<input type="checkbox" checked="checked" id="has_miss" name="checkbox">
												显示遗漏分层
											</label>
											<label for="no_miss">
												<input type="checkbox" id="no_miss" value="checkbox" name="checkbox">
												不带遗漏</label>&nbsp;&nbsp;&nbsp;&nbsp;
										    <!-- <label for="no_miss"> 显示期数：
												<select name='issueNum' id='issueNum'>
												<option value='50' <?php echo ($issueNum == 50) ? 'selected' : ''; ?> >50 &nbsp;&nbsp;期</option>
												<option value='100' <?php echo ($issueNum == 100) ? 'selected' : ''; ?> >100 期</option>
												<option value='200' <?php echo ($issueNum == 200) ? 'selected' : ''; ?> >200 期</option>
												</select>
											</label> -->
											</span>
										</form>
									</div>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
				<div class="hrc_list">
					<div class="hrl_list">
						<table border="0" cellspacing="1" cellpadding="0" id="chartsTable">
							<tbody>
							</tbody>
						</table>
					</div>
				</div>
				<div class="clear"></div>
			</div>
		</div>
	</div>
</div>
<div class="layer"></div>
</body>
<script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/template-web.js"></script>
<script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/game_chart.js"></script>
<script type="text/html" id="content_ssq">
    {{each list value i}}
    <tr>
        <td class="issue">
            <!-- 输出期号 -->
            <div>{{value.issue}}</div>
        </td>

        <!-- 输出开奖号 -->
        {{each value.code codeItem}}
        <td align="center">
            <div class="ballnumb">
                <div class="wth">{{codeItem}}</div>
            </div>
        </td>
        {{/each}}

        <!--循环双色球1-33个号码-->
        <% for(var i=1; i<=33; ++i) { %>
        	<!--定义变量-->
        	<% var flag = 1 %>
        	<!--循环前6个红球-->
        	<% for(var j = 0;j < 6; ++j ) { %>
        		<!--判断是否为开奖号，如果是则输出带样式的球-->
    			<% if(value.code[j] ==i) { %>
				<td align="center" class="charball">
                	<div class="tenthousand">
                   		 <div class="ball01">{{value.code[j]}}</div>
                	</div>
                </td>
                <% var flag  = 0 %>
    			<% } %>
        	<% } %>
        	<% if(flag ==1) { %>
        		<td align="center" class="wdh">
                    <div class="tenthousand">
                        <div class="ball03"></div>
                    </div>
                </td>
        	<% } %>
        <% } %>
        <!--循环双色球的1-16个篮球的号码-->
        <% for(var i=1; i<=16; ++i) { %>
        	<!--判断1-16个号码里是否有双色球的最后一个球，index为6-->
        	<% if(value.code[6] == i) { %>
        		<td align="center" class="charball">
                    <div class="tenthousand">
                        <div class="ball02">{{value.code[6]}}</div>
                    </div>
                </td>
        	<% } else { %>
        		 <td align="center" class="wdh">
                    <div class="tenthousand">
                        <div class="ball04 m"></div>
                    </div>
                </td>
        	<% } %>
        <% } %>
    </tr>
    {{/each}}
</script>

<script type="text/html" id="head_ssq">
    <tr class="th">
		<td rowspan="2" width="6.5%"><div style="width:auto;">期号</div></td>
		<td colspan="6" rowspan="2">红球</td>
		<td colspan="1" rowspan="2">蓝球</td>
		<td colspan="33">红球区</td>
		<td colspan="16">蓝球区</td>
	</tr>
    <tr class="th">
		<td class="wdh">01</td>
		<td class="wdh">02</td>
		<td class="wdh">03</td>
		<td class="wdh">04</td>
		<td class="wdh">05</td>
		<td class="wdh">06</td>
		<td class="wdh">07</td>
		<td class="wdh">08</td>
		<td class="wdh">09</td>
		<td class="wdh">10</td>
		<td class="wdh">11</td>
		<td class="wdh">12</td>
		<td class="wdh">13</td>
		<td class="wdh">14</td>
		<td class="wdh">15</td>
		<td class="wdh">16</td>
		<td class="wdh">17</td>
		<td class="wdh">18</td>
		<td class="wdh">19</td>
		<td class="wdh">20</td>
		<td class="wdh">21</td>
		<td class="wdh">22</td>
		<td class="wdh">23</td>
		<td class="wdh">24</td>
		<td class="wdh">25</td>
		<td class="wdh">26</td>
		<td class="wdh">27</td>
		<td class="wdh">28</td>
		<td class="wdh">29</td>
		<td class="wdh">30</td>
		<td class="wdh">31</td>
		<td class="wdh">32</td>
		<td class="wdh">33</td>
		<td class="wdh">01</td>
		<td class="wdh">02</td>
		<td class="wdh">03</td>
		<td class="wdh">04</td>
		<td class="wdh">05</td>
		<td class="wdh">06</td>
		<td class="wdh">07</td>
		<td class="wdh">08</td>
		<td class="wdh">09</td>
		<td class="wdh">10</td>
		<td class="wdh">11</td>
		<td class="wdh">12</td>
		<td class="wdh">13</td>
		<td class="wdh">14</td>
		<td class="wdh">15</td>
		<td class="wdh">16</td>
	</tr>              
</script>


<script type="text/html" id="foot_ssq">
   	<tr class="th">
		<td rowspan="2"><div>期号</div></td>
		<td colspan="6" rowspan="2">红球</td>
		<td colspan="1" rowspan="2">蓝球</td>
		<td class="wdh">01</td>
		<td class="wdh">02</td>
		<td class="wdh">03</td>
		<td class="wdh">04</td>
		<td class="wdh">05</td>
		<td class="wdh">06</td>
		<td class="wdh">07</td>
		<td class="wdh">08</td>
		<td class="wdh">09</td>
		<td class="wdh">10</td>
		<td class="wdh">11</td>
		<td class="wdh">12</td>
		<td class="wdh">13</td>
		<td class="wdh">14</td>
		<td class="wdh">15</td>
		<td class="wdh">16</td>
		<td class="wdh">17</td>
		<td class="wdh">18</td>
		<td class="wdh">19</td>
		<td class="wdh">20</td>
		<td class="wdh">21</td>
		<td class="wdh">22</td>
		<td class="wdh">23</td>
		<td class="wdh">24</td>
		<td class="wdh">25</td>
		<td class="wdh">26</td>
		<td class="wdh">27</td>
		<td class="wdh">28</td>
		<td class="wdh">29</td>
		<td class="wdh">30</td>
		<td class="wdh">31</td>
		<td class="wdh">32</td>
		<td class="wdh">33</td>
		<td class="wdh">01</td>										
		<td class="wdh">02</td>
		<td class="wdh">03</td>
		<td class="wdh">04</td>
		<td class="wdh">05</td>
		<td class="wdh">06</td>
		<td class="wdh">07</td>
		<td class="wdh">08</td>
		<td class="wdh">09</td>
		<td class="wdh">10</td>
		<td class="wdh">11</td>
		<td class="wdh">12</td>
		<td class="wdh">13</td>
		<td class="wdh">14</td>
		<td class="wdh">15</td>
		<td class="wdh">16</td>
	</tr>
	<tr class="th">
		<td colspan="33">红球区</td>
		<td colspan="16">蓝球区</td>
	</tr>
</script>
</html>
