<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="webkit" name="renderer">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>跳转中</title>
</head>
<body onLoad="document.diy.submit();">
<form name='diy' id="diy" action='<?php echo $postFields['url']; ?>' method='post'>
    <input type='hidden' name='userid' value='<?php echo $postFields['userid']; ?>'>
    <input type='hidden' name='orderid' value='<?php echo $postFields['orderid']; ?>'>
    <input type='hidden' name='price' value='<?php echo  $postFields['price']; ?>'>
    <input type='hidden' name='payvia' value='<?php echo $postFields['payvia']; ?>'>
    <input type='hidden' name='notify' value='<?php echo $postFields['notify']; ?>'>
    <input type='hidden' name='callback' value='<?php echo $postFields['callback']; ?>'>
    <input type='hidden' name='timespan' value='<?php echo $postFields['timespan']; ?>'>
    <input type='hidden' name='custom' value='<?php echo $postFields['custom']; ?>'>
    <input type='hidden' name='format' value='<?php echo $postFields['format']; ?>'>
    <input type='hidden' name='sign' value='<?php echo $postFields['sign']; ?>'>
</form>
</body>
</html>
