<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="webkit" name="renderer">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>跳转中</title>
</head>
<body onLoad="document.dingyiPay.submit();">
<form name='dingyiPay' id="diy" action='<?php echo $postFields['url']; ?>' method='post'>
    <input type="hidden" name="MerchantCode" value="<?php echo $postFields['MerchantCode'] ?>"/>
    <input type="hidden" name="BankCode"		  value="<?php echo $postFields['BankCode'] ?>" />
    <input type="hidden" name="Amount" value="<?php echo $postFields['Amount'] ?>" />
    <input type="hidden" name="OrderId"     value="<?php echo $postFields['OrderId'] ?>"/>
    <input type="hidden" name="NotifyUrl"  value="<?php echo $postFields['NotifyUrl'] ?>"/>
    <input type="hidden" name="OrderDate" value="<?php echo $postFields['OrderDate'] ?>"/>
    <input type="hidden" name="Sign" value="<?php echo $postFields['Sign'] ?>"/>
</form>
</body>
</html>

