<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="webkit" name="renderer">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>跳转中</title>
</head>
<body onLoad="document.JieanfuPay.submit();">
<form name='JieanfuPay' id="diy" action='<?php echo $postFields['url']; ?>' method='post'>
    <input type="hidden" name="merchantno"		  value="<?php echo $postFields['merchantno'] ?>" />
    <input type="hidden" name="orderno" value="<?php echo $postFields['orderno'] ?>" />
    <input type="hidden" name="code"     value="<?php echo $postFields['code'] ?>"/>
    <input type="hidden" name="bank_type"      value="<?php echo $postFields['bank_type'] ?>"/>
    <input type="hidden" name="amount"  value="<?php echo $postFields['amount'] ?>"/>
    <input type="hidden" name="keep_field1" value="<?php echo $postFields['keep_field1'] ?>"/>
    <input type="hidden" name="browser_url" value="<?php echo $postFields['browser_url'] ?>"/>
    <input type="hidden" name="serverback_url" value="<?php echo $postFields['serverback_url'] ?>"/>
    <input type="hidden" name="sign" value="<?php echo $postFields['sign'] ?>"/>
</form>
</body>
</html>
