<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="webkit" name="renderer">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>跳转中</title>
</head>
<body onLoad="document.diy.submit();">
<form name='diy' id="diy" action='<?php echo $postFields['url']; ?>' method='post'>
    <input type='hidden' name='merKey' value='<?php echo $postFields['merKey']; ?>'>
    <input type='hidden' name='orderNo' value='<?php echo $postFields['orderNo']; ?>'>
    <input type='hidden' name='amount' value='<?php echo  $postFields['amount']; ?>'>
    <input type='hidden' name='returnUrl' value='<?php echo $postFields['returnUrl']; ?>'>
    <input type='hidden' name='notifyUrl' value='<?php echo $postFields['notifyUrl']; ?>'>
    <input type='hidden' name='payType' value='<?php echo $postFields['payType']; ?>'>
    <input type='hidden' name='sign' value='<?php echo $postFields['sign']; ?>'>
</form>
</body>
</html>
