<div class="service_informat_layer">
      <div class="serinfor_left_part">
           <span class="service_default_title chat_center_text">聊天中心</span>
       </div>
      <div class="serinfor_right_part">当前状态信息栏</div>
</div>
<div class="service_center_leftmenu">
     <ul>
         <!-- <li><a href="index.jsp?&a=genroom&c=help" <?php if(ACTION=='genroom'): ?>class="service_active"<?php endif;?>>联系上下级
                 <?php if(ACTION=='genroom'): ?><span class="leftmenu_arrow">&gt;</span><?php endif;?>
             </a>
         </li> -->
         <li><a class="duokebo-btn"  target="_blank" href="<?php echo getFloatConfig('service_url'); ?>">联系客服</a></li>
         <li class="leftmenu_divided">
           <span class="state_letter_part">
               <span class="station_letter_leftmenu"></span>
               站内信
            </span>
         </li>
         <li><a href="index.jsp?c=user&a=receiveBox" <?php if(ACTION=='receiveBox'): ?>class="service_active"<?php endif;?>>收件箱
                 <?php if(ACTION=='receiveBox'): ?><span class="leftmenu_arrow">&gt;</span><?php endif;?>
                  
             </a>
         </li>
         <li><a href="index.jsp?c=user&a=sendBox" <?php if(ACTION=='sendBox'): ?>class="service_active"<?php endif;?>>发件箱
                 <?php if(ACTION=='sendBox'): ?><span class="leftmenu_arrow">&gt;</span><?php endif;?>
             </a>
         </li>
         <li><a href="index.jsp?c=user&a=sendMsg" <?php if(ACTION=='sendMsg'): ?>class="service_active"<?php endif;?>>写信
                 <?php if(ACTION=='sendMsg'): ?><span class="leftmenu_arrow">&gt;</span><?php endif;?>

             </a>
         </li>

         <!-- <li><a href="index.jsp?c=help&a=download" <?php if(ACTION=='download'): ?>class="service_active"<?php endif;?>>客户端下载
                 <?php if(ACTION=='download'): ?><span class="leftmenu_arrow">&gt;</span><?php endif;?>
             </a>
         </li> -->
     </ul>
</div>