<!DOCTYPE HTML>  <!-- 团队投注明细 -->
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="webkit" name="renderer">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title><?php echo config::getConfig('site_title'); ?></title>
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/common_operate.css" />
    <?php $this->import('public_cssjs') ?>

    <!--/****************************** 添加 js事件,实现跳转***************************************/-->
    <script type="text/javascript">
        $(function(){
            //>>设置跳转
            var html = '<div class="snow-page-div" style="  float: left;margin-top: 8px; margin-right: 10px;">第<input type="text" name="upPage" value="1" style=" width: 45px; height: 20px; display: inline; margin-left: 8px; margin-bottom: 4px; border: 1em; border: solid 1px #B8B8B8; border-radius: 2px; vertical-align: baseline; line-height: 24px; background-color: #e9e9e9; text-align: center;"  class="snow-input "/> 页<input class="btn-sm  btn-info upPage"  style="         margin-bottom: 3px;  margin-left: 5px;  font-size: 13px;  line-height: 1.5;  border-radius: 3px;  color: #fff;  background-color: #D22018;  border-color: #46b8da;  cursor: pointer;" type="button" value=">>确定<<"/></div>';
            var pageList = $('.user-page-boxs').html();
            pageList = pageList + html;
            $('.user-page-boxs').html(pageList);
            //>>设置分页条换行
            $('.user-page-boxs').closest('li').css({"float" : 'right',"margin-left" : "19px", "margin-top" : '15px','width' : '100%'})
            $('.user-page-boxs').css({'margin' :'0 auto',})
            $('#pageList').css({'float' : 'left'})

            //>>设置当前跳转框的默认值
            //>>获取跳转地址
            //>>获取最大值
            var maxStr = $('#pageList label').html();
            maxStr = maxStr.substring(1,maxStr.lastIndexOf(']'));
            var maxPage = parseInt(maxStr.substring(parseInt(maxStr.indexOf('/')) + 1));
            var nowPage = parseInt(maxStr.substring(0,parseInt(maxStr.indexOf('/'))));
            $('input[name=upPage]').val(nowPage);
            $('.upPage').on('click',function(){

                //>>如果有输出就使用输出
                <?php if(isset($maxPge)) : ?>
                maxPage = '<?php echo $maxPage ?>' == '' ? 1 : '<?php echo $maxPage ?>';
                <?php endif ?>
                if(parseInt($('.snow-input').val()) > parseInt(maxPage)){
                    //>>更改为最大值,并提示
                    $('.snow-input').val(maxPage);
                    try{
                        layer.alert('超过了最大页码值');
                    }catch(e){
                        alert('超过了最大页码值')
                    }

                    return false;
                }else{
                    if (parseInt($('.snow-input').val()) < 1)
                    {
                        $('input[name=upPage]').val(1);
                        try{
                            layer.alert('不能输入小于1的页码值');
                        }catch(e){
                            alert('不能输入小于1的页码值')
                        }
                        return false;
                    }

                    //>>没有超过最大页码值, 跳转到相应页码
                    var url = window.location.href;
                    var page = $('input[name=upPage]').val();
                    //>>不知道到底用哪个
                    url += '&upPage=' + page + '&curPage=' + page;
                    window.location.href = url;
                    window.event.returnValue=false;  //>解决跳转失效问题
                }
            })
        })
    </script>
    <!--/****************************** 添加 js事件,实现跳转***************************************/-->
</head>

<body>
<?php $this->import('public_header') ?>
<div class="operate_middle_page">
    <?php $this->import("public_usermenu"); ?>

    <div class="common_pages default_operate_pageheight">
        <form name="form1" id="form1" action="" method="get">
            <div class="default_record_search none_border_bottom">
                <ul>
                    <li>
                        <label class="search_record_datelab2">时间：</label>
                        <div class="record_date_range">
                            <input size="12" name="startDate" value="<?php echo $startDate; ?>" id="startDate" my97mark="false" onfocus="WdatePicker({dateFmt: 'yyyy-MM-dd'})" class="default_common_input datepicker85"/>
                            <em>到</em>
                            <input size="12" name="endDate" value="<?php echo $endDate; ?>"  id="endDate" my97mark="false" onfocus="WdatePicker({dateFmt: 'yyyy-MM-dd'})" class="default_common_input datepicker85"/>
                        </div>
                    </li>
                    <li>
                        <label class="margin_left_thirty">下级帐号：</label>
                        <input name="username" class="default_common_input" type="text"　value="<?php echo $username; ?>" />
                    </li>
                    <li>
                        <label class="margin_left_thirty">查询范围：</label>
                        <select name="include_childs" class="default_common_input">
                            <option value="0">指定会员</option>
                            <option value="1">指定会员及下级</option>
                        </select>
                    </li>
                    <li>
                        <input type="hidden" name="c" value="user"/>
                        <input type="hidden" name="a" value="<?php echo ACTION; ?>"/>
                        <input type="submit" value="搜索" class="default_record_searchbtn">
                    </li>
                </ul>
            </div>
            <div class="default_record_search">
                <ul>
                    <li>
                        <label class="margin_left_fortyone">游戏：</label>
                        <select name="lottery_id" class="default_common_input">
                            <option value="0">不限</option>
                            <?php foreach ($lotterys as $v): ?>
                                <option value="<?php echo $v['lottery_id']; ?>"><?php echo $v['cname']; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </li>
                    <li>
                        <label class="margin_left_fortyone">奖期：</label>
                        <input type="text" name="issue" value="" class="default_common_input">
                    </li>
                    <li><label class="margin_left_thirty">订单状态：</label>
                        <select name="status" class="default_common_input">
                            <option value="-1">不限</option>
                            <option value="0">正常</option>
                            <option value="1">用户撤单</option>
                            <option value="2">追中撤单</option>
                            <option value="3">出号撤单</option>
                            <option value="4">未开撤单</option>
                        </select>
                    </li>
                    <li><label class="margin_left_thirty">是否中奖：</label>
                        <select name="check_prize_status" class="default_common_input">
                            <option value="-1">不限</option>
                            <option value="1">是</option>
                            <option value="2">否</option>
                        </select>
                    </li>
                    <li class="float_right">
                        <div class="user-page-boxs">
                            <?php echo $pageList; ?>
                        </div>
                    </li>
                </ul>
            </div>
        </form>

        <table class="defoperate_record_tablist">
            <thead>
            <tr class="defoperate_record_tabtitle">
                <th width="9%">账户</th>
                <th width="16%">订单号</th>
                <th width="13%">投注时间</th>
                <th width="12%">游戏类别</th>
                <th width="12%">期号</th>
                <th width="10%">投注金额</th>
                <th width="10%">中奖金额</th>
                <th width="10%">盈亏</th>
                <th width="8%">状态</th>
            </tr>   
            </thead>
            <tbody>
            <?php if ($packages): ?>
                <?php foreach ($packages as $v): ?>
                    <tr class="recordsContent">
                        <td><?php echo $v['username'];?></td>
                        <td>
                            <a class="orderNumberBtn blue_font_href" href="javascript:;"><?php echo $v['wrap_id']; ?></a>
                        </td>
                        <td><?php echo $v['ts'];?></td>
                        <td><?php echo $lotterys[$v['lottery_id']]['cname']; ?></td>
                        <td><?php echo $v['issue']; ?></td>
                        <td><?php echo $v['amount']; ?></td>
                        <td><?php echo $v['prize']; ?></td>
                        <td><?php echo $v['profit']; ?></td>
                        <td><?php if ($v['cancel_status'] == 0): ?>
                                <?php if ($v['check_prize_status'] == 0): ?>未开奖
                                <?php elseif ($v['check_prize_status'] == 1): ?>已中奖
                                <?php else: ?>未中奖
                                <?php endif; ?>
                            <?php else: ?>
                                <?php if ($v['cancel_status'] == 1): ?>个人撤单
                                <?php elseif ($v['cancel_status'] == 2): ?>追中撤单
                                <?php elseif ($v['cancel_status'] == 3): ?>出号撤单
                                <?php elseif ($v['cancel_status'] == 4): ?>未开撤单
                                <?php elseif ($v['cancel_status'] == 9): ?>系统撤单
                                <?php endif; ?>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                <!--
                    <tr>
                    <th>本页合计：</th>
                    <th colspan="4"></th>
                    <th><?php /*echo number_format($realAmount, 2); */?></th>
                    <th><?php /*echo number_format($totalPrize, 2); */?></th>
                    <th></th>
                    <th></th>
                    <th colspan="9">
                    </tr>
                -->
            <?php else: ?>
                <tr>
                    <th colspan="9" class="bom">暂无数据显示</th>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
    <?php $this->import("common_operate_count"); ?>

</div>
<?php $this->import('public_foot') ?>
<script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/jquery.plugin.js"></script><!--jquery小插件-->
<script src="js/My97DatePicker/WdatePicker.js"></script>

<script type="text/javascript">
    $(function() {
        $('#form1').submit(function() {
            /*                    if ($('input[name=username]').val() == '') {
             alert('请输入下级帐号！');
             return false;
             }*/

            return true;
        });

        //设置默认值
        $('input[name=username]').val('<?php echo $username; ?>');
        $('select[name=status]').val('<?php echo $status; ?>');
        $('select[name=is_trace]').val('<?php echo $is_trace; ?>');
        $('select[name=check_prize_status]').val('<?php echo $check_prize_status; ?>');
        $('select[name=lottery_id]').val('<?php echo $lottery_id; ?>').change();
        $('input[name=issue]').val('<?php echo $issue; ?>');
        $('select[name=include_childs]').val('<?php echo $include_childs; ?>').change();
        $('#start_time').val('<?php echo date("Y-m-d", strtotime($start_time)); ?>');
        $('#end_time').val('<?php echo date("Y-m-d", strtotime($end_time)); ?>');
        $('input[name=wrap_id]').val('<?php echo $wrap_id; ?>');

        $('a.orderNumberBtn').on('click', function(){
            var str_award = '普通玩法';

            layer.open({
                type: 2,
                shadeClose: true,
                title: str_award+'&nbsp;&nbsp;订单编号：'+$(this).text(),
                closeBtn: false,
                shade: [0.3, '#000'],
                border: [0],
                area: ['824px','550px'],
                content: ['index.jsp?c=game&a=packageDetail&wrap_id='+$(this).text()]
            });
            $('div.xubox_title', document).addClass('layui-layer-title');
        });

        $('a.closeDialogBtn').on('click', function(){
            layer.close(orderDetailsDal);
        });

        var lottery_issue_format = <?php echo $lotteryIssueFormat; ?>;

        $('select[name=lottery_id]').change(function(){
            if ($('select[name=lottery_id]').val() == '0') {
                return;
            }
            var select_value = $('select[name=lottery_id]').val();
            if(lottery_issue_format[select_value] != undefined){
                $('input[name="issue"]').attr('placeholder',lottery_issue_format[select_value]);
            }else{
                $('input[name="issue"]').attr('placeholder','');
            }
        });
    });
</script>

</body>
</html>
