<!DOCTYPE html>
<html>
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="webkit" name="renderer">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo config::getConfig('site_title'); ?></title>
</head>
    <style>
        body,div,dl,dt,dd,ul,ol,li,h1,h2,h3,h4,h5,h6,pre,form,fieldset,input,textarea,p,blockquote,th,td{padding:0;margin:0;font-family: "微软雅黑";}
        ol, ul {list-style: none;}
        .main{margin: 0px auto;width:1000px;}
        .top{background: #FFF; height: 82px;}
        .logo {float: left;width: 226px; height: 82px;background: url(../images/turnplate/logo.png);}
        .nav {float: right; height: 82px;}
        .nav a { display: block; height: 82px; line-height: 82px;}
        .noticeMap {margin:auto auto;background: url(../images/light_blue/firstDepositDetail.png) center no-repeat;width:1000px;height:1565px;}
    </style>

<body>
        <div class="noticeMap"></div>
</body>
</html>