<!DOCTYPE HTML>  <!-- 登录密码修改 -->
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="webkit" name="renderer">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title><?php echo config::getConfig('site_title'); ?></title>
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/common_operate.css" />
    <?php $this->import('public_cssjs') ?>
</head>

<body>
<!-- 顶部导航信息部分 -->
<?php $this->import('public_header') ?>
<div class="operate_middle_page">
    <?php $this->import("public_usermenu"); ?>

    <div class="common_pages service_center_pageheight padding_top_eight">
        <div class="middle_modify_layer">
                <form name="form2" id="form2" onsubmit="return false;">
                <div class="form_group">
                    <label for="password" class="control_label">新的登录密码：</label>
                    <div class="col_sm_10">
                        <input type="password" name="password" id="password" class="form_control two_hundred_width">
                    </div>
                </div>
                <div class="form_group">
                    <label for="password2" class="control_label">确认登录密码：</label>
                    <div class="col_sm_10">
                        <input type="password" name="password2" id="password2" class="form_control two_hundred_width">
                    </div>
                </div>
<!--                <div class="form_group">-->
<!--                    <label for="safe_pwd" class="control_label">安全码：</label>-->
<!--                    <div class="col_sm_10">-->
<!--                        <input type="password" class="form_control two_hundred_width" name="safe_pwd" id="safe_pwd">-->
<!--                    </div>-->
<!--                </div>-->
                <div class="form_group msgsend_btn_layer">
                    <input type="submit" id="pwdBtn" class="default_navyblue_btn modify_btn" value="确定修改" name="submit">
                </div>
            </form>
        </div>
    </div>
</div>
<?php $this->import('public_foot') ?>

<script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/jquery.plugin.js"></script><!--jquery小插件-->

<script>
    var formUrl = '?c=user&a=<?php echo ACTION; ?>';
    $(document).ready(function() {
        $('#pwdBtn').on('click',function(){
            var pwd = $('input[name=password]').val();
            var pwd2 = $('input[name=password2]').val();
//            var safe_pwd = $('input[name=safe_pwd]').val();
            if (pwd.length == 0) {
                top.layer.alert('请输入新的登录密码');
                return false;
            }
            if(pwd!=$('input[name=password2]').val()){
                top.layer.alert('您输入的新的登录密码和确认登录密码不相同');
                return false;
            }

            var re1 = /^[A-Za-z]+$/;
            var re2 = /^\d+$/;
            var re3 = /^\w{6,15}$/;
            if(!re3.test(pwd) || re2.test(pwd) || re1.test(pwd)){
                top.layer.alert("密码必须是6-15位字母数字混合，且不能为全是数字或全是字母");
                return false;
            }
//            if(safe_pwd.length == 0){
//                top.layer.alert('请输入安全码');
//                return false;
//            }
            $.ajax({
                type: "POST",
                url: formUrl,
                data: {'submit':1,password:pwd,password2:pwd2},//,safe_pwd:safe_pwd
                dataType: "json", //返回0和1
                success: function(data) {
                    if(data.errno == 0){
                        top.layer.alert(data.errstr,1);
                        $('#form2').trigger('reset');
                    }else if(data.errno > 0){
                        top.layer.alert(data.errstr);
                    }
                }
            });
        });


    });
</script>
</body>
</html>