<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="webkit" name="renderer">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?php echo config::getConfig('site_title'); ?></title>
        <link href="<?php echo $imgCdnUrl ?>/css/all_blue.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $imgCdnUrl ?>/css/common.css" rel="stylesheet" type="text/css"  />
        <script src="<?php echo $imgCdnUrl ?>/js/common.js" type="text/javascript"></script>
        <script src="<?php echo $imgCdnUrl ?>/js/jquery.js" type="text/javascript"></script>
        <script src="<?php echo $imgCdnUrl ?>/js/jquery.md5.js" type="text/javascript"></script>
        <link href="<?php echo $imgCdnUrl ?>/js/jqueryUI/dialog/css/jquery.dialog.blue.css" rel="stylesheet" type="text/css"  />
        <script src="<?php echo $imgCdnUrl ?>/js/jqueryUI/dialog/js/jquery.dialog.js" type="text/javascript"></script>
        <script>
            $(function() {

                var submitAction = function(e) { //按esc关闭层
                    var key = e.keyCode ? e.keyCode : e.which;
                    if (key == 13 && $('input[name=password]').val() != '') {
                        $('#regBtn').click();
                    }
                }
                $('input[name=password2]').keyup(submitAction);
                $('#regBtn').click(function() {
                    if ($('input[name=username]').val() == '') {
                        //alert('请输入用户名 ');
                        $('#usernameTips').hide();
                        $('#usernameTips').show('shake', null, 500, function() {
//                            setTimeout(function() {
//                                $("#usernameTips:visible").removeAttr("style").fadeOut();
//                            }, 1000);
                        } );
                        return false;
                    }
                    if ($('input[name=password]').val() == '') {
                        alert('请输入密码');
                        return false;
                    }
                    if ($('input[name=password2]').val() != $('input[name=password]').val()) {
                        alert('确认密码不一致');
                        return false;
                    }
                    $.post(
                            'index.jsp?c=user&a=reg',
                            {
                                username: $('input[name=username]').val(),
                                password: $('input[name=password]').val(),
                                password2: $('input[name=password2]').val(),
                                submit: 'submit'
                            },
                    function(response) {
                        if (response.errno == 0) {
                            location.href = response.errstr;
                        }
                        else {
                            $.alert(response.errstr + '!');
                            $('input[name=username]').val('');
                            $('input[name=password]').val('');
                            $('input[name=password2]').val('');
                        }
                    }, 'json');
                });
            });
        </script>
    </head>
    <body  class="Log_bg">
        <div class="reg">
            <form action="index.jsp?c=user&a=reg" method="post">
                <div class="login-inner">
                    <p>
                        用户名：<span class="red" id="usernameTips">用户名长度为5-10个字母或数字，且必须以字母开头</span></p>
                    <p>
                        <input type="text"  maxlength="50" name="username" title="请输入帐号" tabindex="1" autocomplete="off" />
                    </p>
                    <p>密码：<span class="red" id="passwordTips">密码长度为6-15字符，不能为纯数字或纯字母</span></p>
                    <p>
                        <input type="password" name="password" title="请输入密码"  tabindex="2" />
                    </p>
                    <p>确认密码：<span class="red" id="password2Tips">2次输入密码必须一致</span></p>
                    <p>
                        <input type="password" name="password2" title="请输入确认密码"  tabindex="3"  />
                    </p>
                    <p>
                        <button type="button" tabindex="6"  id="regBtn" class="regBtn">注&nbsp;&nbsp;册</button>
                    </p>
                </div>
            </form>
        </div>
    </body>
</html>