<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
		<style type="text/css">
			*{padding: 0;margin: 0;}
			.main{width: 100%;}
			.main p{padding:0 4rem 0 4rem;}
			.main h2{padding: 2rem;}
			p{margin:10px auto}
		</style>
	</head>
	<body>
		<div class="main">
			<h2  class="h2-1">如何修改登录密码、资金密码？</h2>
            <p>
                请联系客服!通过客服进行密码修改
            </p>
		</div>
	</body>
</html>
