<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="webkit" name="renderer">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo config::getConfig('site_title'); ?></title>
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/Jstyle.css" />
    <script src="<?php echo $imgCdnUrl ?>/js/jquery.js" type="text/javascript"></script>
    <script src="<?php echo $imgCdnUrl ?>/js/jquery.md5.js" type="text/javascript"></script>
</head>

<body class="loginbody">
    <!-- toplist开始 -->
    <div class="loginTop fix">
        <div class="logoLeft"></div>
        <p class="SavePage">我们为您的账户保驾护航！</p>
    </div>
    <!-- toplist结束 -->
    <div class="loginContent">
        <div class="loginMain" id="container">
            <div class="forgetPwdCont">
                <h3 class="title">找回密码</h3>
                <div class="recordsBox">
                    <form name="form1" id="form1" action="index.jsp?a=forgetPwd" method="post">
                        <table class="new_passwordNeir">
                            <colgroup>
                                <col width="30%" />
                                <col />
                            </colgroup>
                            <tbody>
                                <?php if(!$username):?>
                                <tr>
                                    <th>用户名：</th>
                                    <td>
                                        <input type="text" name="username" maxlength="12" value="" /><span>*</span><span id="userTip"></span>
                                    </td>
                                </tr>
                                <tr>
                                    <th>安全码：</th>
                                    <td>
                                        <input type="password" name="safe_pwd"  maxlength="15" value=""/><span>*</span><span id="pwdTip"></span>
                                    </td>
                                </tr>
                                <tr>
                                    <th>验证码：</th>
                                    <td>
                                        <input type="text" name="verifyCode" maxlength="5" id="verifyCode"><img align="absmiddle" src="?c=default&a=verifyCode" width="60px" height="30px" id="code" title="请点图片刷新">
                                    </td>
                                </tr>
                                <?php else: ?>
                                <tr>
                                    <th>用户名：</th>
                                    <td><?php echo $username?></td>
                                </tr>
                                <tr>
                                    <th>新的登录密码：</th>
                                    <td>
                                        <input type="password" name="pwd" maxlength="12" value="" /><span>*</span><span id="userTip"></span>
                                    </td>
                                </tr>
                                <tr>
                                    <th>确认登录密码：</th>
                                    <td>
                                        <input type="password" name="confirm_pwd" maxlength="12" value="" /><span>*</span><span id="userTip"></span>
                                    </td>
                                </tr>
                                <?php endif;?>
                                <tr>
                                    <th></th>
                                    <td>
                                        <input type="submit" name="submit" value="确认" class="btnTow"/>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </form>
                </div>
            </div>
        </div>
    </div>

<?php $this->import('public_tongji') ?>
<script type="text/javascript">
    $(function(){
        $('#verifyCode').focus(function(){
            getCode('#code');
        })
        $('#code').click(function(){
            getCode('#code');
            $('#verifyCode').focus();
        })
        function getCode(ele){
            $(ele).attr('src','?a=verifyCode&'+Math.random())
        }
    })
</script>

</body>
</html>


