<!-- 新手提示开始 -->
<div class="newTips">
	<div class="newTipsBg"></div>
	<div class="newTipsImg">
		<div class="newTipsImg_pat1"></div>
		<div class="newTipsImg_pat2"></div>
		<div class="newTipsImg_pat3"></div>
	</div>
	<div class="newTipsBtn">
		<a class="newTipsBtnNext1" href="javascript:void(0)">下一步</a>
		<a class="newTipsBtnNext2" href="javascript:void(0)">下一步</a>
		<a class="newTipsBtnNext3 newTipsBtnEnd" href="javascript:void(0)">我知道啦</a>
	</div>
</div>
<!-- 新手提示结束 -->