<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta content="webkit" name="renderer"><!-- 页面默认用极速核 -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge"><!-- 指定浏览器按照最高的标准模式解析页面针对IE -->
        <meta name="format-detection" content="telephone=no,email=no"/><!-- 使设备浏览网页时对数字不启用电话功能 -->
        <meta name="apple-touch-fullscreen" content="YES"/><!-- "添加到主屏幕"后，全屏显示 -->
        <meta name="apple-mobile-web-app-capable" content="yes"/>  <!-- 如果内容设置为YES，Web应用程序运行在全屏模式;否则，它不会。默认行为是使用Safari浏览器显示网页内容 -->
        <!--<meta http-equiv="Cache-Control" content="no-cache"/>-->  <!-- 每次打开都清除浏览器页面缓存 -->
        <meta http-equiv="Cache-Control" content="no-siteapp" /><!-- 度SiteApp转码声明 -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
        <title><?php echo config::getConfig('site_title'); ?></title>
        <script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/jquery-1.8.3.min.js"></script>
        <script type="text/javascript">
          $(function(){
            $('.cl').click(function(){
                    $.ajax({
                          type : 'post',
                          dataType : 'json',
                          url : '?a=legalVisit',
                          data : {visit: 1},
                          success : function(response){
                              if (response.errno == 0) {
                                  location.href = response.errstr;
                              }
                              else {
                                  layer.alert(response.errstr + '!');
                              }
                          },
                          error : function(data){
                                  console.log(data);
                          }
                      });
            });
          });
        </script>
    </head>
<style type="text/css">
.cl{    width: 8em;line-height: 1.5em;color: #2a72d3;margin: 30px auto;display: block;text-align: center;border-bottom: 1px solid #2a72d3;cursor: pointer;}
</style>
    <body>
      <h3><botton class='cl'>请点击进入网站</botton></h3>
    </body>
</html>
