<!-- 背景层开始 -->
<div class="BodyBg">
      <div class="Bodybg01"></div>
      <div class="Bodybg02"></div>
      <div class="Bodybg03"></div>
      <div class="Bodybg04"></div>
      <div class="Bodybg05"></div>
      <div class="Bodybg06"></div>
      <div class="Bodybg07"></div>
      <div class="Bodybg08"></div>
      <div class="Bodybg09"></div>
      <div class="Bodybg10"></div>
      <div class="Bodybg11"></div>
      <div class="Bodybg12"></div>
      <div class="Bodybg13"></div>
      <div class="Bodybg14"></div>
      <div class="Bodybg15"></div>
      <div class="Bodybg16"></div>
      <div class="Bodybg17"></div>
      <div class="Bodybg18"></div>
      <div class="Bodybg19"></div>
      <div class="Bodybg20"></div>
      <div class="Bodybg21"></div>
      <div class="Bodybg22"></div>
      <div class="Bodybg23"></div>
      <div class="Bodybg24"></div>
      <div class="Bodybg25"></div>
      <div class="Bodybg26"></div>
      <div class="Bodybg27"></div>
  </div>
  <!-- 背景层结束 -->

  <!-- 浮动客服开始 -->
  <script language="javascript" src="http://v88.live800.com/live800/chatClient/floatButton.js?jid=6179307430&companyID=716121&configID=2374&codeType=custom"></script>
  <!-- 浮动客服结束 -->