<!DOCTYPE HTML>   <!-- 新增会员 -->
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta content="webkit" name="renderer"><!-- 页面默认用极速核 -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge"><!-- 指定浏览器按照最高的标准模式解析页面针对IE -->
    <meta content="telephone=no,email=no" name="format-detection"/><!-- 使设备浏览网页时对数字不启用电话功能 -->
    <meta name="apple-touch-fullscreen" content="YES"/><!-- "添加到主屏幕"后，全屏显示 -->
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <!-- 如果内容设置为YES，Web应用程序运行在全屏模式;否则，它不会。默认行为是使用Safari浏览器显示网页内容 -->
    <!--<meta http-equiv="Cache-Control" content="no-cache"/>-->  <!-- 每次打开都清除浏览器页面缓存 -->
    <meta http-equiv="Cache-Control" content="no-siteapp"/><!-- 度SiteApp转码声明 -->
    <meta name="viewport"
          content="width=device-width,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <title>电子钱包 - <?php echo config::getConfig('site_title'); ?></title>
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/mobileStyle.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/mobile_overallStyle.css">
    <script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/jquery-1.8.3.min.js"></script>
</head>

<body>
<div class="operate_middle_page">
    <!--/*头部*/-->
    <header class="headerbg">
        <a class="headbox01" href="javascript:history.go(-1)"><img
                    src="<?php echo $imgCdnUrl ?>/images/mobile/head_Box1.png"/></a>
        <p class="headtetle">电子钱包</p>
    </header>
    <div class="common_pages add_menbers_page" style="margin-top: 1.875rem;">
        <div class="addmenber_userinfo">
            <div class="form_group ImportText">
                <label for="egame_balance">当前电子游戏额度：</label>
                <span id="egame_balance">0</span>
            </div>
            <div class="form_group ImportText new_user01">
                <label for="username" class="control_label" style="text-align: center;"><h2>转入电子游戏</h2></label>
            </div>
            <div class="form_group ImportText">
                <label for="amount_in" class="control_label">金额：</label>
                <input class="form_control two_hundred_width" type="text" name="amount_in" id="amount_in">
            </div>
            <div class="form_group ImportText">
                <label for="trans_pass_in" class="control_label">资金密码：</label>
                <input class="form_control two_hundred_width" type="password" name="trans_pass_in" id="trans_pass_in">
            </div>
            <div class="form_group" style="text-align: center;">
                <input type="submit" name="submit_in" class="default_navyblue_btn two_hundred_width modify_btn"
                       value="转入">
            </div>

            <div class="form_group ImportText new_user01">
                <label for="username" class="control_label" style="text-align: center;"><h2>电子游戏转出</h2></label>
            </div>
            <div class="form_group ImportText">
                <label for="amount_out" class="control_label">金额：</label>
                <input class="form_control two_hundred_width" type="text" name="amount_out" id="amount_out">
            </div>
            <div class="form_group ImportText">
                <label for="trans_pass_out" class="control_label">资金密码：</label>
                <input class="form_control two_hundred_width" type="password" name="trans_pass_out" id="trans_pass_out">
            </div>
            <div class="form_group" style="text-align: center;">
                <input type="submit" name="submit_out" class="default_navyblue_btn two_hundred_width modify_btn"
                       value="转出">
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/jquery.plugin.js"></script><!--jquery小插件-->
<script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/ZeroClipboard.107.js"></script>
<script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/public.js"></script>
<script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/clipboard.min.js"></script>
<script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/layer-v2.4/layer.js"></script>
<script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/jquery.qrcode.min.js"></script>

<script>
    $(function () {
        var submitIn = $('input[name=submit_in]');

        submitIn.click(function () {
            var r1 = /^[0-9]*[1-9][0-9]*$/;

            if (!r1.test($('input[name=amount_in]').val())) {
                parent.layer.alert("金额必须为正整数！");
                return false;
            }

            submitIn.attr('disabled', 'disabled');

            $.post(
                '?c=fin&a=tranMoney',
                {
                    'op': "tran",
                    'tranFrom': 0,
                    'tranTo': 1,
                    'tranAmount': $('input[name=amount_in]').val(),
                    'tranPass': $('input[name=trans_pass_in]').val(),
                },
                function (response) {
                    parent.layer.alert(response.errstr);
                    $('input[name=amount_in]').val("");
                    $('input[name=trans_pass_in]').val("");
                    submitIn.removeAttr('disabled');
                }, 'json').error(function () {
                parent.layer.alert("未知错误，请联系客服");
                submitIn.removeAttr('disabled');

                getUserInfo();
            });
        });

        var submitOut = $('input[name=submit_out]');

        submitOut.click(function () {
            var r1 = /^[0-9]*[1-9][0-9]*$/;　//正整数

            if (!r1.test($('input[name=amount_out]').val())) {
                parent.layer.alert("金额必须为正整数！");
                return false;
            }

            submitOut.attr('disabled', 'disabled');

            $.post(
                '?c=fin&a=tranMoney',
                {
                    'op': "tran",
                    'tranFrom': 1,
                    'tranTo': 0,
                    'tranAmount': $('input[name=amount_out]').val(),
                    'tranPass': $('input[name=trans_pass_out]').val(),
                },
                function (response) {
                    parent.layer.alert(response.errstr);
                    $('input[name=amount_out]').val("");
                    $('input[name=trans_pass_out]').val("");
                    submitOut.removeAttr('disabled');
                }, 'json').error(function () {
                parent.layer.alert("未知错误，请联系客服");
                submitOut.removeAttr('disabled');
            });

            getUserInfo();
        });

        $(document).ready(function () {
            getUserInfo();
        });

        function getUserInfo() {
            $.post(
                '?c=egame&a=userInfo',
                {},
                function (response) {
                    $("#egame_balance").text(response.money);
                }, 'json');
        }
    });
</script>

<?php $this->import('public_tongji') ?>
</body>
</html>