<!DOCTYPE HTML>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="webkit" name="renderer">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title><?php echo config::getConfig('site_title'); ?></title>
        <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/all_LightBlue.css" />
    </head>

    <body>
        <!-- 内页公用板块 -->
        <div class="GameBoxall SubGamePlatePadding">
            <div class="Gamepart">
                <div class="subTopBar">
                    <div class="SubTit">
                        <h3>游戏记录</h3>
                    </div>
                    <div class="crumbs"></div>
                </div>
                <div class="clear"></div>
                <div class="sub_public">
                    <div class="sub_nav">
                        <div class="clear"></div>
                        <ul>
                            <li><a href="index.jsp?c=game&a=packageList">个人投注明细</a></li>
                            <li><a href="index.jsp?c=game&a=packageTeamList" class="subcur">团队投注明细</a></li>
                            <li><a href="index.jsp?c=game&a=traceList">追号记录</a></li>
                          <!--  <li><a href="index.jsp?c=game&a=egameList">休闲游戏记录</a></li>-->
                            <?php if ($user['level'] == 10) : ?>
                            <li><a href="index.jsp?c=game&a=memberReport">游戏报表</a></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                    <div class="sub_ContBox">
                        <div class="subContCent">
                            <!-- 搜索栏 -->
                            <div class="SearchBar">
                                <form method="GET" action="" id="form1" name="form1">
                                    <ul>
                                        <li>
                                            <label>游戏时间：</label>
                                            <div class="MutiTxt">
                                                <input class="Wdate txtStyle w85px datepicker85" onfocus="WdatePicker({dateFmt: 'yyyy-MM-dd'})" my97mark="false" id="startDate" name="startDate" value="<?php echo $startDate;?>" size="16">
                                                <em>到</em>
                                                <input class="Wdate txtStyle w85px datepicker85" onfocus="WdatePicker({dateFmt: 'yyyy-MM-dd'})" my97mark="false" id="endDate" name="endDate" value="<?php echo $endDate;?>" size="16">
                                            </div>
                                        </li>
                                        <li>
                                            <label>用户名：</label>
                                            <input type="text" value="<?php echo $username;?>" name="username" value="" SIZE="10"/>


                                        </li>
                                        <li style="width: 182px">
                                            <label>游戏名称：</label>
                                            <select class="SelectStyle" name="lottery_id">
                                                <option value="0">请选择</option>
                                                <?php foreach ($lotterys as $v): ?>
                                                    <option value="<?php echo $v['lottery_id']; ?>" <?php if($lottery_id == $v['lottery_id']) echo 'selected';?>><?php echo $v['cname']; ?></option>
                                                <?php endforeach; ?>
                                            </select>
                                        </li>

                                        <li style="width: 50px">
                                            <input type="submit" value="查询" class="btnStyle m010" name="submit">
                                        </li>
                                    </ul>
                                    <input type="hidden" value="game" name="c">
                                    <input type="hidden" value="packageTeamList" name="a">
                                </form>
                            </div>
                            <!-- 列表数据 -->
                            <div class="clear"></div>
                            <table class="tab01" border="0" cellspacing="0" cellpadding="0">
                                <tr>
                                    <th>账户</th>
                                    <th>订单号</th>
                                    <th>投注时间</th>
                                    <th>彩种</th>
                                    <th>奖期</th>

                                    <th>投注金额</th>
                                    <th>中奖金额</th>
                                    <th>盈亏</th>
                                    <th>状态</th>

                                </tr>
                                <?php if ($packages): ?>
                                    <?php foreach ($packages as $v): ?>
                                        <tr class="recordsContent">
                                            <td><?php echo $v['username'];?></td>
                                            <td><a onclick="showPackageDetail('<?php echo $v['wrap_id']; ?>');return false;" href="?c=game&a=packageDetail&wrap_id=<?php echo $v['wrap_id']; ?>" title="查看订单详情"><?php echo $v['wrap_id']; ?></a></td>
                                            <td><?php echo $v['ts'];?></td>
                                            <td><span class="yellow"><?php echo $lotterys[$v['lottery_id']]['cname']; ?></span></td>
                                            <td><?php echo $v['issue']; ?></td>
                                            <td><?php echo $v['amount']; ?></td>
                                            <td><?php if ($v['cancel_status'] == 0): ?>
                                                    <?php if ($v['check_prize_status'] == 1): echo $v['prize']; ?>
                                                    <?php else: echo '--' ?>
                                                    <?php endif; ?>
                                                <?php else: echo '--'; ?>
                                                <?php endif; ?>
                                            </td>
                                            <td></td>
                                            <td><?php if ($v['cancel_status'] == 0): ?>
                                                    <?php if ($v['check_prize_status'] == 0): ?><span class="yellow_dark">未开奖</span>
                                                    <?php elseif ($v['check_prize_status'] == 1): ?><span class="greenlight">已中奖</span>
                                                    <?php else: ?><span class="red">未中奖</span>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <b>
                                                        <?php if ($v['cancel_status'] == 1): ?><span class="yellow_dark">个人撤单</span>
                                                        <?php elseif ($v['cancel_status'] == 2): ?><span class="yellow_dark">追中撤单</span>
                                                        <?php elseif ($v['cancel_status'] == 3): ?><span class="yellow_dark">出号撤单</span>
                                                        <?php elseif ($v['cancel_status'] == 4): ?><span class="yellow_dark">未开撤单</span>
                                                        <?php elseif ($v['cancel_status'] == 9): ?><span class="yellow_dark">系统撤单</span>
                                                        <?php endif; ?>
                                                    </b>
                                                <?php endif; ?>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                    <tr>
                                        <th>本页合计：</th>
                                        <th colspan="4"></th>
                                        <th><?php echo number_format($realAmount, 2); ?></th>
                                        <th><?php echo number_format($totalPrize, 2); ?></th>
                                        <th></th>
                                        <th></th>
                                        <th></th>
                                        <th></th>
<!--                                        <th colspan="9">
                                            <div class="bottom_info">计划投注金额 <span class="yellow"><?php /*echo number_format($totalAmount, 2); */?></span> 元   &nbsp;&nbsp;实际投注金额: <span class="yellow"><?php /*echo number_format($realAmount, 2); */?></span> 元  &nbsp;&nbsp;中奖金额小计: <span class="yellow"><?php /*echo number_format($totalPrize, 2); */?></span> 元</div></th>-->
                                    </tr>
                                <?php else: ?>
                                    <tr>
                                        <th colspan="11" class="bom">暂无数据显示</th>
                                    </tr>
                                <?php endif; ?>

                            </table>
                            <!-- 分页 -->
                            <div class="Page">
                                 <?php echo $pageList; ?>
                            </div>
                            <!-- 分页end -->

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/jquery-1.8.3.min.js"></script>
        <script src="<?php echo $imgCdnUrl ?>/js/common.js" type="text/javascript"></script>
        <script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/jquery.plugin.js"></script><!--jquery小插件-->
        <script>
    $(function() {
        //设置默认值
        $('select[name=lottery_id]').val('<?php echo $lottery_id; ?>').change();
        $('#start_time').val('<?php echo date('Y-m-d', strtotime($start_time));  ?>');
        $('#end_time').val('<?php echo date('Y-m-d', strtotime($end_time)); ?>');
        $('input[name=wrap_id]').val('<?php echo $wrap_id; ?>');
        $('select[name=check_prize_status]').val('<?php echo $check_prize_status; ?>').change();

    });
</script>
    <?php $this->import('public_tongji') ?>
</body>
</html>
