<!DOCTYPE HTML> <!-- 投注记录订单详情页面 -->
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta content="webkit" name="renderer"><!-- 页面默认用极速核 -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge"><!-- 指定浏览器按照最高的标准模式解析页面针对IE -->
    <meta content="telephone=no,email=no" name="format-detection"/><!-- 使设备浏览网页时对数字不启用电话功能 -->
    <meta name="apple-touch-fullscreen" content="YES"/><!-- "添加到主屏幕"后，全屏显示 -->
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <!-- 如果内容设置为YES，Web应用程序运行在全屏模式;否则，它不会。默认行为是使用Safari浏览器显示网页内容 -->
    <!--<meta http-equiv="Cache-Control" content="no-cache"/>-->  <!-- 每次打开都清除浏览器页面缓存 -->
    <meta http-equiv="Cache-Control" content="no-siteapp"/><!-- 度SiteApp转码声明 -->
    <meta name="viewport"
          content="width=device-width,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <title><?php echo config::getConfig('site_title'); ?></title>
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/mobileStyle.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/mobile_overallStyle.css">
    <style type="text/css">
        .poker_kj_num i {
            background: url(../images/mobile/small/ls-small.png) no-repeat;
            display: inline-block;
            position: relative;
            width: 0.6rem;
            height: 0.5rem;
            padding-left: 0.5rem;
            background-position: 1rem 0.5rem;
            background-size: 0.6rem 3.8rem;
        }

        .poker_heit i {
            background-position: 0rem -0.01rem;
        }

        .poker_hongt i {
            background-position: 0rem -0.95rem;
        }

        .poker_meih i {
            background-position: 0rem -2.2rem;
        }

        .poker_fangk i {
            background-position: 0rem -3.3rem;
        }
    </style>
</head>
<style type="text/css">
    html, body {
        width: 100%;
        height: 100%;
        overflow: auto;
    }
</style>
<body>
<div id="orderDetailsLayer" class="order_details_layer">
    <ul class="bet_details">
        <li>彩种：<?php echo $lottery['cname']; ?><?php echo $package['xgame'] ? '(信)' : ''; ?>
            第 <?php echo $package['issue']; ?> 期
        </li>
        <li>订单号：<?php echo $package['wrap_id']; ?></li>
        <li>购买时间：<?php echo $package['create_time']; ?></li>

        <?php if(!$package['xgame']): ?>
        <li>模式：<?php echo $GLOBALS['cfg']['modes'][strval(floatval($package['modes']))]; ?></li>
        <li>投注倍数：<?php echo $package['multiple']; ?></li>
        <?php endif; ?>

        <!-- <li>奖金系列：<?php echo $prizeMode; ?></li> -->
        <li>
            <?php if ($lottery['lottery_id'] == 14): ?>
                <td class="width_poker"><span style="float: left;">开奖号码：</span>
                    <div class="poker_kj">
                        <?php foreach ($openCode as $p): ?>
                            <span class="poker_kj_num <?php echo $p['suit'] ?>"><i></i><em><?php echo $p['num'] ?></em></span>
                        <?php endforeach; ?>
                    </div>
                </td>
            <?php else: ?>
                <td>开奖号码：<span class="orange_font"><?php if (isset($openCode)) echo $openCode; ?></span></td>
            <?php endif; ?>
        </li>
        <li>中奖金额：<?php echo $package['prize']; ?></li>
    </ul>
</div>
<div style="display:inline-block;overflow: auto;height: 8rem;">
    <table class="order_details_cont">
        <thead>
        <tr>
            <th width="20%">玩法名称</th>
            <th width="60%">投注内容</th>
            <th width="20%">投注金额</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($projects as $v): ?>
            <tr>
                <td><?php echo $methods[$v['method_id']]['cname']; ?></td>
                <td><label class="textarea"><?php if ($methods[$v['method_id']]['name'] == 'JSSTTX') {
                            echo '111_222_333_444_555_666';
                        } elseif ($methods[$v['method_id']]['name'] == 'JSSLTX') {
                            echo '123_234_345_456';
                        } else {
                            echo str_replace('|', '|', $v['code']);
                        } ?></label></td>
                <td><span class="orange_font"><?php echo $v['amount']; ?></span>元</td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<div class="close_order_layer">
    <?php if ($package['show_cancel']): ?>
        <a href="javascript:void(0);" id="buttonCanle" name="cancel" class="cancelBtn">撤单</a>
    <?php endif; ?>
    <a href="javascript:void(0);" class="closeDialogBtn">返回</a>
</div>
</div>

<script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/jquery-1.8.3.min.js"></script>
<script>
    $(function () {
        if ($('.textarea').text().length >= 30) {
            $('.textarea').addClass('are');
        } else {
            $('.textarea').removeClass('are');
        }
        $('a.closeDialogBtn').on('click', function () {
            var index = parent.layer.getFrameIndex(window.name);      //获取当前窗口索引
            parent.layer.close(index);
        });

        $('#buttonCanle').click(function () {
            top.layer.confirm('您真的要撤单吗？', {icon: 7}, function (i) {
                $.post(
                    'index.jsp?c=game&a=cacelPackage',
                    {
                        'wrap_id': '<?php echo $package['wrap_id']; ?>',
                    },
                    function (response) {
                        if (response.errno == 0) {
                            var wrap_id = '<?php echo $package['wrap_id']; ?>';
                            $(window.top.document).find(".MainIframe").contents().find("input[name=" + wrap_id + "]").hide();
                            $(window.top.document).find(".MainIframe").contents().find("#status_" + wrap_id).html('个人撤单');
                            location.reload();
                        }
                        top.layer.alert(response.errstr, {icon: 1});
                    }, 'json');
            });
        });
    });
</script>
<?php $this->import('public_tongji') ?>
</body>
</html>