<!DOCTYPE HTML> <!-- 投注记录订单详情页面 -->
<html>
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta content="webkit" name="renderer"><!-- 页面默认用极速核 -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge"><!-- 指定浏览器按照最高的标准模式解析页面针对IE -->
    <meta content="telephone=no,email=no" name="format-detection" /><!-- 使设备浏览网页时对数字不启用电话功能 -->
    <meta name="apple-touch-fullscreen" content="YES"/><!-- "添加到主屏幕"后，全屏显示 -->
    <meta name="apple-mobile-web-app-capable" content="yes"/>  <!-- 如果内容设置为YES，Web应用程序运行在全屏模式;否则，它不会。默认行为是使用Safari浏览器显示网页内容 -->
    <!--<meta http-equiv="Cache-Control" content="no-cache"/>-->  <!-- 每次打开都清除浏览器页面缓存 -->
    <meta http-equiv="Cache-Control" content="no-siteapp" /><!-- 度SiteApp转码声明 -->
    <meta name="viewport" content="width=device-width,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <title><?php echo config::getConfig('site_title'); ?></title>
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/mobileStyle.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/mobile_overallStyle.css">
    </head>

    <body>
      <div id="orderDetailsLayer" class="order_details_layer">

       <div class="bet_details">
            <li>彩种：<?php echo $lottery['cname']; ?> 第 <?php echo $package['issue']; ?> 期</li>
            <li>订单号：<?php echo $package['wrap_id']; ?></li>
            <li>购买时间：<?php echo $package['create_time']; ?></li>
            <li>模式：<?php echo $GLOBALS['cfg']['modes'][strval(floatval($package['modes']))]; ?></li>
            <li>投注倍数：<?php echo $package['multiple']; ?></li>
            <!-- <li>奖金系列：<?php echo $prizeMode; ?></li> -->
            <li>开奖号码：<?php if (isset($openCode)) echo $openCode; ?></li>
            <li>中奖金额：<?php echo $package['prize']; ?></li>
       </div>
        <table class="order_details_cont">
                <thead>
                    <tr>
                        <th>玩法名称</th>
                        <th>投注内容</th>
                        <th>投注金额</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($projects as $v): ?>
                    <tr>
                        <td><?php echo $methods[$v['method_id']]['cname']; ?></td>
                        <td><label class="textarea"><?php echo str_replace('|', ' ', $v['code']); ?></label></td>
                        <td><span class="orange_font"><?php echo $v['amount']; ?></span>元</td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
          </table>
       <div class="close_order_layer">
            <a href="javascript:;" class="default_blue_btn closeDialogBtn">返回</a>
       </div>
</div>

   <script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/jquery-1.8.3.min.js"></script>
    <script>
    $(function() {
      if($('.textarea').text().length >= 30){
        $('.textarea').addClass('are');
      }else{
        $('.textarea').removeClass('are');
      }
      $('a.closeDialogBtn').on('click', function(){
            var index = parent.layer.getFrameIndex(window.name);      //获取当前窗口索引
            parent.layer.close(index);
        });
    });
</script>
    <?php $this->import('public_tongji') ?>
</body>
</html>