<!DOCTYPE html>
<html>
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="webkit" name="renderer">
<title><?php echo 'new'; ?></title>
<META http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link href="<?php echo $imgCdnUrl ?>/css/all_<?php echo $styleDir; ?>.css" rel="stylesheet" type="text/css"  />
<script src="<?php echo $imgCdnUrl ?>/js/jquery.js" type="text/javascript"></script>
<script src="<?php echo $imgCdnUrl ?>/js/common.js" type="text/javascript"></script>

</head>
<!-- 整体内容 -->
<div class="mainContent fixed fl container" id="container">