<!DOCTYPE HTML>   <!-- 服务中心下安全相关 -->
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="webkit" name="renderer">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title><?php echo config::getConfig('site_title'); ?></title>
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/global_reset.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/all_LightBlue.css?v=<?php echo time(); ?>" />
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/common_operate.css" />
</head>

<body>
<div class="operate_middle_page">
    <?php $this->import("_usermenu"); ?>
    <div class="common_pages service_center_pageheight padding_top_eight">
        <?php $this->import("servicecent_common_operate"); ?>

        <div class="help_center_content">
           <div class="latestnew_cont_title help_center_title">安全相关</div>
           <div class="help_center_txt">
              <span class="help_center_subtitle">什么是安全码，有什么作用？</span>
              <p>
                “安全码”是每一个账户最为重要的密码，他独立于登陆密码、资金密码之外，修改登陆密码、资金密码都必须使用安全码进行修改。
              </p>
              <span class="help_center_subtitle">如何修改登录密码、资金密码？</span>
              <p>
                修改密码只需输入安全码，再输入新的登录密码或者资金密码，即可完成密码修改操作。
              </p>
              <span class="help_center_subtitle">如何解绑银行资料？</span>
              <p>
                “安全码”同时也是解绑银行卡资料唯一渠道，在“个人中心”----“银行卡管理”----“解绑”。
              </p>
              <p>
                解绑时需要输入安全码，解绑完成72小时后才可进行“换绑”操作，解锁中的银行卡不影响充值提现等操作（活动期间无法修改）
              </p><br/>
              <p>
                请广大用户妥善保管安全码，切勿告知他人，因客户自身原因导致的账号被盗或者资金损失，平台一律不承担相关责任。
              </p>
              <p>
                如安全码遗忘，请及时联系在线客服。
              </p>
           </div>
        </div>
    </div>
</div>
<?php $this->import('public_tongji') ?>
</body>
</html>