<!DOCTYPE HTML>   <!-- 服务中心下责任与声明 -->
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="webkit" name="renderer">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title><?php echo config::getConfig('site_title'); ?></title>
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/global_reset.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/all_LightBlue.css?v=<?php echo time(); ?>" />
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/common_operate.css" />
</head>

<body>
<div class="operate_middle_page">
    <?php $this->import("_usermenu"); ?>
    <div class="common_pages service_center_pageheight padding_top_eight">
        <?php $this->import("servicecent_common_operate"); ?>

        <div class="help_center_content">
           <div class="latestnew_cont_title help_center_title">责任与声明</div>
           <div class="help_center_txt">
             <span class="help_center_subtitle">一、遵守会员规范及法律规定：</span>
             <p>
                 您注册成为中彩网彩票会员后，即可使用中彩网彩票所提供的各项服务(以下称本服务)。当会员使用本服务时，即表示除了同意遵守本服务条款外，还同意接受巴网游戏 对会员规范(包括各项游戏规则、公告及注意事项等)及相关法令规定之约束，巴网游戏 所有产品与客户服务、软件系统、网络架构等相关业务事宜，皆由菲律宾政府卡格扬经济特区The Cagayan Economic Zone Authority 所授权和监管的合法线上娱乐公司。使用本服务的会员请遵守使用者当地法令许可，如有违反将不在本服务负责范围。
             </p>
             <span class="help_center_subtitle">二、服务简介：</span>
             <p>
                 巴网游戏 在创造一个『长久信誉』、『安全稳定』、『公平公正』的优质娱乐服务平台，我们秉承以客为尊的态度，不断开发创新及了解客户需求是本公司引以为傲的经营理念，希望能创造出崭新的娱乐价值以及达到多方普及的目的，成为具有领导指标性的娱乐网站。
             </p>
             <span class="help_center_subtitle">三、真实登录义务：</span>
             <p>
                 基于巴网游戏 所提供的各项服务，您同意注册时依注册申请程序所提示的项目，登录您本人正确、真实及完整的个人资料；当您的个人资料有异动时，请立即更新，以维持您个人资料的正确、真实及完整。如因您登录不实资料或冒用他人名义以致于侵害他人权益或违法时，应自负法律责任；您所提供的个人资料不真实或个人资料有异动但没有更新以致于与原登录资料不符时，巴网游戏 有权随时终止您的会员资格及使用各项会员服务权利。
             </p>

             <span class="help_center_subtitle">四、服务停止与更改</span>
             <p>
                 1.会员登录资料不实。
             </p>
             <p>
                 2.使用他人的名义申请本服务。
             </p>
             <p>
                 3.违反游戏公平原则。
             </p>
             <p>
                 4.参与游戏或比赛时，故意钻研系统漏洞或利用游戏弱点以影响结果。
             </p>
             <p>
                 5.违反本服务条款时。
             </p>
             <p>
                 6.巴网游戏 不允许不公平的下注方式、双边下注、无风险下注及任何无风险解冻之下投注方式，如有发现上述问题的玩家，巴网游戏 有终止玩家帐号使用权力。如有任何争议问题，巴网游戏 有最终决定权。无论任何情形，就停止或更改服务或终止会员帐户服务所可能产生之困扰、不便或损害，本服务对任何会员或第三人均不负任何责任。
             </p>
             <span class="help_center_subtitle">五、服务暂停或中断：</span>
             <p>
                 (一) 巴网游戏 于下列情形之一，需暂停或中断本服务之全部或部分，对于使用者不负担任何赔偿责任：
             </p>
             <p>
                 1.对于本服务相关系统设备进行迁移、更换或维护时。
             </p>
             <p>
                 2.因不可归责于巴网游戏 国际所造成服务停止或中断。
             </p>
             <p>
                 3.因不可抗力所造成服务停止或中断。
             </p>

             <p>(二) 如因巴网游戏 对于本网站相关系统设备进行迁移、更换或维护而必须暂停或中断全部或部分服务时，巴网游戏 于暂停或中断前将以电子邮件通知或于本网站上发公告。</p>

             <p>(三) 对于本服务之暂停或中断，可能造成您使用上的不便、资料遗失或其他经济及时间上的损失，您平时应采取适当的防护措施，以保障您的权益。</p>

             <span class="help_center_subtitle">六、保管义务：</span>

             <p>会员有义务妥善保管在巴网游戏 游戏帐号与密码，并为此帐号与密码登入系统后所进行的一切活动负责。为维护会员自身权益，请勿将帐号与密码泄露或提供给第三人知悉，或出借或转让他人使用。</p>

             <span class="help_center_subtitle">七、同意游戏规则：</span>

             <p>为避免使用者于本平台投注游戏时产生争议，各项规则在游戏中心均有详细说明，请务必详细阅读本服务所定的各项规则，会员一经开始使用本服务，即被视为已接受所有规定。</p>

             <span class="help_center_subtitle">八、会员规范之增订及修改：</span>

             <p>本服务条款如有增订或修改，您同意自该修订条款于本网站公告之时起受其约束，本网站将不对会员个别通知。如您看过公告后继续使用本服务，则视为您已经同意该修订条款。</p>

           </div>
        </div>
    </div>
</div>
<?php $this->import('public_tongji') ?>
</body>
</html>