<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="webkit" name="renderer">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title></title>
</head>
<body>
<form name='diy' id="diy" action='<?php echo $qrcode_url; ?>' target="_blank"  method='post'>
    <input name="pay" type="submit" value="启动 QQ/微信/支付宝 支付" />
</form>
</body>
</html>









