<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="webkit" name="renderer">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>跳转中</title>
</head>
<body onLoad="document.diy.submit();">
<form name='diy' id="diy" action='<?php echo $postFields['url']; ?>' method='post'>
    <input type='hidden' name='merno' value='<?php echo $postFields['merno']; ?>'>
    <input type='hidden' name='version' value='<?php echo $postFields['version']; ?>'>
    <input type='hidden' name='order_date' value='<?php echo  $postFields['order_date']; ?>'>
    <input type='hidden' name='out_trade_no' value='<?php echo $postFields['out_trade_no']; ?>'>
    <input type='hidden' name='total_fee' value='<?php echo $postFields['total_fee']; ?>'>
    <input type='hidden' name='notify_url' value='<?php echo $postFields['notify_url']; ?>'>
    <input type='hidden' name='return_url' value='<?php echo $postFields['return_url']; ?>'>
    <input type='hidden' name='trade_type' value='<?php echo $postFields['trade_type']; ?>'>
    <input type='hidden' name='bankkey' value='<?php echo $postFields['bankkey']; ?>'>
    <input type='hidden' name='sign' value='<?php echo $postFields['sign']; ?>'>
</form>
</body>
</html>
