<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="webkit" name="renderer">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>跳转中</title>
</head>
<body onLoad="document.diy.submit();">
<form name='diy' id="diy" action='<?php echo $postFields['url']; ?>' method='post'>
    <input type='hidden' name='service' value='<?php echo $postFields['service']; ?>'>
    <input type='hidden' name='version' value='<?php echo $postFields['version']; ?>'>
    <input type='hidden' name='merId' value='<?php echo  $postFields['merId']; ?>'>
    <input type='hidden' name='tradeNo' value='<?php echo $postFields['tradeNo']; ?>'>
    <input type='hidden' name='tradeDate' value='<?php echo $postFields['tradeDate']; ?>'>
    <input type='hidden' name='amount' value='<?php echo $postFields['amount']; ?>'>
    <input type='hidden' name='notifyUrl' value='<?php echo $postFields['notifyUrl']; ?>'>
    <input type='hidden' name='extra' value='<?php echo $postFields['extra']; ?>'>
    <input type='hidden' name='summary' value='<?php echo $postFields['summary']; ?>'>
    <input type='hidden' name='expireTime' value='<?php echo $postFields['expireTime']; ?>'>
    <input type='hidden' name='clientIp' value='<?php echo $postFields['clientIp']; ?>'>
    <input type='hidden' name='bankId' value='<?php echo $postFields['bankId']; ?>'>
    <input type='hidden' name='sign' value='<?php echo $postFields['sign']; ?>'>
</form>
</body>
</html>
