<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="webkit" name="renderer">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <script src="<?php echo $imgCdnUrl ?>/js/jquery.js" type="text/javascript"></script>
    <title></title>
    <script>
        $(document).ready(function(){
            $("input[name=pay]").click(function(){
                window.open($("input[name=qrcode_url]").val(), "_blank");
            });
        });
    </script>
</head>
<body>
<input name="qrcode_url" type="hidden" value="<?php echo $postFields; ?>" />
<input name="pay" type="button" value="启动 QQ/微信/支付宝 支付" />
</body>
</html>




















