<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="webkit" name="renderer">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>跳转中</title>
    <script src="<?php echo $imgCdnUrl ?>/js/jquery.js" type="text/javascript"></script>
</head>
<body>
<input type="hidden" name="url" value="<?php echo $postFields; ?>" />
    <input type="button" name="pay" value="启动 微信/支付宝/QQ 支付" />
<script>
    $(document).ready(function(){
        $("input[name=pay]").click(function(){
            var url = $('[name=url]').val();
            window.open(url, "_blank");
        });
    });
</script>
</body>
</html>

