<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="webkit" name="renderer">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>跳转中</title>
</head>
<body onLoad="document.dingyiPay.submit();">
<a>正在加载，请勿离开页面或者刷新页面</a>
<form name='dingyiPay' id="diy" action='<?php echo $postFields['url']; ?>' method='post'>

</form>
</body>
</html>



