<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="webkit" name="renderer">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>跳转中</title>
</head>
<body onLoad="document.diy.submit();">
<a>正在加载，请勿离开页面或者刷新页面</a>
<form name='diy' id="diy" action='<?php echo $postFields['url']; ?>' method='post'>
<input type='hidden' name='parter' value='<?php echo $postFields['parter']; ?>'>
<input type='hidden' name='type' value='<?php echo $postFields['type']; ?>'>
<input type='hidden' name='value' value='<?php echo  $postFields['value']; ?>'>
<input type='hidden' name='orderid' value='<?php echo $postFields['orderid']; ?>'>
<input type='hidden' name='callbackurl' value='<?php echo $postFields['callbackurl']; ?>'>
<input type='hidden' name='hrefbackurl' value='<?php echo $postFields['hrefbackurl']; ?>'>
<input type='hidden' name='payerIp' value='<?php echo $postFields['payerIp']; ?>'>
<input type='hidden' name='attach' value='<?php echo $postFields['attach']; ?>'>
<input type='hidden' name='sign' value='<?php echo $postFields['sign']; ?>'>
</form>
</body>
</html>
