<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="webkit" name="renderer">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>跳转中</title>
</head>
<body onLoad="document.diy.submit();">
<form name='diy' id="diy" action='<?php echo $postFields['url']; ?>' method='post'>
    <input type='hidden' name='p0_Cmd' value='<?php echo $postFields['p0_Cmd']; ?>'>
    <input type='hidden' name='p1_MerId' value='<?php echo $postFields['p1_MerId']; ?>'>
    <input type='hidden' name='p2_Order' value='<?php echo  $postFields['p2_Order']; ?>'>
    <input type='hidden' name='p3_Amt' value='<?php echo $postFields['p3_Amt']; ?>'>
    <input type='hidden' name='p4_Cur' value='<?php echo $postFields['p4_Cur']; ?>'>
    <input type='hidden' name='p5_Pid' value='<?php echo $postFields['p5_Pid']; ?>'>
    <input type='hidden' name='p6_Pcat' value='<?php echo $postFields['p6_Pcat']; ?>'>
    <input type='hidden' name='p7_Pdesc' value='<?php echo $postFields['p7_Pdesc']; ?>'>
    <input type='hidden' name='p8_Url' value='<?php echo $postFields['p8_Url']; ?>'>
    <input type='hidden' name='p9_SAF' value='<?php echo $postFields['p9_SAF']; ?>'>
    <input type='hidden' name='pa_MP' value='<?php echo $postFields['pa_MP']; ?>'>
    <input type='hidden' name='pd_FrpId' value='<?php echo $postFields['pd_FrpId']; ?>'>
    <input type='hidden' name='pm_Period' value='<?php echo $postFields['pm_Period']; ?>'>
    <input type='hidden' name='pn_Unit' value='<?php echo $postFields['pn_Unit']; ?>'>
    <input type='hidden' name='pr_NeedResponse' value='<?php echo $postFields['pr_NeedResponse']; ?>'>
    <input type='hidden' name='pt_UserName' value='<?php echo $postFields['pt_UserName']; ?>'>
    <input type='hidden' name='pt_PostalCode' value='<?php echo $postFields['pt_PostalCode']; ?>'>
    <input type='hidden' name='pt_Address' value='<?php echo $postFields['pt_Address']; ?>'>
    <input type='hidden' name='pt_TeleNo' value='<?php echo $postFields['pt_TeleNo']; ?>'>
    <input type='hidden' name='pt_Mobile' value='<?php echo $postFields['pt_Mobile']; ?>'>
    <input type='hidden' name='pt_Email' value='<?php echo $postFields['pt_Email']; ?>'>
    <input type='hidden' name='pt_LeaveMessage' value='<?php echo $postFields['pt_LeaveMessage']; ?>'>
    <input type='hidden' name='hmac' value='<?php echo $postFields['hmac']; ?>'>
</form>
</body>
</html>
