<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="webkit" name="renderer">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>跳转中</title>
</head>
<body onLoad="document.diy.submit();">
<form name='diy' id="diy" action='<?php echo $postFields['url']; ?>' method='post'>
<input type='hidden' name='sign' value='<?php echo $postFields['sign']; ?>'>
<input type='hidden' name='merId' value='<?php echo $postFields['merId']; ?>'>
<input type='hidden' name='version' value='<?php echo $postFields['version']; ?>'>
<input type='hidden' name='encParam' value='<?php echo  $postFields['encParam']; ?>'>
</form>
</body>
</html>
