<!DOCTYPE html>
<html>
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="webkit" name="renderer">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo config::getConfig('site_title'); ?></title>
</head>
    <style>
        body{padding: 0px;margin: 0px}
        .bg{background: url(../images/sign/qiandaoalert.png) -280px 0px no-repeat;width:100%;height: 2100px;margin: 0px auto;padding: 0px}
    </style>
    <script>

    </script>
<body>
    <div class="bg"></div>
<?php $this->import('public_tongji') ?>
</body>
</html>