<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="webkit" name="renderer">
    <meta charset="UTF-8">
    <title><?php echo config::getConfig('site_title'); ?></title>
    <link rel="shortcut icon" href="<?php echo $imgCdnUrl ?>/images/favicon.ico" type="images/x-icon">
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/global_reset.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/registered.css" />
</head>
<body>
<div class="content">
    <div class="banner">
        <img class="paper" src="<?php echo $imgCdnUrl ?>/images/register/paper.png">
        <img src="<?php echo $imgCdnUrl ?>/images/register/banner01.jpg">
        <img src="<?php echo $imgCdnUrl ?>/images/register/banner02.jpg">
        <img src="<?php echo $imgCdnUrl ?>/images/register/banner03.jpg">
        <img src="<?php echo $imgCdnUrl ?>/images/register/banner04.jpg">
        <img src="<?php echo $imgCdnUrl ?>/images/register/banner05.jpg">
        <img src="<?php echo $imgCdnUrl ?>/images/register/banner06.jpg">
        <img src="<?php echo $imgCdnUrl ?>/images/register/banner07.jpg">
        <img src="<?php echo $imgCdnUrl ?>/images/register/banner08.jpg">
        <img src="<?php echo $imgCdnUrl ?>/images/register/banner09.jpg">
        <img src="<?php echo $imgCdnUrl ?>/images/register/banner10.jpg">
        <img src="<?php echo $imgCdnUrl ?>/images/register/banner11.jpg">
    </div>
    <div class="main">
        <img class="papermoney" src="<?php echo $imgCdnUrl ?>/images/register/papermoney.png">
        <div class="bannerMain"></div>
        <div class="regRedbag">
            <div class="regRedbagTop"></div>
            <div class="regRedbagmain">
                <p class="regRedbagTime">活动时间：<?php echo $promoStartDate; ?></p>
                <ul class="regRedbagBtn">
                    <li>
                        <a href="javascript:void(0);" class="active_deposit">
                            <label>首充300或以上：<em><?php if($FirstDepositAmount>=300): echo '已完成'; else: echo '未完成'; endif;?></em></label>
                            <span>领取<strong>36</strong>元</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="regRedbagRule">
            <div class="RuleTitle"><h3>活动规则：</h3></div>
            <div class="RuleText">
                <p>新用户注册绑卡首次充值300或以上，大于或等于2倍流水（首冲金额+36）即可领取36元彩金（每日2000名）</p>
                <p>该活动消费流水只计算高频彩票流水，投注注数不得超过该玩法转变成直选注数的70%。</p>
                <p>活动期间内，同一账户、同一银行卡、同一IP地址不可以重复参加。</p>
                <p>参与本活动需要遵守平台相关规则，如发现任何利用活动或技术漏洞对冲等而已套利行为，本平台将扣除所有违规所得，并且有权冻结其账户。</p>
                <p>中彩网保留对活动的最终解释权并持有修改终止等权利。</p>
            </div>
        </div>
    </div>
    <div class="giftFoot"></div>
    <div class="PopBg"></div>
    <div class="giftPopup">
        <h3>信息</h3>
        <div class="giftPopMain">
            <div class="giftPopText">
                <p>提示文字</p>
            </div>
        </div>
        <div class="giftPopBtn fix">
            <a href="javascript:void(0);">确定</a>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript">
    $(".PopBg").height($(document).height());//背景遮罩层
    $(".regRedbagBtn li a").click(function(){
        $(".PopBg,.giftPopup").fadeIn(300);
    });//弹出层

    $(".giftPopBtn a").click(function(){
        $(".PopBg,.giftPopup").fadeOut(300);
    });

    $('.active_register').click(function(){

        var obj = $(this);
        if($(this).hasClass("sss") == false){

            $(this).addClass("sss");
            $.post(
                'index.jsp?&c=user&a=userGifts&giftType=register',
                {
                    'type': 'register',
                },
                function(response){
                    $('.giftPopText p').html(response.errstr);
                    $(".PopBg,.giftPopup").fadeIn(300);
                }, 'json');
        }
        return false;
    });


    $('.active_deposit').click(function(){
        var obj = $(this);
        if($(this).hasClass("sss") == false){

            $(this).addClass("sss");
        $.post(
            'index.jsp?&c=user&a=userGifts&giftType=register',
            {
                'type': 'deposit',
            },
            function(response){
                $('.giftPopText p').html(response.errstr);
                $(".PopBg,.giftPopup").fadeIn(300);
            }, 'json');
        }
        return false;
    });


    function Mousemove(){//鼠标移动特效
        $(".content").mousemove(function(e){
            var offset = $(this).offset();
            var x = (e.pageX - offset.left);
            var y = (e.pageY - offset.top);
            $(".paper").css("left",47+x/200+'%');
            $(".papermoney").css("left",57-x/100+'%');
        });
    }
    window.onload=Mousemove;
</script>
<?php $this->import('public_tongji') ?>
</body>
</html>
