<!DOCTYPE HTML>       <!-- 会员管理页面中返点页面 -->
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="webkit" name="renderer">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title><?php echo config::getConfig('site_title'); ?></title>
        <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/global_reset.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/all_default.css" />
    </head>

    <body>
       <div class="fandian_page_part">
            <div class="form_group">
                  <label class="control_label">用户名：</label>
                  <div class="col_sm_10"><?php echo $user['username']; ?></div>
            </div>
            <div class="form_group">
                  <label for="fanDian" class="control_label">返点：</label>
                  <div class="col_sm_10">
                      <select class="form_control" name="prize_group" id="fanDian">
                          <?php foreach ($aPrizeMode as $prize_mode=>$rebate): ?>
                              <option value="<?php echo $prize_mode; ?>" <?php if ($prize_mode == $subPrizeMode) echo 'selected'; ?>><?php echo $prize_mode.'/'.$rebate; ?>
                              </option>
                          <?php endforeach; ?>
                      </select>
                   </div>
             </div>
            <div class="close_order_layer">
                 <input type="button" class="default_blue_btn" value="设置">
                 <a href="javascript:void(0);" class="default_gray_btn closeDialogBtn">返回</a>
            </div>
       </div>

    <script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/jquery-1.8.3.min.js"></script>
    <script>
    $(function() {
      $('a.closeDialogBtn').on('click', function(){
            var index = parent.layer.getFrameIndex(window.name);      //获取当前窗口索引
            parent.layer.close(index);
        });

        $('input.default_blue_btn').on('click', function(){
            $.post(
                'index.jsp?c=user&a=setRebate',
                {
                    'user_id': '<?php echo $user['user_id']; ?>',
                    'prize_group': $('select[name=prize_group]  option:selected').val(),

                },
                function(response) {
                    parent.layer.alert(response.errstr,9);
                    if (response.errno == 0) {
                        window.location.reload();
                    }
                }, 'json');
        });

    });
</script>
    <?php $this->import('public_tongji') ?>
</body>
</html>