<!DOCTYPE HTML>    <!-- 团队即时报表 -->
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta content="webkit" name="renderer"><!-- 页面默认用极速核 -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge"><!-- 指定浏览器按照最高的标准模式解析页面针对IE -->
    <meta content="telephone=no,email=no" name="format-detection" /><!-- 使设备浏览网页时对数字不启用电话功能 -->
    <meta name="apple-touch-fullscreen" content="YES"/><!-- "添加到主屏幕"后，全屏显示 -->
    <meta name="apple-mobile-web-app-capable" content="yes"/>  <!-- 如果内容设置为YES，Web应用程序运行在全屏模式;否则，它不会。默认行为是使用Safari浏览器显示网页内容 -->
    <!--<meta http-equiv="Cache-Control" content="no-cache"/>-->  <!-- 每次打开都清除浏览器页面缓存 -->
    <meta http-equiv="Cache-Control" content="no-siteapp" /><!-- 度SiteApp转码声明 -->
    <meta name="viewport" content="width=device-width,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <title><?php echo config::getConfig('site_title'); ?></title>
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/mobileStyle.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/mobile_overallStyle.css">
    <script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/jquery-1.8.3.min.js"></script>
</head>

<body>
<div class="operate_middle_page">
      <!--/*头部*/-->
        <header>
            <img style="width:0.3rem" src="<?php echo $imgCdnUrl ?>/images/mobile/arrows_left.png"/>
            <a href="index.jsp?c=user&a=teamReportCentral">返回</a>
            <p>团队帐变明细</p>
        </header>
        <div class="defoperate_record_tablist">
            <ul class="defoperate_record_tabtitleUl">
                <li>账户</li>
                <li>平台活动</li>
                <li>彩票盈亏</li>
            </ul>
             <ul class="defoperate_record_tabtitleUL">
            <?php if ($flag): ?>
                    <li>
                        <?php if ($self['level'] != 10): ?>
                            <?php echo $self['username']; ?>(自己)
                        <?php else: ?>
                            <?php echo $self['username']; ?>
                        <?php endif; ?>
                    </li>
                    <li><?php echo number_format($self['total_promo_active'], 2); ?></li>
                    <li><?php echo number_format($self['total_win'], 2); ?></li>
            </ul>
            <div class="OrderbyDiv DisplayNone">
                <li class="OrderbyText">充值总额</li><li><?php echo number_format($self['total_deposit'], 2); ?></li>
                <li class="OrderbyText">提现总额</li><li><?php echo number_format($self['total_withdraw'], 2); ?></li>
                <li class="OrderbyText">彩票投注</li><li><?php echo number_format($self['total_amount'], 2); ?></li>
                <li class="OrderbyText">彩票返奖</li><li><?php echo number_format($self['total_prize'], 2); ?></li>
                <li class="OrderbyText">彩票返点</li><li><?php echo number_format($self['total_rebate'], 2); ?></li>
                <button class="OrderbyDivX">关闭</button>
            </div>
                <?php foreach ($curPageTeamReport as $v): ?>
                    <ul class="defoperate_record_tabtitleUL">
                        <td>
                            <?php if ($v['level'] != 10): ?>
                                <a href="index.jsp?c=user&a=<?php echo ACTION; ?>&username=<?php echo $v['username']; ?>"><?php echo $v['username']; ?></a>
                            <?php else: ?>
                                <?php echo $v['username']; ?>
                            <?php endif; ?>
                        </td>
                        <td><?php echo number_format($v['total_promo_active'], 2); ?></td>
                        <td><?php echo number_format($v['total_win'], 2); ?></td>
                    </ul>
             <div class="OrderbyDiv DisplayNone">
                <li>充值总额</li><li><?php echo number_format($self['total_deposit'], 2); ?></li>
                <li>提现总额</li><li><?php echo number_format($self['total_withdraw'], 2); ?></li>
                <li>彩票投注</li><li><?php echo number_format($self['total_amount'], 2); ?></li>
                <li>彩票返奖</li><li><?php echo number_format($self['total_prize'], 2); ?></li>
                <li>彩票返点</li><li><?php echo number_format($self['total_rebate'], 2); ?></li>
                <button class="OrderbyDivX">关闭</button>
            </div>
                <?php endforeach; ?>
            <?php else: ?>
                <th colspan="9" class="text_center">您无权查看此用户或此用户不存在！</th>
            <?php endif; ?>
        </div>
    </div>
             <div>
                <?php echo $pageList; ?>
            </div>
</div>
<script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/public.js"></script>
<script>
    $(function() {
        //设置默认值
        $('input[name=username]').val('<?php echo $username; ?>');
        $('#regStartDate').val('<?php echo $regStartDate; ?>');
        $('#regEndDate').val('<?php echo $regEndDate; ?>');
        $('select[name=range]').val('<?php echo $range; ?>');

    });

    function switch_sort(key) {
        var old_key = $('#sortKey').val();
        if (key == old_key) {
            $('#sortDirection').val(-1 * $('#sortDirection').val());
        } else {
            $('#sortDirection').val(-1);
            $('#sortKey').val(key);
        }
        //submit
        $('#form1').submit();
    }
        $(".defoperate_record_tabtitleUL").each(function(i){
       $(".defoperate_record_tabtitleUL").eq(i).click(function(){
           $(".OrderbyDiv").eq(i).addClass("DisplayBlock").siblings().removeClass("DisplayBlock");
        })
    })
    $(".OrderbyDivX").click(function(){
        $(".OrderbyDiv").removeClass("DisplayBlock");
    })
</script>
<?php $this->import('public_tongji') ?>
</body>
</html>