<?php $this->import("head"); ?>
<link href="<?php echo $imgCdnUrl ?>/js/jqueryUI/dialog/css/jquery.dialog.<?php echo $styleDir; ?>.css" rel="stylesheet" type="text/css"  />
<script src="<?php echo $imgCdnUrl ?>/js/jqueryUI/dialog/js/jquery.dialog.js" type="text/javascript"></script>
<script>
    $(function() {

        $(".choose").click(function() {
            $.post(
                    'index.jsp?c=user&a=setting',
                    {
                        'style': $(this).attr("id")
                    },
            function(response) {

                if (response == 1) {
                    $('<div title="切换成功">切换成功</div>').dialog({
                        bgiframe: true,
                        width: 300,
                        buttons: {
                            "关闭": function() {
                                $(this).dialog("close", window.parent);       //关闭这个对话框
                                window.parent.location.reload();
                            }
                        }
                    }, window.parent);

                }
            });

        });
    });
</script>

<div style="background-image:url(../images/<?php echo $styleDir; ?>/choise_style.jpg); width:926px; height:510px; "  >

    <div style="top:450px;left: 175px;   width:130px;height:35px;position:absolute; cursor: pointer; " id="blue" class="choose" > </div>
    <div style="top:450px;left: 650px;   width:130px;height:35px;position:absolute; cursor: pointer; " id="dark" class="choose"> </div>
</div>

<?php $this->import("foot"); ?>
