<!DOCTYPE HTML>   <!-- 团队日结报表 -->
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="webkit" name="renderer">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title><?php echo config::getConfig('site_title'); ?></title>
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/all_LightBlue.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/global_reset.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo $imgCdnUrl ?>/css/common_operate.css" />
    <script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/layer-v2.4/layer.js"></script> <!-- layer调用弹出层 -->
</head>

<body>
<div class="operate_middle_page">
    <?php $this->import("_usermenu"); ?>

    <div class="common_pages default_operate_pageheight">
        <div class="default_record_search">
            <form name="form1" id="form1" action="" method="GET">
                <ul>
                    <li>
                        <label class="search_record_datelab">时间：</label>
                        <div class="record_date_range">
                            <input size="15" name="startDate" id="startDate" my97mark="false" onfocus="WdatePicker({dateFmt: 'yyyy-MM-dd'})" class="default_common_input datepicker85"/>
                            <em>&ndash;&ndash;</em>
                            <input size="15" name="endDate" id="endDate" my97mark="false" onfocus="WdatePicker({dateFmt: 'yyyy-MM-dd'})" class="default_common_input datepicker85"/>
                        </div>
                    </li>
                    <li>
                        <label class="margin_left_thirty">用户名：</label>
                        <input name="username" class="default_common_input" type="text"/>
                    </li>
                    <li>
                        <input type="hidden" name="c" value="user"/>
                        <input type="hidden" name="a" value="<?php echo ACTION; ?>"/>
                        <input type="hidden" id="sortKey"  name="sortKey" value="<?php echo $sortKey; ?>" >
                        <input type="hidden" id="sortDirection" name="sortDirection" value="<?php echo $sortDirection ?>"/>
                        <input type="submit" value="查询" class="default_record_searchbtn default_common_btn">
                        <!--  注:默认只能查询截止到昨日的数据 -->
                    </li>
                    <li class="float_right">
                        <div>
                            <?php echo $pageList; ?>
                        </div>
                    </li>
                </ul>
            </form>
        </div>

        <table class="defoperate_record_tablist">
            <thead>
            <tr class="defoperate_record_tabtitle">
                <th width="7%">账户</th>
                <th width="9%" onclick="javascript:switch_sort('day');"><span class="Orderby">日期<i class="<?php if ($sortKey == 'day' && $sortDirection == 1): ?>OrderbyUp<?php elseif ($sortKey == 'day' && $sortDirection == -1): ?>OrderbyDown<?php else: ?>OrderbyBoth<?php endif; ?>"></i></span></th>
                <th width="8%" onclick="javascript:switch_sort('total_deposit');"><span class="Orderby">充值总额<i class="<?php if ($sortKey == 'total_deposit' && $sortDirection == 1): ?>OrderbyUp<?php elseif ($sortKey == 'total_deposit' && $sortDirection == -1): ?>OrderbyDown<?php else: ?>OrderbyBoth<?php endif; ?>"></i></span></th>
                <th width="8%" onclick="javascript:switch_sort('total_withdraw');"><span class="Orderby">提现总额<i class="<?php if ($sortKey == 'total_withdraw' && $sortDirection == 1): ?>OrderbyUp<?php elseif ($sortKey == 'total_withdraw' && $sortDirection == -1): ?>OrderbyDown<?php else: ?>OrderbyBoth<?php endif; ?>"></i></span></th>
                <th width="8%" onclick="javascript:switch_sort('total_amount');"><span class="Orderby">彩票投注<i class="<?php if ($sortKey == 'total_amount' && $sortDirection == 1): ?>OrderbyUp<?php elseif ($sortKey == 'total_amount' && $sortDirection == -1): ?>OrderbyDown<?php else: ?>OrderbyBoth<?php endif; ?>"></i></span></th>
                <th width="8%" onclick="javascript:switch_sort('total_prize');"><span class="Orderby">彩票中奖<i class="<?php if ($sortKey == 'total_prize' && $sortDirection == 1): ?>OrderbyUp<?php elseif ($sortKey == 'total_prize' && $sortDirection == -1): ?>OrderbyDown<?php else: ?>OrderbyBoth<?php endif; ?>"></i></span></th>
                <th width="8%" onclick="javascript:switch_sort('total_rebate');"><span class="Orderby">彩票返点<i class="<?php if ($sortKey == 'total_rebate' && $sortDirection == 1): ?>OrderbyUp<?php elseif ($sortKey == 'total_rebate' && $sortDirection == -1): ?>OrderbyDown<?php else: ?>OrderbyBoth<?php endif; ?>"></i></span></th>
                <th width="8%" onclick="javascript:switch_sort('total_promo_active');"><span class="Orderby">彩票活动<i class="<?php if ($sortKey == 'total_promo_active' && $sortDirection == 1): ?>OrderbyUp<?php elseif ($sortKey == 'total_promo_active' && $sortDirection == -1): ?>OrderbyDown<?php else: ?>OrderbyBoth<?php endif; ?>"></i></span></th>
                <th width="8%" onclick="javascript:switch_sort('total_win');"><span class="Orderby">盈亏<i class="<?php if ($sortKey == 'total_win' && $sortDirection == 1): ?>OrderbyUp<?php elseif ($sortKey == 'total_win' && $sortDirection == -1): ?>OrderbyDown<?php else: ?>OrderbyBoth<?php endif; ?>"></i></span></th>
            </tr>
            </thead>
            <tbody>
            <?php if ($flag): ?>

                <!--
                        <tr>
                                <td>
                                    <?php if ($self['level'] != 10): ?>
                                       <?php echo $self['username']; ?>(自己)
                                    <?php else: ?>
                                        <?php echo $self['username']; ?>(用户)
                                    <?php endif; ?>
                                </td>
                                <td><?php echo $day; ?></td>
                                <td><?php echo number_format($self[$day]['total_deposit'], 2); ?></td>
                                <td><?php echo number_format($self[$day]['total_withdraw'], 2); ?></td>
                                <td><?php echo number_format($self[$day]['total_amount'], 2); ?></td>
                                <td><?php echo number_format($self[$day]['total_prize'], 2); ?></td>
                                <td><?php echo number_format($self[$day]['total_rebate'], 2); ?></td>
                                <td><?php echo number_format($self[$day]['total_promo_active'], 2); ?></td>
                                <td><?php echo number_format($self[$day]['total_win'], 2); ?></td>
                            </tr>
                            -->
                <?php foreach ($curPageTeamReport as $v): ?>
                    <tr>
                        <td>
                            <?php if ($selfData['level'] != 10): ?>
                                <!--
                                        <a href="index.jsp?c=user&a=<?php echo ACTION; ?>&username=<?php echo $selfData['username']; ?>" style="color: yellow"></a>
                                        -->
                                <?php echo $selfData['username']; ?>
                            <?php else: ?>
                                <?php echo $selfData['username']; ?>
                            <?php endif; ?>
                        </td>
                        <td><?php echo $v['day']; ?></td>
                        <td><?php echo number_format($v['total_deposit'], 2); ?></td>
                        <td><?php echo number_format($v['total_withdraw'], 2); ?></td>
                        <td><?php echo number_format($v['total_amount'], 2); ?></td>
                        <td><?php echo number_format($v['total_prize'], 2); ?></td>
                        <td><?php echo number_format($v['total_rebate'], 2); ?></td>
                        <td><?php echo number_format($v['total_promo_active'], 2); ?></td>
                        <td><?php echo number_format($v['total_win'], 2); ?></td>
                    </tr>

                <?php endforeach; ?>

            <?php else: ?>
                <th colspan="9" class="text_center">您无权查看此用户或此用户不存在！</th>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
    <table class="bet_count_layer">
        <tbody>
        <tr class="bet_count_thispage defoperate_record_tablist">
            <td width="16%" class="count_first_line rose_red_font" colspan="2">本页合计：</td>
            <td width="8%"><?php echo number_format($pageData['page_deposit'], 2); ?></td>
            <td width="8%"><?php echo number_format($pageData['page_withdraw'], 2); ?></td>
            <td width="8%"><?php echo number_format($pageData['page_amount'], 2); ?></td>
            <td width="8%"><?php echo number_format($pageData['page_prize'], 2); ?></td>
            <td width="8%"><?php echo number_format($pageData['page_rebate'], 2); ?></td>
            <td width="8%"><?php echo number_format($pageData['page_promo_active'], 2); ?></td>
            <td width="8%"><?php echo number_format($pageData['page_win'], 2); ?></td>
        </tr>
        <tr class="defoperate_record_tablist">
            <td class="count_first_line rose_red_font" colspan="2">总计：</td>
            <td><?php echo number_format($teamTotal['team_total_deposit'], 2); ?></td>
            <td><?php echo number_format($teamTotal['team_total_withdraw'], 2); ?></td>
            <td><?php echo number_format($teamTotal['team_total_amount'], 2); ?></td>
            <td><?php echo number_format($teamTotal['team_total_prize'], 2); ?></td>
            <td><?php echo number_format($teamTotal['team_total_rebate'], 2); ?></td>
            <td><?php echo number_format($teamTotal['team_total_promo_active'], 2); ?></td>
            <td><?php echo number_format($teamTotal['team_total_win'], 2); ?></td>
        </tr>
        </tbody>
    </table>
    <div class="common_pages ten_height">&nbsp;</div>
</div>
<script type="text/javascript" src="<?php echo $imgCdnUrl ?>/js/jquery.plugin.js"></script><!--jquery小插件-->
<script>
    $(function() {
        //设置默认值
        $('input[name=username]').val('<?php echo $username; ?>');
        $('#startDate').val('<?php echo $startDate; ?>');
        $('#endDate').val('<?php echo $endDate; ?>');

    });

    function switch_sort(key) {
        var old_key = $('#sortKey').val();
        if (key == old_key) {
            $('#sortDirection').val(-1 * $('#sortDirection').val());
        } else {
            $('#sortDirection').val(-1);
            $('#sortKey').val(key);
        }

        //submit
        $('#form1').submit();
    }
</script>
<?php $this->import('public_tongji') ?>
</body>
</html>